### ISSUE TITLE
Install the library system-wide

### ISSUE THREAD

**Issue by tbarbette** [private-octopus/picoquic#1054]
Hi all,

Is there a way to install the library system-wide? So external apps can link against libpicoquic-core.a?

I guess cmake can handle such a thing if it's not currently possible?

Cheers,
Tom

**Comment by huitema** [comment]
Something like "make install" ? Yes, that's a great idea. I am not much of a CMake expert, but I will be happy to take a PR if someone prepares it.

**Comment by huitema** [comment]
@tbarbette can you take a look at PR #1058 ? It should be doing pretty much what you want.

**Comment by huitema** [comment]
Done in PR #1058
