### ISSUE TITLE
No peer_addr set by picoquic_prepare_next_packet

### ISSUE THREAD

**Issue by tbarbette** [private-octopus/picoquic#1063]
Hi all,

I made a client based on the picoquic sample, the event loop and order of things is a little bit changed but I think it's correct.

My problem is that after having the "connection almost ready" callback, the subsequent call to `picoquic_prepare_next_packet` does not set the "peer_addr". Therefore, the call to `picoquic_send_through_socket` to send that packet fails with the error 89. The packet returned is 147 bytes, not sure what to say more. The local address is set and correct.

So why could the peer_addr be not set (the ss_family is 0)?

I print in the callback the value of picoquic_get_peer_addr and it's correct.

I tried with today's version and one from a few months ago and it's the same problem.

Only lead is maybe some race condition. The client opens the connection by sending a 1252 byte packet. Then the server answers with 3 packets. 1252 bytes, 723 and 1440. But the client process the first two packets, then says "connection almost ready", creates this buggy 147 bytes packets that is not sent, then process the 1440 bytes packets.

The server is the normal sample server.

Thanks for the help,
Tom

**Comment by huitema** [comment]
The peer address is set when receiving a packet with documented source address. That documentation depends on the application's implementation of the socket layer. Does your application set the source address?

**Comment by huitema** [comment]
@tbarbette I did test the sample code and I did not reproduce the issue. I think I would need to look at your client to understand the problem.

**Comment by tbarbette** [comment]
Yes, the sample is working great. The problem appears when I use my client with the sample server. 
My application does not specifically set the source address. But the problem here is the peer address not being set on the client. The server is the sample one (that works with the sample client) so I guess it puts its local address correctly, so the client should get it correctly. And indeed when I print on the almost_ready callback both peer and local address, it's there and correct. But somehow, when the "write" loop runs afterwards, it generates some packet that has no peer address.
I'll clean the app.

**Comment by huitema** [comment]
There is probably a subtle difference between your client and the sample client, and that's causing the issue. It is either an issue in your client, or something in your client that causes the sample code to misbehave. That means we need either better documentation, or fix a bug in the sample, or both. Waiting for your analysis.

**Comment by tbarbette** [comment]
The code is there if you have time to look : https://github.com/tbarbette/wrk2/blob/wrk3/src/quic.h
You may try (assuming both libs are installed with your own patches) with `./configure && make && ./wrk -R -1 --timeout 1 -q -t 1 -c 1 http://192.168.64.1:4433/index.htm` (the path is not sent as it fails before).

The output should be something like (with tcpdump in background)
```
Running 10s test @ http://192.168.64.1:4433/bin-8k
  1 threads and 1 connections
Creating QUIC for thread
No token file present. Will create one as <token_store.bin>.
Socket 2 2 17...
Creating Context for addr 140a8c0 (host 192.168.64.1)
Starting Client Context
Initial connection ID: ef9e231065a7884c
Marking stream 0
Opened stream 0
WRITEABLE
PREPARING NEXT PACKET
WRITE 1252 bytes, peer addr 140a8c0 (fam 2), local address 5555 (fam 0) <---------------- the local address is not set here, but it goes okay... I think this is normal and should be a feature in any case. I should be able to set myself as "0.0.0.0" and let the socket subsystem handle this, no?
WRITEABLE
PREPARING NEXT PACKET
Wakeup in 1000 msec. Return was 0. Length 0
17:36:25.653955 b8:83:03:6f:43:49 > b8:83:03:6f:43:12, ethertype IPv4 (0x0800), length 1294: 192.168.63.15.37187 > 192.168.64.1.4433: UDP, length 1252
17:36:25.659567 b8:83:03:6f:43:11 > b8:83:03:6f:43:49, ethertype IPv4 (0x0800), length 1294: 192.168.64.1.4433 > 192.168.63.15.37187: UDP, length 1252
READ 1252 <------------------------------------------------------- at this point we received a packet from the server, so all address should be known
17:36:25.660615 b8:83:03:6f:43:11 > b8:83:03:6f:43:49, ethertype IPv4 (0x0800), length 765: 192.168.64.1.4433 > 192.168.63.15.37187: UDP, length 723
READ FINISHED, scheduling write if need be
READ 723
17:36:25.661161 b8:83:03:6f:43:11 > b8:83:03:6f:43:49, ethertype IPv4 (0x0800), length 1482: 192.168.64.1.4433 > 192.168.63.15.37187: UDP, length 1440
READ FINISHED, scheduling write if need be
WRITEABLE
PREPARING NEXT PACKET
CALLBACK 9!
Connection to the server completed, almost ready.
Peer addr 140a8c0 (fam 2), Local addr 140a8c0 (fam 2) <---------------- the local address is actually not correct, should be  f40a8c0  (192.168.63.15)
WRITE 145 bytes, peer addr 140a8c0 (fam 0), local address 140a8c0 (fam 2) <------------------- here the peer address is not set, though the value is correct. The local address is set... but wrong!
Could not send message to AF_to=0, AF_from=2, ret=-1, err=89
READ 1440
READ FINISHED, scheduling write if need be
WRITEABLE
PREPARING NEXT PACKET
WRITE 55 bytes, peer addr 140a8c0 (fam 0), local address 140a8c0 (fam 2)
Could not send message to AF_to=0, AF_from=2, ret=-1, err=89
WRITEABLE
PREPARING NEXT PACKET
WRITE 55 bytes, peer addr 140a8c0 (fam 2), local address 140a8c0 (fam 2)
WRITEABLE
17:36:25.664906 b8:83:03:6f:43:49 > b8:83:03:6f:43:12, ethertype IPv4 (0x0800), length 97: 192.168.63.15.37187 > 192.168.64.1.4433: UDP, length 55
PREPARING NEXT PACKET
Wakeup in 1000 msec. Return was 0. Length 0
WRITEABLE
PREPARING NEXT PACKET
WRITE 147 bytes, peer addr 140a8c0 (fam 0), local address 140a8c0 (fam 2)
Could not send message to AF_to=0, AF_from=2, ret=-1, err=89
WRITEABLE
PREPARING NEXT PACKET
WRITE 55 bytes, peer addr 140a8c0 (fam 0), local address 140a8c0 (fam 2)
Could not send message to AF_to=0, AF_from=2, ret=-1, err=89
WRITEABLE
PREPARING NEXT PACKET
WRITE 55 bytes, peer addr 140a8c0 (fam 2), local address 140a8c0 (fam 2)
WRITEABLE
PREPARING NEXT PACKET
Wakeup in 1000 msec. Return was 0. Length 0
17:36:26.669463 b8:83:03:6f:43:49 > b8:83:03:6f:43:12, ethertype IPv4 (0x0800), length 97: 192.168.63.15.37187 > 192.168.64.1.4433: UDP, length 55
```

I'll try to force setting the local address :)

**Comment by huitema** [comment]
I am looking at the differences between your code in `quic.h` and the code in `sockloop.c`. I think I found something suspicious. The signature of `picoquic_recvmsg` is:
```
int picoquic_recvmsg(SOCKET_TYPE fd,
    struct sockaddr_storage* addr_from,
    struct sockaddr_storage* addr_dest,
    int* dest_if,
    unsigned char* received_ecn,
    uint8_t* buffer, int buffer_max)
```
But you are calling it as:
```
    recv_length = picoquic_recvmsg(c->fd, &local_addr,
                         &peer_addr, &if_index, &received_ecn,
                         (unsigned char*)&recv_buffer, recv_length);
```
The local and peer parameters are inverted. The second parameter of `picoquic_recvmsg` is called `addr_from`, which is meant to indicate the address **from which** the packet was sent, i.e., the source IP in the IP header. It will receive the address of the server. If you set the local address to that value, something bad probably happens.

You may also want to check the port number. The call to `picoquic_recvmsg` sets the IP address and port number for the parameter `addr_from`, but only the IP address for the parameter `addr_dest` -- the socket option returned by `recvmsg` only provides the source IP address. This is not an issue if you manage only one socket, but if you manage several you need to set the port number of the received `addr_dest` to the port number for the socket on which the packet arrive before calling `picoquic_incoming_packet`. The code in `sockloop.c` does that:
```

                /* Document incoming port */
                if (addr_to.ss_family == AF_INET6) {
                    ((struct sockaddr_in6*) & addr_to)->sin6_port = current_recv_port;
                }
                else if (addr_to.ss_family == AF_INET) {
                    ((struct sockaddr_in*) & addr_to)->sin_port = current_recv_port;
                }
                /* Submit the packet to the server */
                (void)picoquic_incoming_packet(quic, buffer,
                    (size_t)bytes_recv, (struct sockaddr*) & addr_from,
                    (struct sockaddr*) & addr_to, if_index_to, received_ecn,
                    current_time);
```

**Comment by tbarbette** [comment]
> The local and peer parameters are inverted. The second parameter of `picoquic_recvmsg` is called `addr_from`, which is meant to indicate the address **from which** the packet was sent, i.e., the source IP in the IP header. It will receive the address of the server. If you set the local address to that value, something bad probably happens.

Oh damn! That solved it! Thanks! I took some part of the loop as the select must be done in the core app, and I guess I messed up the from/to local/peer renaming... Thank you very much!

For the port, it seems to work for now. Performance will be important at some point, so doing this transformation for every packet may not be suitable.
