### ISSUE TITLE
How to know a FD can be closed?

### ISSUE THREAD

**Issue by tbarbette** [private-octopus/picoquic#1074]
Hi all,

I'd like to clean my file descriptor as fast as possible. However, in the callback event picoquic_connection_closed, it is too early as I observed some packets arriving on the file descriptor afterwards.
The question is specific for the client mode.

I found out that after calling picoquic_close() and exchanging a few packets with the server, after some time calling picoquic_prepare_packet() will return an error 1044 (I guess PICOQUIC_ERROR_INVALID_STREAM_ID). At that point the connection seems normally closed and I should be able to call close(fd). But the read before that probably lead to this state does not return anything specific. Also maybe some other event should trigger the clean?

In sockloop I see it's done at the end of the application, but it's not suitable in my case as I want to generate many requests (hence many fds).

Thanks!
Tom

**Comment by huitema** [comment]
The sample client closes the stream after the "fin" has been provided by the application. You can see the code in the implementation of the callback, in sample_client.c lines 281-290. If it receives a "connection close" event, the client callback marks the connection as disconnected and unlinks the callback function from the connection (lines 322-326). The code does not close the files at that specific point, since general cleanup will happen shortly after. Maybe it should, that would be more explicit.

Would that solve your issue, or do you need something else?

**Comment by tbarbette** [comment]
Yes that would be perfect, thanks! But you can't close the file at that specific point, right? Because there are some exchanges after the connection close event?

A slighlty related question : is it safe to re-use the same tuple to restart a new connection (with different connection id?) in your opinion? Will the server be messed up by that?

**Comment by huitema** [comment]
There are two levels of interactions between stack and application: per stream, and per connection. The per-stream operations are ordered: data is read in sequence, and is delivered in sequence. There is no further attempt to read stream data if the application has signaled the FIN bit, and there is no further delivery of stream data after delivering the FIN bit.

The sample code ensures that the callback function is not called any more after the connection close by calling:
```

            /* Remove the application callback */
            picoquic_set_callback(cnx, NULL, NULL);
```
This resets the callback function and callback context pointers to NULL for the connection, ensuring that the callback will never fire again for that connection.

**Comment by huitema** [comment]
As for reusing tuples, yes, that's supposed to work. As long as the connection ID is different, multiple connections can share the same IP addresses and ports.

**Comment by tbarbette** [comment]
> There are two levels of interactions between stack and application: per stream, and per connection. The per-stream operations are ordered: data is read in sequence, and is delivered in sequence. There is no further attempt to read stream data if the application has signaled the FIN bit, and there is no further delivery of stream data after delivering the FIN bit.
> 
> The sample code ensures that the callback function is not called any more after the connection close by calling:
> 
> ```
> 
>             /* Remove the application callback */
>             picoquic_set_callback(cnx, NULL, NULL);
> ```
> 
> This resets the callback function and callback context pointers to NULL for the connection, ensuring that the callback will never fire again for that connection.

I had that and removed it but In both case I still have packets exchanged for that connection after the last callback. Unless I did something wrong, of course. Eg if I remember correctly the server sent a last packet that I would not have receive if I closed the fd() in the connection_close callback. Isn't there something like the FIN2/last ACK in QUIC? I probably over-think it, I'll wait for your update. Thanks!

**Comment by huitema** [comment]
In the absence of packet losses, you should see the following:

1) Client receives a packet with the last bytes of the file and the FIN mark (stream frame in 1 RTT packets)
2) Client sends (prepare) a packet containing an ACK of the server packets and a Connection Close frame
3) Client receives ACK packets sent by the server before receiving the Connection Close frame
4) Client MAY repeat the Connection Close frame if it sees too many packets incoming from the server
5) Optionally, client receives Connection Close frame from the server and exits
6) If no Connection Close received, client exits after 3 RTT

This suppose that the client is doing a gracious close, which allows the server to know the file was well received, and to clean its own state quickly.

If the client may also just stop after step 1 before sending ACK and Close, the server will try retransmit the last unacked packets and eventually close. If the client stops after step 2, the next packets from the server will be ignored. Of course there are complications if packets are lost.

There is an issue with the "connection close" callback. In the current state, it can be sent multiple times: after step 2 in the previous diagram, and after 5 or 6. I see how that can be confusing. There are really two transitions: connection "closing" after step 2, which means "no more data can be sent or received", and "closed" after step 5 or 6. Should I fix that?

**Comment by tbarbette** [comment]
I modified the sample app to note the number of bytes received, the callback event I get and remove the de-registration of the callback, I get the following : 
```
Starting connection to 192.168.64.1, port 4433
Initial connection ID: f2f497c645c1c198
Opened stream 0 for file bin-8k
Waiting for packets.
Received callback 8
Received 1252 bytes
Received 774 bytes
Received callback 9
Connection to the server completed, almost ready.
Received 1440 bytes
Received 55 bytes
Received 55 bytes
Received callback 10
Connection to the server confirmed.
Received 55 bytes
Received 1440 bytes
Received callback 0
Received 1440 bytes
Received callback 0
Received 1440 bytes
Received callback 0
Received 1440 bytes
Received callback 0
Received 1440 bytes
Received callback 0
Received 1014 bytes
Received callback 1
Received callback 5
Connection closed.
bin-8k: complete, received 8000 bytes
Received callback 5
Connection closed.
```

As you stated, callback 5 is called twice. But in this case we could close the fd at the first call, as no packets is received after the call to 5. If indeed after the first "callback 5" we could receive a packet, then that event should be something else. It would be unclean to ignore packets from the server (especially that the client may generate an ICMP message).

However, I tried the same on the demo application and this shows my problem where I receive a single callback 5, then a packet:
```
Opening stream 24 to GET /file-123K
Received 55 bytes
Demo callback 1
Stream 24 ended after 0 bytes
All done, Closing the connection.
Demo callback 5 <------------------------ callback 5
Received a request to close the connection.
Received 31 bytes <----------------------- Received bytes after the callback 5?
The connection is closed! <--------------- Maybe I should focus on how this one is done?
Quic Bit was greased by the client.
Quic Bit was greased by the server.
ECN was received (ect0: 890, ect1: 0, ce: 0).
ECN was acknowledged (ect0: 264, ect1: 0, ce: 0).
Received 1235014 bytes in 0.048613 seconds, 203.240121 Mbps.
Client exit with code = 0
```

Sorry for the long delay but I had to revert my setup to try that.

**Comment by huitema** [comment]
The stack should not provide data after it has signaled that the connection is closed. I wonder what these data are that the demo client received. It smells like a bug, data incoming on a closed stream but still provided to the application.

The proposed fix is to create a callback "the connection is closing", so the sequence on your example would be:
```
...
Received 1014 bytes
Received callback 1
Received callback 14
Connection closing.
bin-8k: complete, received 8000 bytes
Received callback 5
Connection closed.
```
The processing of "closing" should be very much the same as the processing of "closed", but with a requirement to keep waiting for packets for a short while in order to get a gracious close.

Would that be clearer?

**Comment by huitema** [comment]
@tbarbette can you check whether PR #1082 would solve your issue? It is the simplest fix that I could think off: delay the "connection closed" callback until the connection is completely closed. The drawback is that there will be a small interval during which the connection is in a "closing" state, but the application does not know. It will find out only if it tries pushing more data, or opening a new stream, in which case the call will return an error.

I don't think the interval is a big issue. Even with the old code, the application could open a stream just before the connection closes, and find out that it won't be sent when the "connection closed" callback arrives. If the delay really is a problem, we will need to introduce a new "closing" callback, but applications will have to add code to handle it.

**Comment by tbarbette** [comment]
It seems fine to me for the second case. It seems clean to me but I'm a fairly new user so...

However I'm more worried about those 31bytes of the demo application.

**Comment by huitema** [comment]
For clarity, when you say "demo application", do you mean "picoquicdemo"? I would like to reproduce the issue, to understand where the 31 bytes that you mention come from. Or look at a trace if you have one.

**Comment by tbarbette** [comment]
Yes, picoquicdemo. Sorry the testbed is in use now and I did not record it.

**Comment by huitema** [comment]
@tbarbette Do we still need to work on this issue?

**Comment by tbarbette** [comment]
Yes, I guess the merged commit fixes it, thanks !
