### ISSUE TITLE
No packet header encryption

### ISSUE THREAD

**Issue by simonasmulevicius** [private-octopus/picoquic#1083]
Good morning, 

I am doing a research project about the QUIC offloading in hardware.
For this reason, I would like to be able to see packet numbers (in hardware).
However, I know that multiple implementations of QUIC usually encrypt packet headers.
Hence, I wonder if this implementation of QUIC has an API to turn off packet header encryption mechanism.

Kind regards, 
Simonas

**Comment by huitema** [comment]
There is no plan to do that. Picoquic follows the standard.

**Comment by huitema** [comment]
@simonasmulevicius My understanding of the state of the art is that if hardware offload is available, the QUIC implementations delegate both payload encryption and packet header protection to the hardware. You may want to look at the "msquic" implementation from Microsoft, which I believe already supports this kind of delegation.

If we get a standard API to perform this hardware offload, then Picoquic should support it.

**Comment by huitema** [comment]
Closing - no action.
