### ISSUE TITLE
Should be able to set or unset loss bit in picoquicdemo

### ISSUE THREAD

**Issue by IvanNardi** [private-octopus/picoquic#1086]
Hi
Is there any way to easily disable "loss-bit stuff" in picoquicdemo?
Sorry if I missed something obvious...
Thanks in advance

**Comment by huitema** [comment]
Not yet, no. The use or not of the loss bit is controlled by the transport parameter "enable_loss_bit". The application can set the value of transport parameters per QUIC context or per connection, but the demo program does not have a command line argument to set that value. It would be a good idea to create one, and pass it to the client and server. Not very hard to do.

The parameter has the following values:

0: do not enable loss bit.
1: the peer can send the loss bit, but this node will not.
2: ready to receive and send loss bit.

**Comment by IvanNardi** [comment]
Thanks for confirming my understanding!

**Comment by huitema** [comment]
You are welcome. I know I should rework the demo program to accept more parameters and enable more experimentation, but I will need some time to do that.

**Comment by huitema** [comment]
@IvanNardi you may want to take a look at PR #1096. I think that it solves your issue.
