### ISSUE TITLE
Sample client does not terminate

### ISSUE THREAD

**Issue by bortzmeyer** [private-octopus/picoquic#1093]
```
% ./picoquic_sample client localhost 4433 /tmp foobar 
Starting connection to localhost, port 4433                               
Initial connection ID: 7584d3e7713a538c
Opened stream 0 for file foobar
Waiting for packets.
Connection to the server completed, almost ready.
Connection to the server confirmed.
All done, closing the connection.
```

But, after that, the client does not stop and never returns.

This may be the root cause of #1092 (no exit, so no conversion to qlog).

**Comment by huitema** [comment]
@bortzmeyer Thanks for filing the issue. This is being fixed in PR #1094.

The issue appeared after PR #1082, which removed an "early callback" when a connection was almost closed -- but failed to add a proper callback on one of the closing paths.
