### ISSUE TITLE
Improper function name?

### ISSUE THREAD

**Issue by iriszero** [private-octopus/picoquic#1100]
Hi, I was reviewing the overall code and I came across this function:

```
/*
 * Processing of client encrypted packet.
 */
int picoquic_incoming_encrypted(
    picoquic_cnx_t* cnx,
    uint8_t* bytes,
    picoquic_packet_header* ph,
    struct sockaddr* addr_from,
    struct sockaddr* addr_to,
    int if_index_to,
    unsigned char received_ecn,
    uint64_t current_time);
```
However, it seems that, in my understanding, the packet should have been *decrypted* at this stage.
Could you confirm this? @huitema 

If so, I think it should be `picoquic_incoming_**encoded**()`.

I'm attaching a callgrind result of a sending-a-big-file scenario: [callgrind.out.zip](https://github.com/private-octopus/picoquic/files/5629337/callgrind.out.zip) It shows no encryption overhead beneath the concerned function.

In the profiling, `picotls` and `openssl` were built together with `picoquic`; all with `-Og -g` flag enabled.

**Comment by iriszero** [comment]
Correction: I'm not sure the profiling was done where `openssl` was built together. I will try it again first thing in the morning.

**Comment by huitema** [comment]
I agree that the choice of function name is misleading. It should be based on the packet type, like the other functions. And yes, the packets are passed to the function after decryption -- but the same is true for all the other incoming functions for initial, handshake or 0rtt. The proper name should be "incoming_1rtt".

**Comment by huitema** [comment]
PR #1101 should address the issue.

**Comment by iriszero** [comment]
On an unrelated note, may I ask what `pn` stuff do in the code?

It seems that `picoquic` performs separate encryption on it, which accounts for roughly 5% of CPU cycle on the server.
I'm referring to `picoquic_pn_encrypt` and other `_pn` functions, elements, and structures.

**Comment by huitema** [comment]
Packet number encryption. That's a function of header protection, see https://tools.ietf.org/html/draft-ietf-quic-tls-32#section-5.4.

5% of CPU, really? How much is encryption proper? I could fix that by moving to support the "fusion" code from picotls.

**Comment by iriszero** [comment]
Thank you for the reference.
I think I am no better capable of making that guess than you'd be.

Again, the attached profiling did not account for all syscalls. 
I can come up with more rigorous CPU profiling soon later.

**Comment by huitema** [comment]
Any suggestion for visualizing the callgrind output on Windows?

**Comment by iriszero** [comment]
Well, even in Linux, the GUI application (KCachegrind) seems to resolve the symbols at runtime. I'm having difficulty in visualizing the result from my remote machine as well. This is so, even my local machine is a Ubuntu-desktop of the same version of the remote. The culprits are library version and relative path stuff.

My plan is to get a tentative call graph with `CallGraph`, which you'd have in your brain vividly, and manually insert tracepoints before and after the target functions. I'd be happy to share the numbers here as soon as I get.
