### ISSUE TITLE
SEGV running picoquic_ct

### ISSUE THREAD

**Issue by IvanNardi** [private-octopus/picoquic#1145]
Running `./picoquic_ct -f 100` it is quite easy to get the following crash:

```
/home/ivan/svnrepos/picoquic/picoquic/tls_api.c:2385:59: runtime error: member access within null pointer of type 'struct ptls_aead_context_t'
AddressSanitizer:DEADLYSIGNAL
=================================================================
==13666==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x563adb7686ed bp 0x000000000000 sp 0x7fff1c1e5040 T0)
==13666==The signal is caused by a READ memory access.
==13666==Hint: address points to the zero page.
    #0 0x563adb7686ec in picoquic_aead_get_checksum_length /home/ivan/svnrepos/picoquic/picoquic/tls_api.c:2385
    #1 0x563adb71853d in picoquic_protect_packet /home/ivan/svnrepos/picoquic/picoquic/sender.c:610
    #2 0x563adb71fe20 in picoquic_finalize_and_protect_packet /home/ivan/svnrepos/picoquic/picoquic/sender.c:1083
    #3 0x563adb73d3ae in picoquic_prepare_packet_ready /home/ivan/svnrepos/picoquic/picoquic/sender.c:3742
    #4 0x563adb7448f7 in picoquic_prepare_packet_ex /home/ivan/svnrepos/picoquic/picoquic/sender.c:4198
    #5 0x563adb749f66 in picoquic_prepare_packet /home/ivan/svnrepos/picoquic/picoquic/sender.c:4293
    #6 0x563adb5a454f in stress_handle_packet_prepare /home/ivan/svnrepos/picoquic/picoquictest/stresstest.c:601
    #7 0x563adb5abaf5 in stress_loop_poll_context /home/ivan/svnrepos/picoquic/picoquictest/stresstest.c:808
    #8 0x563adb5abaf5 in stress_or_fuzz_test /home/ivan/svnrepos/picoquic/picoquictest/stresstest.c:1030
    #9 0x563adb5add88 in fuzz_test /home/ivan/svnrepos/picoquic/picoquictest/stresstest.c:1166
    #10 0x563adb54c684 in do_one_test /home/ivan/svnrepos/picoquic/picoquic_t/picoquic_t.c:297
    #11 0x563adb5499b7 in main /home/ivan/svnrepos/picoquic/picoquic_t/picoquic_t.c:532
    #12 0x7fd5b23050b2 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x270b2)
    #13 0x563adb54c4cd in _start (/home/ivan/svnrepos/picoquic/picoquic_ct+0x30e4cd)

```

It doesn't happen always (some fuzz logic is involved), but it should be easy to reproduce

**Comment by huitema** [comment]
Isn't fuzzing great?...

There are several issues here. Fixing that specific case, but also fixing the "leaks" test to yell if it detects "runtime error". The problem there is the fuzz test, which executes randomly and find different issues at each run. In theory the fuzz operates from a static random seed, but tiny changes in the code may change the timing of packets and the order of calls to the random number generator.

A bit like working on the memory leaks. We need to fix all the errors before we can turn on the automated test.

**Comment by huitema** [comment]
The stack is weird. 
```
    #0 0x563adb7686ec in picoquic_aead_get_checksum_length /home/ivan/svnrepos/picoquic/picoquic/tls_api.c:2385
    #1 0x563adb71853d in picoquic_protect_packet /home/ivan/svnrepos/picoquic/picoquic/sender.c:610
    #2 0x563adb71fe20 in picoquic_finalize_and_protect_packet /home/ivan/svnrepos/picoquic/picoquic/sender.c:1083
    #3 0x563adb73d3ae in picoquic_prepare_packet_ready /home/ivan/svnrepos/picoquic/picoquic/sender.c:3742
```
The function `picoquic_prepare_packet_ready` manages sending of packets after the handshake is complete. At that point, only 1-RTT packets will be sent. But line 1083 in `picoquic_finalize_and_protect_packet` corresponds to the protection of a 0-RTT packet! There is probably no encryption context available for that. I wonder how the code got there...

**Comment by huitema** [comment]
I understand what is happening. A zero RTT packet was fuzzed, and the frame type inside was changed from "stream data" to "crypto stream". The fuzzed packet was sent, and then copied for retransmission. When the retransmission timer ran out, the packet was resent, but because of the presence of crypto frame it was resent as 0-RTT... The good news is that this cannot happen in normal usage, it is effectively a fault injection in the code.

**Comment by huitema** [comment]
The offending code is legacy code. The latest QUIC spec do not allow transmission of crypto frames in 0-RTT packets. I need to clean that up!

**Comment by IvanNardi** [comment]
> There are several issues here. Fixing that specific case, but also fixing the "leaks" test to yell if it detects "runtime error".

You want an easy way to detect the runtime errors in the GitHub Action script: am I getting it right?

**Comment by huitema** [comment]
I am think of grepping for "runtime_error" in the "sanity.txt" output, counting the errors, and raising an issue if the count exceeds a legacy value. Or exceeds zero if we have fixed the legacy issues.

**Comment by huitema** [comment]
PR #1146 will fix this issue. I like that it merely removes old bogus code...

**Comment by IvanNardi** [comment]
> I am think of grepping for "runtime_error" in the "sanity.txt" output, counting the errors, and raising an issue if the count exceeds a legacy value. Or exceeds zero if we have fixed the legacy issues.

With #1148, it should be enough to check the program return value, as we already do for the leaks
