### ISSUE TITLE
Handling NEW_CONNECTION_ID frames that retire all connection IDs

### ISSUE THREAD

**Issue by WesleyRosenblum** [private-octopus/picoquic#1147]
While testing interoperability of the Picoquic client, we've encountered a few issues related to Picoquic's handling of [NEW_CONNECTION_ID frames](https://tools.ietf.org/html/draft-ietf-quic-transport-32#section-19.15).

The scenario that triggers these issues involves a peer that issues a NEW_CONNECTION_ID frame that requests to retire all previously issued connection IDs. This should be allowed by the following from [QUIC Transport §5.1.2](https://tools.ietf.org/html/draft-ietf-quic-transport-32#section-5.1.2):
> Upon receipt of an increased Retire Prior To field, the peer MUST stop using the corresponding connection IDs and retire them with RETIRE_CONNECTION_ID frames before adding the newly provided connection ID to the set of active connection IDs.  This ordering **allows an endpoint to replace all active connection IDs** without the possibility of a peer having no available connection IDs and without exceeding the limit the peer sets in the active_connection_id_limit transport parameter; see Section 18.2.

Let's say Picoquic has just completed a handshake with a peer. At this point, Picoquic has a single connection ID (with sequence ID 0) to communicate with the peer and the Retire Prior To value is 0.

Now, say the following NEW_CONNECTION_ID frame, which indicates the peer no longer wants to use the connection ID used during the handshake, is received by Picoquic:

```
NEW_CONNECTION_ID Frame {
     Type = 0x18,
     Sequence Number = 1,
     Retire Prior To = 1,
     Length (8) = 4,
     Connection ID = fb 2c 60 93,
     Stateless Reset Token = 05 7a cf aa aa a3 42 d2 39 71 c8 aa b2 6c 6f 08,
   }
```

When Picoquic [processes](https://github.com/private-octopus/picoquic/blob/d34383069230f8eca46b2c36ad79b2dc9f98bb34/picoquic/frames.c#L332) this frame, since the Retire Prior To field has increased from 0 to 1, the connection ID with sequence number 0 [should be retired](https://github.com/private-octopus/picoquic/blob/d34383069230f8eca46b2c36ad79b2dc9f98bb34/picoquic/frames.c#L362-L365) and the new connection ID should be used going forward.

Issue 1: No RETIRE_CONNECTION_ID frame will be sent for this connection ID, because [there is a path reference to it](https://github.com/private-octopus/picoquic/blob/8befec69f96059c05709c197a23c45de15fed669/picoquic/quicctx.c#L1891). 

Issue 2: Further down in [`picoquic_remove_not_before_cid`](https://github.com/private-octopus/picoquic/blob/8befec69f96059c05709c197a23c45de15fed669/picoquic/quicctx.c#L1883), `picoquic_renew_connection_id` is called, which calls [`picoquic_renew_path_connection_id`](https://github.com/private-octopus/picoquic/blob/8befec69f96059c05709c197a23c45de15fed669/picoquic/quicctx.c#L1933). This attempts to retrieve an unused stashed connection ID by calling `picoquic_obtain_stashed_cnxid`, but since the New Connection ID has not been stashed yet, it returns `NULL` and a `PICOQUIC_ERROR_CNXID_NOT_AVAILABLE` [is returned](https://github.com/private-octopus/picoquic/blob/8befec69f96059c05709c197a23c45de15fed669/picoquic/quicctx.c#L1944-L1948).

Issue 3: When a NEW_CONNECTION_ID frame is received while connection migration is disabled, a PICOQUIC_ERROR_MIGRATION_DISABLED error [will be returned](https://github.com/private-octopus/picoquic/blob/8befec69f96059c05709c197a23c45de15fed669/picoquic/quicctx.c#L1938-L1942). A peer should be able to issue NEW_CONNECTION_IDs without actually performing or allowing connection migrations. This may be done, for example, because the peer may only wish to use a given connection ID for a limited amount of time.

Thanks for considering this issue and let me know if you need any further information!

**Comment by huitema** [comment]
Thanks for the report. Let's get this fixed.

**Comment by huitema** [comment]
@WesleyRosenblum I am trying to reproduce these issues. First step is to add a couple of tests in the test suite. I think I need two of those.

First test would address your first issue, "No RETIRE_CONNECTION_ID frame will be sent for this connection ID". I think that the test should work as this:

1) Establish a test connection.
2) Force the server to send a single NEW CONNECTION ID frame, that retire all previously issued CID.
3) Verify that within a few RTT the client sends and the server receives RETIRE CONNECTION ID frames for CID #0.

I think that this test also covers your second issue. The root cause of the first issue is probably that the new connection ID should be stashed immediately after receiving it, and that the call to `picoquic_remove_not_before_cid` should happen after `picoquic_enqueue_cnxid_stash`, not before.

The second test should address the other issue, receiving a NEW_CONNECTION_ID frame is received while connection migration is disabled. I think that this can be tested with a variant of the test above:

1) Establish a test connection, with the server setting the parameter `disable_active_migration`.
2) Force the server to send a single NEW CONNECTION ID frame, that retire all previously issued CID.
3) Verify that within a few RTT the client sends and the server receives RETIRE CONNECTION ID frames for CID #0.
4) Check that the connection continues as expected.

Will that address your issues?

**Comment by WesleyRosenblum** [comment]
Sounds great! Just make sure when stashing the new connection ID that you don't count the newly retired connection ID against the active_connection_id_limit. Maybe you could have a test for that as well, have the server send as many new connection IDs as your active_connection_id_limit while retiring existing ones.

**Comment by huitema** [comment]
@WesleyRosenblum PR #1150 should address your issues. However, I think we need some work on the API side. I added an "internal" API for the tests, but I need to better understand the use case. If the point is to manage a long running server behind a load balancer, we need to understand who will call that API. Do we assume that the server is part of a larger application that comes with its own maintenance system? The internal API `picoquic_set_local_cnxid_retire_before` is defined per connection, using connection ID sequence numbers. Is that the right level?

Picoquic has support for the CID formats defined in [the load balancing draft](https://github.com/quicwg/load-balancers). This is still rough, and we might want a bit of work on that too. For example, the LB draft defines way to specify epochs and associated flags. I could see a management operation "rotating" the epoch. The API `picoquic_set_local_cnxid_retire_before` could be used, but it is convoluted. It requires enumerating all connections managed by the server, and for each connection either renew all connection ID, or maybe inspect all currently allocated connection ID to find out whether some were allocated with the old format, and then invalidate those ones.

There should be a better way. Maybe a server level API, per QUIC context, that somehow interfaces with the CID plug-in function.

**Comment by WesleyRosenblum** [comment]
Thanks for the PR! I will take a look today

**Comment by WesleyRosenblum** [comment]
Thanks again for the PR, I just had a couple questions on it related to connection migration.

Regarding the use case in question, generally I think it's beneficial if a server allows whoever is using it specify how long the connection IDs are allowed to remain in use before they are expired and replaced. I haven't looked closely at how Picoquic generates IDs, but depending on how that works a separate API or configuration could be appropriate.

**Comment by huitema** [comment]
I like the idea of setting an upper time limit for the validity of CID in the QUIC server context, and let every connection inherit it. It is simple enough, and in the general spirit of the picoquic design.

By default, picoquic creates CID as random binary strings of length N -- N can be configured to any value from 0 to the max 26 allowed by the protocol. The application can provide a callback function, in which case the CID values will be set by that function. The distribution includes a function implementing the spec in the load balancing draft, but that implementation assumes that all parameters are known when the server starts. If people start using it, we will want a management API to update the parameters over time.

I was worried about cancelling all CID on a set date -- that would create a thundering herd of all dormant connections waking up at the same time to send fresh CID to their peers. But if we have a validity time per CID, that mitigates the issue somewhat.
