### ISSUE TITLE
Warning

### ISSUE THREAD

**Issue by IvanNardi** [private-octopus/picoquic#1154]
I got the following warning:
```
/home/ivan/svnrepos/picoquic/picoquic/frames.c:2098:33: error: explicitly assigning value of variable of type 'int' to itself [-Werror,-Wself-assign]
                is_path_x_valid = is_path_x_valid;
                ~~~~~~~~~~~~~~~ ^ ~~~~~~~~~~~~~~~
```
The code is clearly wrong (probably some cut-and-paste error); no idea on how to fix it, though...

**Comment by huitema** [comment]
Oops. This is a silly no-op instruction that I added during debugging, in order to place a checkpoint when the tested condition was true.

**Comment by huitema** [comment]
Fixing that in PR #1156
