### ISSUE TITLE
Insufficient TPS number

### ISSUE THREAD

**Issue by huitema** [private-octopus/picoquic#1188]
From the msquic performance report:

↓Client →Server | msquic | picoquic | lsquic | ngtcp2 | quinn
-- | -- | -- | -- | -- | --
msquic | 547K RPS | 15K RPS | X | X |  
picoquic | X | X | X | X |  
lsquic | X | X | X | X |  
quinn |   |   |   |   |  

There are many plausible explanations for the low value of the picoquic number. One is that 15K is actually pretty good, so we did not try to better that. The other is that there may be some inadequate tuning, e.g. the number of streams that a connection may open. Is there an easy fix?

**Comment by nibanks** [comment]
I believe one big problem was not scaling to use the full set of CPUs available on the machine. But as you said, using just a single core might be all you're interested in testing.

**Comment by huitema** [comment]
@nibanks  Yes, the deployments that I hear off are happy with the process using a single core, and then using load balancing between multiple processes. But I am concerned that even 15K RPS per core is a bit low, and I want to investigate what the issue is. How many cores was msquic using in your test? 

I have a problem for my tests on WIndows. Visual Studio has a nice feature to breakdown CPU usage by function, down to the line of code. That is very handy for these perf investigations. However, the feature has stopped working on recent builds. From what I see on the web, similar issues in the past were due to bugs in some drivers (CPU driver?) that stopped the ETW signals listened to by VS. I don't know whether you have heard about such issues?

**Comment by nibanks** [comment]
Sorry, but I haven't heard anything related the ETW signals.

Our perf tests are run on 40 core / 80 thread machines. Right now, it looks like the client consumes all the CPU resources, where the server uses less than half (client on left, server on right):

![image](https://user-images.githubusercontent.com/20663557/113889444-19397e00-9778-11eb-83de-856c96e99fdd.png)

Dividing our ~1 million RPS by 80 cores does give us ~12.5K RPS per core, which is inline with (a bit less) what you have. Though, I still would recommend doing some testing at scale to make sure things are parallelized evenly with your load balancing model.

FYI @thadhouse

**Comment by nibanks** [comment]
BTW, that test was with 0 byte "requests" and 4096 byte "responses". If I up things to 8192 byte responses, RPS drops by ~30%, but we're network limited (50 Gbps NICs)

![image](https://user-images.githubusercontent.com/20663557/113890261-d7f59e00-9778-11eb-8697-0c759599b8c1.png)

**Comment by huitema** [comment]
Closing this. The 15K RPS number with one core would extrapolate to 600K RPS with the 40 cores used in the MSQUIC tests, which means the performance are more or less at parity.
