### ISSUE TITLE
Remove unused memory from context after handshake completes

### ISSUE THREAD

**Issue by huitema** [private-octopus/picoquic#1189]
From measurements of  `cnx_stress`:  for 1000 connections, I see client+server = 50MB. For 10,000, I see 457MB. The limiting factor is the time it takes to establish the connections -- all these public key operations. For 50,000 connections, I see over 2GB. 

May not be a huge priority, but it would be good to understand why picoquic allocates almost 25K per connection!

**Comment by victorstewart** [comment]
can you point me in the direction of the various structures and buffers maintained per and for connections so i can begin my wild goose chase?

**Comment by huitema** [comment]
How about this snaphot from the Visual Studio debugger. This is the delta between the memory allocation when the simulation is setup (about 2MB) and when all required 10,000 connections have been established.
![image](https://user-images.githubusercontent.com/7464128/112774981-46579500-8ff0-11eb-8838-31ba600272bb.png)

**Comment by huitema** [comment]
Looking into the void*. This is of course a mishmash of stuff, but something stands out. The implementation of AES-GCM that comes with picotls allocates some working memory for each "aes fusion" context. There are two such instances per connection context (encode and decode), and we have 20,000 connection contexts, 10,000 client and 10,000 servers. Total: 135MB out of the 150MB of "void".

![image](https://user-images.githubusercontent.com/7464128/112775208-0a70ff80-8ff1-11eb-9df9-68f9ecdbab67.png)

**Comment by huitema** [comment]
The next big item is the TLS context created for each connection, 4,976 bytes. With 20,000 contexts, that's 99MB.
![image](https://user-images.githubusercontent.com/7464128/112775625-48baee80-8ff2-11eb-90b9-d4badcc065bf.png)

**Comment by victorstewart** [comment]
amazing! seems like we have it all here.

first thoughts, dimitri mentioned how they throw away the TLS context after the connection is established... can we do that too?

**Comment by victorstewart** [comment]
> Looking into the void*. This is of course a mishmash of stuff, but something stands out. The implementation of AES-GCM that comes with picotls allocates some working memory for each "aes fusion" context. There are two such instances per connection context (encode and decode), and we have 20,000 connection contexts, 10,000 client and 10,000 servers. Total: 135MB out of the 150MB of "void".
> 
> ![image](https://user-images.githubusercontent.com/7464128/112775208-0a70ff80-8ff1-11eb-9df9-68f9ecdbab67.png)

@kazuho is it practically possible to use a buffer pool instead of allocating 2 static buffer per connection? how complicated of a change would that be?

**Comment by victorstewart** [comment]
counting down to `ptls_aead_context_t` at 192 bytes per connection, we're at 18,847... so 20K per connection looks about the right number

**Comment by huitema** [comment]
The table below gives a breakout of the allocations that I understand. When seeing fractional counts, these ae allocation on the server side but not on the client side.


What | Type | size | n/c | Per C | Nb C | Total
-- | -- | -- | -- | -- | -- | --
AES Fusion | Void* | 3,376 | 2 | 6752 | 20000 | 135040000
TLS context | st_picoquic_tls_ctx_t | 4,976 | 1 | 4976 | 20000 | 99520000
Connection context | st_picoquic_cnx_t | 3176 | 1 | 3176 | 20000 | 63520000
Path context | st_picoquic_path_t | 920 | 1 | 920 | 20000 | 18400000
Header encryption | st_ptls_cipher_context | 320 | 2 | 640 | 20000 | 12800000
Remote CNXID | st_picoquic_remote_cnxid_t | 184 | 3 | 552 | 20000 | 11040000
Local CNXID | st_picoquic_local_cnxid_t | 160 | 3 | 480 | 20000 | 9600000
Packet encryption | ptls_aead_context_t | 96 | 2 | 192 | 20000 | 3840000
CC state (new reno) | st_picoquic_reno_state_t | 176 | 1 | 176 | 20000 | 3520000
CNX Reset (hash) | st_picoquic_net_secret_key | 152 | 1 | 152 | 20000 | 3040000
Local CNXID (hash) | st_picoquic_cnxid_key_t | 48 | 3 | 144 | 20000 | 2880000
Hash item (hash tables) | _picohash_item | 24 | 4.5 | 108 | 20000 | 2160000
Net+ICID hash entry | st_picoquic_net_icid_key_t | 160 | 0.5 | 80 | 20000 | 1600000
Stress context (test) | st_cnx_stress_callback_ctx_t | 48 | 1 | 48 | 20000 | 960000
Various | strings | 12 | 1.5 | 18 | 20000 | 369960
Various | pointers | 8 | 1 | 8 | 20000 | 159952
Sum |   |   |   | 18422.5 |   | 368449912

It does not account for everything. There are about 15MB of void* allocations that are not traced to specific programs. There are also 16 MB of packet buffers, i.e. about 19K packets managed as pools and shared by all connections.

**Comment by huitema** [comment]
@victorstewart as you wrote above, there seems to be some first things that come to mind:

1) Convince @kazuho to use a more efficient memory allocation for the "fusion" implementation, or if not that use either a different implementation of AES, or maybe ChaCha20. The Openssl implementation of AES is a bit slower that Fusion, but might use fewer resource. ChaCha20 is definitely much slower than AES using X64 instructions, but might use fewer resource.
2) Free the TLS context when all the TLS work is done, i.e. the connection is established and the TLS resume ticket has been obtained. We just need to verify that this is compatible with key rotation. I believe so, but better check.
3) Possibly, trim the size of the connection context
4) Check the usage of connection ID. Maybe allow application to control how many are allocated.

The good news is that with a few simple fixes we should be able to gain at least a factor 2.

**Comment by huitema** [comment]
There are a couple items in the connection context that could be freed after connection establishment: the packet contexts and ack context associated with Initial and Handshake packets for example. Similarly, there are packet contexts and ack contexts associated with local and remote CNXID, but only used when configuring multipath connections. They could be replaced by pointers.

**Comment by victorstewart** [comment]
it seems like these changes could yield nearing a 70% reduction in memory per connection. that's a huge amount of memory.

that reduction in sprawl might improve performance nominally too, in a many connection environment.

feel free to assign me any of these things we've discussed as tasks to accomplish.

**Comment by huitema** [comment]
@victorstewart why don't you take a shot at exploring alternatives to AES fusion? The table of AES algorithms and providers is in tls_api.c, and there is also a per connection API to chose a particular encryption algorithm if we want to try ChaCha20. 

We cannot just free the TLS context when the connection transitions to the "ready" state, because that would risk missing the "post connection" message that carries session resume tokens and enables 0-RTT. Well, we could, but that would be a trade off. Instead, we want to either free after the session resume token has been received, or after the TLS server indicates that all is clear. I will open an issue in picotls to get that.

**Comment by victorstewart** [comment]
well i'd like the best of both worlds, maximal throughput and minimal memory footprint. haha. so first thing i'll do is discuss with @kazuho when he's around on what it would take to not allocate those buffers per connection, and see about doing that work myself. if that proves to be unrealistic for whatever reason (though i don't see why it would) i'll explore if there are any other options worth whatever trade off they offer for memory reduction.

we could add a transport parameter that disables 0-RTT and thus throw it away when the handshake completes as well? Or exfiltrate the struct containing the context for the session resumption tokens from the larger tls context.

**Comment by huitema** [comment]
Thinking about the TLS issue some more. I opened an issue in picotls (https://github.com/h2o/picotls/issues/354), but if we don't get an API I believe we can manufacture one. Picotls uses callbacks to ask an application to encrypt or decrypt a ticket -- see `picoquic_server_encrypt_ticket_call_back` and `picoquic_client_save_ticket_call_back`. These callbacks are executed during a call to from the app to picotls -- see calls to `ptls_handle_message` in tls_api.c. The callbacks could set a flag in the connection context, "session tickets have been processed". That flag can then be checked either during the ready transition, or after the ready transition when checking the result of `ptls_handle_message`. And at that point, the TLS context could be freed.

**Comment by victorstewart** [comment]
now having a blueprint of the structures and memory requirements per connection, we could also consider at a future date some kind of pool and preallocate 1000 or more at a time. not sure it's worth the effort or complication, just an idea, but would definitely increase handshakes per second in an artificial benchmark or aid latency in moments of connection establishment surge.

**Comment by kazuho** [comment]
> Convince @kazuho to use a more efficient memory allocation for the "fusion" implementation, or if not that use either a different implementation of AES, or maybe ChaCha20. The Openssl implementation of AES is a bit slower that Fusion, but might use fewer resource. ChaCha20 is definitely much slower than AES using X64 instructions, but might use fewer resource.

Re fusion, most of the memory pressure comes from precalculation of GHASH. Fusion uses aggregate reduction as proposed in https://crypto.stanford.edu/RealWorldCrypto/slides/gueron.pdf p.22 to the extreme, by precalculating the values for entire MTU. That's why it needs ~ 2*MTU bytes of state.

I am personally fine with fusion using 4x MTU bytes per connection (i.e., 2xMTU for ingress and egress), as typically the send buffer and the receive buffer of each connection is expected be much bigger than that.

That said, IIRC OpenSSL precomputes for 6 blocks (96 bytes), so the amount of state would be like 1/10 of fusion. So that'd be a reasonable choice if you want to trade performance for memory.

> Free the TLS context when all the TLS work is done, i.e. the connection is established and the TLS resume ticket has been obtained. We just need to verify that this is compatible with key rotation. I believe so, but better check.

Servers can send TLS resumption tickets at any given moment, therefore you cannot throw away TLS state without taking risk.

Also, I'm not convinced that picotls is to blame here. I think `ptls_t` consumes only ~512 bytes. I believe `st_picoquic_tls_ctx_t` consuming 4976 bytes is a picoquic structure?

**Comment by huitema** [comment]
@kazuho you are right, there may well be an issue with the picoquic structure st_picoquic_tls_ctx_t. I will take a look at trimming that. As for the choice between fusion and openssl AES, it is indeed a trade off between performance and memory. It could could be managed with a compile flag or an execution time flag

**Comment by huitema** [comment]
@kazuho I am looking at the size of st_picoquic_tls_ctx_t. It is due to two big buffers that are automatically allocated and kept there for encoding or decoding the "transport parameters" extension. I can easily get rid of the decoding buffer, and should have done that a long time ago. But I need some more information for the encoding buffer. The way it works today is:

1) Picoquic allocates a large buffer and keeps it in the TLS context
2) Picoquic formats the transport parameters in the buffer, and documents the buffer in `handshake_properties.additional_extensions`
3) Picoquic calls "ptls_handle_message"

Is it OK to just free the "additional extensions" memory after "handle message" returns?

**Comment by huitema** [comment]
First step, trimming the size of `st_picoquic_tls_ctx_t` from 4976 to 888 bytes. Gains 4K per connection, no change in functionality. see PR #1190.

![image](https://user-images.githubusercontent.com/7464128/112897578-a869d600-9094-11eb-9a3e-bd6ef8046305.png)

**Comment by huitema** [comment]
A bit more work, and the picoquic_tls_ctx_t is down to 392 bytes. At that point, other things are higher priority:


What | Type | size | n/c | Per C | Nb C | Total
-- | -- | -- | -- | -- | -- | --
AES Fusion | Void* | 3,376 | 2 | 6752 | 20000 | 1.35E+08
Connection context | st_picoquic_cnx_t | 3176 | 1 | 3176 | 20000 | 63520000
Path context | st_picoquic_path_t | 920 | 1 | 920 | 20000 | 18400000
Header encryption | st_ptls_cipher_context | 320 | 2 | 640 | 20000 | 12800000
Remote CNXID | st_picoquic_remote_cnxid_t | 184 | 3 | 552 | 20000 | 11040000
Local CNXID | st_picoquic_local_cnxid_t | 160 | 3 | 480 | 20000 | 9600000
TLS context | st_picoquic_tls_ctx_t | 392 | 1 | 392 | 20000 | 7840000
Packet encryption | ptls_aead_context_t | 96 | 2 | 192 | 20000 | 3840000
CC state (new reno) | st_picoquic_reno_state_t | 176 | 1 | 176 | 20000 | 3520000
CNX Reset (hash) | st_picoquic_net_secret_key | 152 | 1 | 152 | 20000 | 3040000
Local CNXID (hash) | st_picoquic_cnxid_key_t | 48 | 3 | 144 | 20000 | 2880000
Hash item (hash tables) | _picohash_item | 24 | 4.5 | 108 | 20000 | 2160000
Net+ICID hash entry | st_picoquic_net_icid_key_t | 160 | 0.5 | 80 | 20000 | 1600000
Stress context (test) | st_cnx_stress_callback_ctx_t | 48 | 1 | 48 | 20000 | 960000
Various | strings | 12 | 1.5 | 18 | 20000 | 369960
Various | pointers | 8 | 1 | 8 | 20000 | 159952
Sum |   |   |   | 13838.5 |   | 2.77E+08

**Comment by victorstewart** [comment]
spectacular!

**Comment by huitema** [comment]
Looking at the code, it is very simple to not pick fusion and get openssl instead. I will add a flag "prefer low memory" in the engine's context, use that flag when selecting the ciphersuite, and test using the flag in the "cnx_stress" test. Should be done tonight. After that, I may look at the connection context, try to find out what causes it to be so big.

**Comment by huitema** [comment]
PR #1191 introduces a "low memory" option. When set on a QUIC context, connections in that context will use the openSSL version of AES, instead of the fusion code. This reduces the memory per context a lot, as shown in the following table:


What | Type | size | n/c | Per C | Nb C | Total
-- | -- | -- | -- | -- | -- | --
Connection context | st_picoquic_cnx_t | 3176 | 1 | 3176 | 20000 | 63520000
Path context | st_picoquic_path_t | 920 | 1 | 920 | 20000 | 18400000
Remote CNXID | st_picoquic_remote_cnxid_t | 184 | 3 | 552 | 20000 | 11040000
TLS Context (picotls) | (void *)ptls_t | 512 | 1 | 512 | 20000 | 10240000
Local CNXID | st_picoquic_local_cnxid_t | 160 | 3 | 480 | 20000 | 9600000
TLS context (picoquic) | st_picoquic_tls_ctx_t | 392 | 1 | 392 | 20000 | 7840000
Key schedule (picotls) | (void *)ptls_key_schedule_t | 120 | 2 | 240 | 20000 | 4800000
Packet encryption | ptls_aead_context_t | 88 | 2 | 176 | 20000 | 3520000
CC state (new reno) | st_picoquic_reno_state_t | 176 | 1 | 176 | 20000 | 3520000
CNX Reset (hash) | st_picoquic_net_secret_key | 152 | 1 | 152 | 20000 | 3040000
Local CNXID (hash) | st_picoquic_cnxid_key_t | 48 | 3 | 144 | 20000 | 2880000
SHA 256 hash (picotls) | (void *)? | 136 | 1 | 136 | 20000 | 2720000
Hash item (hash tables) | _picohash_item | 24 | 4.5 | 108 | 20000 | 2160000
Header encryption | st_ptls_cipher_context | 40 | 2 | 80 | 20000 | 1600000
Net+ICID hash entry | st_picoquic_net_icid_key_t | 160 | 0.5 | 80 | 20000 | 1600000
Stress context (test) | st_cnx_stress_callback_ctx_t | 48 | 1 | 48 | 20000 | 960000
Various | strings | 12 | 1.5 | 18 | 20000 | 369960
Various | pointers | 8 | 1 | 8 | 20000 | 159952
Sum |   |   |   | 7398.496 |   | 147969912

**Comment by huitema** [comment]
There are probably other potential sources of gain. The connection context looks rather large, and contains data for the Initial, Handshake and 0RTT contexts that are not used after the handshake. It would probably be possible to save 1KB there without too much effort. It should also be possible to gain some space in the local connection ID and remote connection ID structures, maybe another 512B to 1K. After that, it would be a matter of questioning each statistical counter, are they really useful, and maybe some state variables, are they redundant? But going from 19K to 7.5K looks like a good first step.

**Comment by huitema** [comment]
I just repeated the connection stress test establishing 50,000 connections -- which indeed means 100,000 connections total. The process size grew to 1,016 MB, which would be 10KB per connection. In addition to the table above, this probably includes memory for packets. The whole setup phase took 278 seconds, which means 5.56 milliseconds per connection.

**Comment by kazuho** [comment]
@huitema Just curious, but how much memory did OpenSSL consume for retaining AES-GCM context? I ask this because it seems to be missing in the table right above.

**Comment by huitema** [comment]
I am curious about that too. I see the context created as ptls_aead_context_t, but I do not see the openssl objects. This might be a limitation of the Visual Studio tools. That's why I did a big run and looked at the process size. Based on that, we have about 2.5KB of unexplained overhead by process. Of that, I can believe that 1.5KB is packet data -- one packet per connection. That would leave 1KB for managing 2 contexts with openSSL. Does that look plausible?

**Comment by kazuho** [comment]
Thank you. That sounds plausible indeed.

**Comment by huitema** [comment]
@victorstewart We are down to about 10KB per connection. Is this low enough, or do we still need to work on this?

**Comment by victorstewart** [comment]
i'm aiming for about 750,000 connections per machine now, so with the low memory option currently looking at ~5GB of memory. that fits within my memory budget.

that said RE previous comments below...

> The connection context looks rather large, and contains data for the Initial, Handshake and 0RTT contexts that are not used after the handshake. It would probably be possible to save 1KB there without too much effort. It should also be possible to gain some space in the local connection ID and remote connection ID structures, maybe another 512B to 1K. 

if it's not too much trouble the extra 1-2KB reduction (20-30%) would be fantastic and very welcomed. bit more breathing room, and can't hurt cache residency for performance. but even without this is a home run.
