### ISSUE TITLE
Long transmission with congestion test takes twice longer than expected

### ISSUE THREAD

**Issue by huitema** [private-octopus/picoquic#119]
The long transmission test simulates sending 1MB over 10 Mbps list, with low latency and some queuing. The current test executes in a simulated time of 1.9 seconds. If using the link at full capacity, the transmission would last 800 milliseconds. Some overhead is expected, but not 125%!

**Comment by huitema** [comment]
Lars observed that with a link latency of 10ms, the RTT is 20 ms, and the test links should be configured with 20ms of buffer, not 10ms.

**Comment by huitema** [comment]
Matching the queue size to the BDP did fix the problem -- the test execute in the same time as other unconstrained tests.

**Comment by bkchr** [comment]
So the bug was in the test and not in the implementation of picoquic?

**Comment by huitema** [comment]
Kinda. Picoquic currently comes with the standard "New Reno" congestion control.That algorithm requires that intermediate nodes maintain at least one bandwidth*delay product of buffers. That correspond to 20ms of congestion, so upping the buffer limit from 10 ms to 20 ms solve the problem.

The limiting factor is new reno. With something more modern we could go father!

**Comment by huitema** [comment]
Implementing Google's BBR would help...
