### ISSUE TITLE
BBR Performance issue in low latency asymmetric links

### ISSUE THREAD

**Issue by huitema** [private-octopus/picoquic#1213]
After tests performed at MIT LL, the following issue was detected:

With forward link to be 10Mbps and varying the reverse link from 100kbps, 200kbps, 300kbps, 400 kbps, the server sends client 10MB over forward link while client sends over 8 bytes (minimum bytes). Therefore the reverse link mainly should be ACK packet. But the throughput is around 1.9mbps under 100kbps, around 4 or 5mbps over 200/300kbps and finally reaches to 9mbps with 400kbps on the reverse link. Please see attached chart based on the qlog collected on 100kbps as the reverse link. It looks like before 400kbps, the reverse link is saturated with ACK packet.

**Comment by huitema** [comment]
Graphs of QLOG for the issue:
![231aad8b1b3166c8-server-0-cwnd](https://user-images.githubusercontent.com/7464128/123463657-a2ef2f80-d5a0-11eb-853b-36e3ea639535.png)
![231aad8b1b3166c8-server-0-send-rate](https://user-images.githubusercontent.com/7464128/123463663-a4205c80-d5a0-11eb-8ffd-174dad933cdb.png)
![231aad8b1b3166c8-client-0-cwnd](https://user-images.githubusercontent.com/7464128/123463664-a4b8f300-d5a0-11eb-9d8d-34d9036e678f.png)
![231aad8b1b3166c8-client-0-ack-send-rate](https://user-images.githubusercontent.com/7464128/123463666-a4b8f300-d5a0-11eb-8f87-488786d46fdd.png)

**Comment by ferrieux** [comment]
Could you please attach the pcap ? Assuming the spin bit is enabled, one can plot RTT and BIF, and maybe see things not obvious from the CWND.

**Comment by huitema** [comment]
I do not have the PCAP, but I have a repro. I added a test simulating 10Mbps downlink, 100kbps uplink, short latency, see PR #1214. The key to the repro was to set up a large buffering limit on the ACK path. The test produces a binary log, compressed version attached here:
[bbr_asym100_20210626.zip](https://github.com/private-octopus/picoquic/files/6720571/bbr_asym100_20210626.zip)
Some debugging to do!

**Comment by ferrieux** [comment]
Thanks. Clearly BBR tries the usual probes and sees no gain, as though a system bottleneck was in the way:

Temporal view:

  * in the long initial phase of steady 15kB BIF, the RTT ominously climbs by steps: 36...40...44ms
  * the detailed metrics when probing down and up are better seen in a bidimensional BIF-RTT view below


![temporal](https://user-images.githubusercontent.com/614725/123526447-41ca7780-d6d8-11eb-8c3b-57853010a636.png)


BIF-RTT view:

  * in red the first 10 seconds just described, steady 15kB bytes but RTT increasing
  * in green the probing-down: BBR drains the queues and wait for the RTT to drop accordingly
  * in blue the up-probing: BBR speeds up and sees the RTT go up again
  * in all cases, note how the steady state lands on the purple line of 3.33Mbps
  * the conclusion from BBR's perspective is that the bottleneck is at 3.33Mbps. No bug.
  * come to think of it, the ACK rate is 240pps. With datagrams of 55 bytes (according to qlog... does it include Ether+IP+UDP?), this means ... 105kbps, the uplink bottlneck :)
   
 ![rttbif](https://user-images.githubusercontent.com/614725/123526861-e77ee600-d6da-11eb-8dbd-55d0c1eae45b.png)

**Comment by huitema** [comment]
The high level issue is that Picoquic fails to saturate the 10 Mbps link. This is largely due to "too high ACK ratio". I am looking at that and wondering how Picoquic could have automatically decreased the ACK ratio. In the test, the server is setting the ACK rate to something like RTT/8, somewhat blindly. The server should notice that the RTT is much too high, 4 or 5 times RTT min, which indicates that something is very wrong. In fact, when using BBR, an RTT larger than 2*RTT_MIN is wrong. The server could also notice that ACK are dribbling in at a low rate, much lower than minRTT/8. So maybe there is a way to design a test and drive a better policy.

**Comment by ferrieux** [comment]
Oh, so we're simply looking at a missing normative feature (not restricted to PicoQuic), the detection of a reverse-path bottleneck is just not considered in the RFC ?
If so, the timing is a bit unfortunate post v1.0 ;)

Now you're mentioning the *server* "setting" or "noticing". By "server", here specifically you mean... the *receiver*, right ?
Or is there really  a way (normative or not) for the *sender* to remotely control the ACK ratio of the receiver ?

**Comment by huitema** [comment]
I am not looking at a "normative" feature -- implementations can decide how and when to send ACK. The recovery RFC provides a basic strategy, but it is well understood that implementations are free to innovate. At their own risk. Of course, if we find something good and it works well, we will publish it and it might become part of the next version.

In that test, the server usd the "delayed ack" [extension](https://www.ietf.org/archive/id/draft-iyengar-quic-delayed-ack-02.txt), which allows for controlling the rate and spacing of ACKs by the receiver.

**Comment by ferrieux** [comment]
Ah, OK seeing the ack_freq frames  now :)

```shell
$ sticky '(^.*transport.*packet_sent.*$)' < *qlog | grep ack_frequency | qlog2fields packet_tolerance max_ack_delay

  0.008053 2 2013
  0.145196 2 10000
  0.146446 3 2013
  0.269779 2 4071
  0.273254 2 7613
  0.287152 2 2160
  0.301051 2 2131
 10.509332 4 2013
 11.271191 3 2131
 11.356601 4 2131
 11.830939 5 2013
 11.861041 6 2013
 22.647684 7 2013
 22.672441 8 2013
 22.706235 9 2013
```
Now here are the actual packet rates. As you can see, the ACK ratio seldom moves away from 1:1, despite a few spikes.
Neither the update_max_ack_delay (2013 usecs, while the typical inter-ack is 4ms) nor the packet tolerance seem to be honoured by the receiver...

![rates](https://user-images.githubusercontent.com/614725/123545547-daa0d780-d758-11eb-910b-5cf0ec053daf.png)

**Comment by andrewkewang** [comment]
adding the qlog for 10Mbps/100kbps. I have to change the extension qlog to  .txt 
[10Mbps_100kbps.server.qlog.txt](https://github.com/private-octopus/picoquic/files/6727129/10Mbps_100kbps.server.qlog.txt)
[10MBps_100kbps.client.qlog.txt](https://github.com/private-octopus/picoquic/files/6727126/10MBps_100kbps.client.qlog.txt)

**Comment by joynwang** [comment]
uploaded qlogs for 10Mbps/100kbps. 
[10Mbps_100kbps.zip](https://github.com/private-octopus/picoquic/files/6727315/10Mbps_100kbps.zip)

**Comment by huitema** [comment]
I have a pull request #1215 that appear to fix the problem. 

The PR detects running with BBR and observing RTT that are much longer than the target. When that is the case, it increases the ACK delay and the ACK gap to match the capacity of the return path. This appears to fix the performance issues:
![image](https://user-images.githubusercontent.com/7464128/124025237-0e703d00-d9a5-11eb-995c-a3183bde0f31.png)

Of course, this is just a validation with a unit test. @joynwang if you could download branch asymmetry-debug and repeat your test, that would be nice.

**Comment by huitema** [comment]
After adding tests, it appears that the fix is robust if the delayed ACK extension is negotiated. If it is not, it relies on estimates of senders bandwidth and return path capacity, and these do not seem too robust. But a partial fix is still useful.

**Comment by joynwang** [comment]
Great! I will try it out on my side. Thanks. 

Joy

 

From: Christian Huitema ***@***.***>
Reply-To: private-octopus/picoquic ***@***.***>
Date: Wednesday, June 30, 2021 at 4:15 PM
To: private-octopus/picoquic ***@***.***>
Cc: "Wang, Joy - 0665 - MITLL" ***@***.***>, Mention ***@***.***>
Subject: Re: [private-octopus/picoquic] BBR Performance issue in low latency asymmetric links (#1213)

 

I have a pull request #1215 that appear to fix the problem.

The PR detects running with BBR and observing RTT that are much longer than the target. When that is the case, it increases the ACK delay and the ACK gap to match the capacity of the return path. This appears to fix the performance issues:

Of course, this is just a validation with a unit test. @joynwang if you could download branch asymmetry-debug and repeat your test, that would be nice.

**Comment by huitema** [comment]
Issue appears fixed.
