### ISSUE TITLE
Is there currently a way to initialize an insecure context?

### ISSUE THREAD

**Issue by warvstar** [private-octopus/picoquic#1232]
My reason for wanting such a thing is to use insecure for a local network, specifically for an AWS load balancer.

**Comment by huitema** [comment]
Define insecure.

**Comment by warvstar** [comment]
I mean without using credentials on the server.

**Comment by huitema** [comment]
The demo program supports a variation of that -- start the server with a self-signed certificate, tell the clients to accept this certificate. The test certificate and the test root certificate list are distributed as '../certs/cert.pem' and '../certs/test-ca.crt'.

**Comment by warvstar** [comment]
Thanks!
