### ISSUE TITLE
Non Sequential Ordering of Streams

### ISSUE THREAD

**Issue by akhprasa** [private-octopus/picoquic#1259]
I started using the sample client-server code to do some testing. My aim is to send multiple files across multiple streams.
Currently, with my experiments, I find that the data in the streams are being sent in a sequential way. Is there a way where I can change the scheduling to a non-sequential order?

**Comment by huitema** [comment]
It would be nice to define exactly what the reasons are for picking a specified order. So far, I know of:

1) Multimedia, which expect for example audio and video streams to be sent in parallel
2) HTTP3, in which the application may ask for relative ordering of different streams

There is a complicating factor with datagrams, which are often used for audio and video streams. The transport sees datagram as a single class, sent by the application as it sees fit, and gives them priority over streams.

There are also two different classes of solutions. One is to let the application specify some kind of policy, the other is to delegate to the application. Picoquic supports the latter, with "just in time" API. The application can mark streams "active" or not, and Picoquic will only attempt to send the active streams.

**Comment by akhprasa** [comment]
I wanted to send a video stream over picoquic and wanted to send the video data in one stream and audio in the other parallelly.

**Comment by huitema** [comment]
What program do you use? The `picoquicdemo` program will not do that.

**Comment by akhprasa** [comment]
I used the sample_picoquic program and modified a bit in that

**Comment by huitema** [comment]
That's probably the reason. The sample is not designed to do this kind of parallel download. You would need to change the way the processing loop reacts to "prepare to send" to signal that one media is ready, then the other one, etc.

**Comment by akhprasa** [comment]
Oh okay.
Thanks for the response.

**Comment by dongsf** [comment]
A simple way is changing 'picoquic_find_ready_stream' to reach "round-bin" for all queued streams.

**Comment by huitema** [comment]
Picoquic has been updated with PR #1295, with the new API `picoquic_set_default_priority` and `picoquic_set_stream_priority`. The least significant bit of the "stream priority" let applications chose between round robin and FIFO.
