### ISSUE TITLE
VN: missing Chosen Version in the Client-Sent Other Versions list

### ISSUE THREAD

**Issue by IvanNardi** [private-octopus/picoquic#1263]
It seems that the, in the TP sent by the client, the Chosen Version is not present in the Other Versions list.
According to the Editor Copy of the draft:
```
Note that the version in the Chosen Version field MUST be included in this list to allow the client to communicate the chosen version's preference
```
Am I missing something?

![Screenshot from 2021-12-03 15-55-06](https://user-images.githubusercontent.com/12729895/144623206-6b04a984-df31-432c-9944-f54a93bc8c22.png)

**Comment by huitema** [comment]
Not missing anything. Thanks for pointing that out. The fix is in PR #1264.
