### ISSUE TITLE
Can picoquicdemo send a user agent string?

### ISSUE THREAD

**Issue by moderation** [private-octopus/picoquic#1296]
I'm doing some testing with `picoquicdemo` against a local Envoy proxy that that then proxies a request to a H3 upstream. In testing it doesn't look like `picoquicdemo` sends a user agent string.

There is reference to `http_header_user_agent` at  https://github.com/private-octopus/picoquic/blob/master/picohttp/h3zero.c#L268

There is `Picoquic-H3zero/0.1` in comments at https://github.com/private-octopus/picoquic/blob/master/picohttp/h3zero.c#L636-L640

Is there a way to set this or ensure the agent string is sent in a request?

**Comment by huitema** [comment]
Sorry for the silence, was working on other issues. Yes, documenting a user agent string makes sense. I am a bit backed up now, but will schedule that. Or review a PR :-)

**Comment by moderation** [comment]
Thanks. I did try a couple of things locally but it looks like there are more changes required in the header construction
```diff
 picohttp/h3zero.c | 6 +++---                                                                        
 1 file changed, 3 insertions(+), 3 deletions(-)

diff --git a/picohttp/h3zero.c b/picohttp/h3zero.c                                                   
index e99d687c..0f8ef84e 100644                                                                      
--- a/picohttp/h3zero.c                                                                              
+++ b/picohttp/h3zero.c                                                                              
@@ -265,7 +265,7 @@ h3zero_qpack_static_t qpack_static[] = {                                         
     { 92, http_header_server, NULL, 0},
     { 93, http_header_timing_allow_origin, "*", 0},
     { 94, http_header_upgrade_insecure_requests, "1", 0},
-    { 95, http_header_user_agent, NULL, 0},                                                         
+    { 95, http_header_user_agent, "Picoquic-H3zero/0.1", 0},                                        
     { 96, http_header_x_forwarded_for, NULL, 0},
     { 97, http_header_x_frame_options, "deny", 0},
     { 98, http_header_x_frame_options, "sameorigin", 0}
@@ -469,10 +469,10 @@ uint8_t * h3zero_parse_qpack_header_value(uint8_t * bytes, uint8_t * bytes_max,
 int h3zero_get_interesting_header_type(uint8_t * name, size_t name_length, int is_huffman)
 {
     char const  * interesting_header_name[] = {
-     ":method", ":path", ":status", "content-type", NULL };                                         
+     ":method", ":path", ":status", "content-type", "user-agent", NULL };                           
     const http_header_enum_t interesting_header[] = {
         http_pseudo_header_method, http_pseudo_header_path,
-        http_pseudo_header_status, http_header_content_type };                                      
+        http_pseudo_header_status, http_header_content_type, http_header_user_agent };              
     http_header_enum_t val = http_header_unknown;
     uint8_t deHuff[256];
```

**Comment by huitema** [comment]
The function "h3zero_get_interesting_header_type" is about parsing incoming headers and extracting a small number of "interesting" fields that get exposed to the application as members of the decoded `h3zero_header_parts_t`. The various HTTP headers are formatted using different functions:
```
uint8_t * h3zero_create_request_header_frame(uint8_t * bytes, uint8_t * bytes_max,
    uint8_t const * path, size_t path_length, char const * host);
uint8_t * h3zero_create_post_header_frame(uint8_t * bytes, uint8_t * bytes_max,
    uint8_t const * path, size_t path_length, char const * host,
    h3zero_content_type_enum content_type);
uint8_t * h3zero_create_response_header_frame(uint8_t * bytes, uint8_t * bytes_max,
    h3zero_content_type_enum doc_type);
uint8_t * h3zero_create_not_found_header_frame(uint8_t * bytes, uint8_t * bytes_max);
uint8_t * h3zero_create_bad_method_header_frame(uint8_t * bytes, uint8_t * bytes_max);
```
It should be possible to add a version field in the request, post, response, not found and bad method headers. I would like to call this by default "h3zero" instead of "picoquic", because that code can be used outside of picoquic. Which brings two questions:

1) The simplest solution is to just add a compiled value to the header when building the frame: client variant for get and post, server variant for response and errors. Is that OK? Do we need a possibility to change this at run time?
2) Should we also decode the user agent string and add the result to the `h3zero_header_parts_t`?

**Comment by huitema** [comment]
Solved. The PR #1348 added "extended" versions of the h3zero message creation functions, adding a UA String parameter. The UA String parameter can take whatever value the application chooses, including NULL. The existing functions are still available; by default, they set the UA String to:
```
#define H3ZERO_USER_AGENT_STRING "H3Zero/1.0"
```
The PR includes changes to the test suite to verify the functionality.

**Comment by moderation** [comment]
@huitema this is awesome. I can confirm in testing it is working. Thanks!
