### ISSUE TITLE
Client connection killed by unexpected VN packet

### ISSUE THREAD

**Issue by huitema** [private-octopus/picoquic#1297]
Looking at the report of a failure in the "interop runner" (https://interop.seemann.io/logs/2022-03-05T08:07/quic-go_picoquic/handshakecorruption/) we find that one of the connection attempts failed:

```
client          | mv /logs/test_log.txt  /logs/mc-psqbzhiulr.txt
client          | /picoquic/picoquicdemo  -L -l /logs/test_log.txt -q /logs/qlog -o /downloads -V -0 -v 00000001 server4 443 /owgmijemge
client          | Starting Picoquic (v0.34f) connection to server = server4, port = 443
client          | Set ALPN to hq-interop based on stored ticket
client          | Set version to 0x00000001 based on stored ticket
client          | Testing scenario: </owgmijemge>
client          | Max stream id bidir remote before start = 0 (0)
client          | Starting client connection. Version = 1, I-CID: 1029059c691c216d
client          | Max stream id bidir remote after start = 396 (396)
client          | Max stream id bidir remote after 0rtt = 396 (396)
client          | Opening stream 0 to GET /owgmijemge
client          | Waiting for packets.
client          | Received a version negotiation request: 00000000, 00000000, 00000000
client          | Received a request to close the connection.
client          | The connection is closed!
client          | Connection end with remote error 0x437.
client          | Out of 1 zero RTT packets, 0 were acked by the server.
client          | Quic Bit was NOT greased by the client.
client          | Quic Bit was NOT greased by the server.
client          | ECN was not received.
client          | ECN was not acknowledged.
client          | Client exit with code = -1
```

The failure here is caused by a version negotiation packet. The short session log shows:

1) The client sending an Initial packet
2) The client receiving a version negotiation packet
3) The client closing the connection.

The version negotiation packet passes the verification checks: SCID and DCID have the expected values. Further checks would show that the packet content is dubious:

```
[33569, "transport", "packet_received", { "packet_type": "version_negotiation", "header": { "packet_size": 35, "version": "00000000", "scid": "1029059c691c216d", "dcid": "29e5da9b6dc970a8" },
    "proposed_versions": ["00000000", "00000000", "00000000"]}],
```

There are two plausible fixes: one would be to verify that the proposed versions contain at least one locally supported version; the other to ignore the version negotiation packet altogether. In fact, only the second alternative makes sense, because spurious VN packets are most likely generated by some kind of middlebox intent on disrupting the connection. At the same time, ignoring all VN packets is a bit harsh, because conformance tests mandate support. We could have the following: 

* ignore but log the VN packets received at the beginning of the connection.
* definitely ignore VN packets if a valid response is received from the server.
* maybe retain the proposed VN and use it if the connection fails.

While this is interesting, fake VN are not the only way to kill a connection. There are other plausible ways, such as:

* injecting an initial packet containing a "connection close"
* injecting an initial packet containing some kind of syntax error
* injecting a packet with incorrect TLS data
* sending a retry packet

Should we try to build resilience against all these?

**Comment by victorstewart** [comment]
if they pose no threat to the stability of the server process and only the connection getting cancelled, then i see no motivation to add code to consider them-- since a faulty client can't expect to establish a connection.

**Comment by huitema** [comment]
The practical threat is a "man on the side" injecting a fake packet in the flow, causing the connection to fail. That cannot be done after the handshake complete, but the following MAY happen:

* before the handshake key is computed on both sides, man on the side can fake Version Negotiation packets, a large variety of Initial packets, and possibly Retry packets. All will cause the connection to fail.
* the man on the side can also inject a perfectly valid Initial response, creating a man-in-the-middle attack. The man on the side can then insert a variety of handshake packets, e.g., a packet containing a "close connection" request. This will cause the connection to fail.

I could do a quick fix and block the particular VN insertion used in the interop tests. This will have nice PR result: make sure that the test matrix for picoquic looks really good. But if we really want a full protection, we need to implement something like https://datatracker.ietf.org/doc/html/draft-duke-quic-protected-initial.

**Comment by huitema** [comment]
The PR #1229 addresses the issue by tightening the tests on incoming VN, including:

* Checking that the source ID matches the Initial CID -- as specified in spec, but not implemented yet.
* Treating proposal of alternate version=0 as an error -- which should be in the spec
* Ignoring VN packets if they do not propose at least one locally supported version.

The PR also include an unit test to verify that the checks are properly implemented.

**Comment by huitema** [comment]
Latest run of interop runner indicate that the issue is fixed.
