### ISSUE TITLE
Picoquic client interop with quiche server

### ISSUE THREAD

**Issue by feters** [private-octopus/picoquic#1310]
I'm was testing picoquic client with quiche server but it does not work, according to them [quiche issue](https://github.com/cloudflare/quiche/issues/1189) it's a client problem, it needs to use an interoperable ALPN.

look at the code but still don't understand, could you please explain to me how to use ALPN or do interop properly?
thank you.

**Comment by huitema** [comment]
From the log, you are trying to use the "sample" code. The sample implements its own protocol. It demonstrates how to implement an application that is not HTTP. But, not being HTTP, it will not interoperate with an HTTP server like Quiche. The ALPN is a way to check that.

**Comment by feters** [comment]
``@huitema My apologies for my late response and thank you for your explanation.
I managed to run it using picoquicdemo. However, when I run against quicly_server it shows `Client exit with code = -1`
I go through the code but still does not have any clue.

this is the command I used:
```
./picoquicdemo -q client_qlog -o /tmp 172.17.0.7 4433 "*1:0:-:10m2.txt;"
```

this is the output:
```
Starting Picoquic (v0.34f) connection to server = 172.17.0.7, port = 4433
Testing scenario: <*1:0:-:10m2.txt;>
Max stream id bidir remote before start = 0 (0)
Starting client connection. Version = 1, I-CID: c66922f9a5065816
Max stream id bidir remote after start = 0 (0)
Waiting for packets.
Client port (AF=2): 38768.
Almost ready!

Connection established. Version = 1, I-CID: c66922f9a5065816, verified: 1
Opening stream 0 to GET /10m2.txt
Received a request to close the connection.
Connection end with local error 0x1.
Quic Bit was NOT greased by the client.
Quic Bit was NOT greased by the server.
ECN was not received.
ECN was not acknowledged.
Received 1245 bytes in 0.159824 seconds, 0.062319 Mbps.
max_data_local: 1048576
max_max_stream_data_local: 2097152
max_data_remote: 16777216
max_max_stream_data_remote: 396
ack_delay_remote: 1000 ... 1000
max_ack_gap_remote: 2
ack_delay_local: 25000 ... 25000
max_ack_gap_local: 2
max_mtu_sent: 1472
max_mtu_received: 1280
Client exit with code = -1
```

**Comment by huitema** [comment]
That would be easier to diagnose if you collected the qlog traces.
