### ISSUE TITLE
Sample code for file transfer append

### ISSUE THREAD

**Issue by jeromelau1984** [private-octopus/picoquic#1322]
Dear huitema:
How do I use the picoquic_sample to send and receive data in both directions？
I can understand the process of the client downloading data from the server,
but on the client side, there was only one picoquic_callback_prepare_to_send callback event before picoquic_file_open,
What can I do to send user data from client to server.
<img width="596" alt="image" src="https://user-images.githubusercontent.com/45782912/159479303-eac5fcde-c0f6-4a1d-874b-4dd26c8b84d5.png">

_Originally posted by @jeromelau1984 in https://github.com/private-octopus/picoquic/issues/932#issuecomment-1075099846_

**Comment by jeromelau1984** [comment]
@huitema Another way, can you provide any sample code for client and server trans data of bidir transmission?

**Comment by huitema** [comment]
You will need to write a different application. The "sample" protocol is just that, a code sample. The only protocol messages are on the client side "get file", which results in opening a bidirectional stream, passing the file name in the stream data sent by the client, and waiting for the file content or a reset in the server stream. To handle bidirectional, that protocol should be extended, and that very much means writing your own application.
