### ISSUE TITLE
Should drop connection if no response for some time

### ISSUE THREAD

**Issue by huitema** [private-octopus/picoquic#1342]
This test between aioquic client and picoquic server shows bizarre behavior after aioquic sends a "connection close", and that packet is lost:

![image](https://user-images.githubusercontent.com/7464128/161174205-986f015c-94cf-474b-b8e2-4734c030619e.png)

The server will keep attempting to send its last message for 30 seconds, sending that message almost 3,000 times:

![image](https://user-images.githubusercontent.com/7464128/161175925-2962f51f-8405-4863-8dc1-21d3b7d49dde.png)

Surely there is no need to wait 30 seconds and 3,000 messages to realize that the peer is not answering!

**Comment by victorstewart** [comment]
maybe best to overall cap the number of retransmissions before closing a connection?

**Comment by huitema** [comment]
Yes. This is a side effect of the "preemptive repeat" option, which automatically repeats the last unacknowledged packets if there is nothing else to do and the congestion control agrees. This overrides the normal behavior, repeat 7 times and then give up.

**Comment by huitema** [comment]
The preemptive repeat option is really useful on long delay links, e.g., intercontinental or satellite. I turned it on in the interop runner builds in order to get some exposure, and there was a whole series of issues. But then, many of the issues can repro in other contexts, e.g., if for some reasons there are many losses and also many spurious repeat. SO it is good to see those issues fixed...

**Comment by huitema** [comment]
Fixed in PR #1343
