### ISSUE TITLE
how to enable multipath in picoquic_sample?

### ISSUE THREAD

**Issue by dongsf** [private-octopus/picoquic#1344]
I want test multipath in real environment, how to setup multipath test in picoquic_sample?

**Comment by huitema** [comment]
You would have to add code and do two things:

1) announce support for the multipath option in the client, so it is negotiated.
2) on the client, open alternate paths.

You can look at the code in "mutipath_test.c":

* setting multipath options in `multipath_init_params()`, lines 339-351
* after the handshake, have the client call `picoquic_probe_new_path()`, as inside the function `multipath_test_one`, lines 538-541

**Comment by dongsf** [comment]
thanks，It works, and announce support for the multipath option in the server is required
