### ISSUE TITLE
GSO issue in sample code

### ISSUE THREAD

**Issue by muxamilian** [private-octopus/picoquic#1345]
When GSO is enabled in the picoquic sample code (the default) this seems to cause packets to be combined, which results in a `payload_decrypt_error` on the client side (`picoquic_sample client`). This leads to a large percentage of lost packets and slow transmission speed. I ran the sample server and client exactly as described in the `README.md`. I transferred a file containing 1M of random binary data from the server to the client. I compiled picoquic without any errors and all tests of picoquic pass. Also picotls compiled without problems. I tested it on Ubuntu 20.04, x86-64. The issue does not only occur on localhost but also when simulating a simple topology in mininet.

The fix I found is to disable GSO in the `sample_client.c` and the `sample_server.c` like this:
 
*picoquic_packet_loop(quic, 0, server_address.ss_family, 0, 0, **1**, sample_client_loop_cb, &client_ctx)*

Attached are the qlogs and the pcap file. 

[logs_and_pcap.zip](https://github.com/private-octopus/picoquic/files/8454070/logs_and_pcap.zip)

GSO and GRO are enabled as can be seen in the output of `sudo ethtool -k lo` (next paragraph). However, also disabling GSO and GRO doesn't seem to make a difference. 

```Features for lo:
rx-checksumming: on [fixed]
tx-checksumming: on
	tx-checksum-ipv4: off [fixed]
	tx-checksum-ip-generic: on [fixed]
	tx-checksum-ipv6: off [fixed]
	tx-checksum-fcoe-crc: off [fixed]
	tx-checksum-sctp: on [fixed]
scatter-gather: on
	tx-scatter-gather: on [fixed]
	tx-scatter-gather-fraglist: on [fixed]
tcp-segmentation-offload: on
	tx-tcp-segmentation: on
	tx-tcp-ecn-segmentation: on
	tx-tcp-mangleid-segmentation: on
	tx-tcp6-segmentation: on
generic-segmentation-offload: on
generic-receive-offload: on
large-receive-offload: off [fixed]
rx-vlan-offload: off [fixed]
tx-vlan-offload: off [fixed]
ntuple-filters: off [fixed]
receive-hashing: off [fixed]
highdma: on [fixed]
rx-vlan-filter: off [fixed]
vlan-challenged: on [fixed]
tx-lockless: on [fixed]
netns-local: on [fixed]
tx-gso-robust: off [fixed]
tx-fcoe-segmentation: off [fixed]
tx-gre-segmentation: off [fixed]
tx-gre-csum-segmentation: off [fixed]
tx-ipxip4-segmentation: off [fixed]
tx-ipxip6-segmentation: off [fixed]
tx-udp_tnl-segmentation: off [fixed]
tx-udp_tnl-csum-segmentation: off [fixed]
tx-gso-partial: off [fixed]
tx-sctp-segmentation: on
tx-esp-segmentation: off [fixed]
fcoe-mtu: off [fixed]
tx-nocache-copy: off [fixed]
loopback: on [fixed]
rx-fcs: off [fixed]
rx-all: off [fixed]
tx-vlan-stag-hw-insert: off [fixed]
rx-vlan-stag-hw-parse: off [fixed]
rx-vlan-stag-filter: off [fixed]
l2-fwd-offload: off [fixed]
hw-tc-offload: off [fixed]
esp-hw-offload: off [fixed]
esp-tx-csum-hw-offload: off [fixed]
rx-udp_tunnel-port-offload: off [fixed]```

**Comment by huitema** [comment]
Interesting. The qlog are quite clear: the server sends packets of length 1252, but the client receives packets of length 1536. Something is definitely wrong.

I wonder whether this is something about the sample code. The demo server at test.privateoctopus.com:4433 runs with GSO on, with no issue. GSO was also used in performance tests, and errors would have had a big effect.

**Comment by victorstewart** [comment]
i've used GSO extensively for a year and there are no issues with it. so definitely a bug in the sample code.

**Comment by huitema** [comment]
Trying to repro on a virtual machine running Ubuntu 20.04 focal. No repro. Logs show GSO is used, no problem.

**Comment by huitema** [comment]
@muxamilian I think there is something in your configuration that trips the code. The code relies on *UDP* segmentation offload. From the logs it seems that:

* picoquic believes that udp_gso is enabled, 
* but the packet logs show that it is not, causing errors.

This shows that the test of UDP GSO support is a little weak. The current test is static:
```
# if defined(UDP_SEGMENT)
static int udp_gso_available = 1;
#else
static int udp_gso_available = 0;
#endif
```
It seems that on your system UDP GSO is available, in the sense that `UDP_SEGMENT` is defined, but it is somehow disabled. What would be a good way to test that?

**Comment by huitema** [comment]
I think I saw this problem already once. UDP Segmentation offload only works if the local interface supports it. It does not work with the mininet driver -- we saw that bug happen when running the "interop runner". The system level test is insufficient, but I do not know how to do an interface level test.

**Comment by victorstewart** [comment]
tx-checksum-ipv4: off [fixed]
tx-checksum-ipv6: off [fixed]

i think this is the problem.

the network chip must support checksum offloading for GSO to work. sendmsg calls with fail with EIO if you try to send a GSO packet without that hardware support.

**Comment by muxamilian** [comment]
Thank you for your swift response! To clarify, the logs I sent were recorded when the server was listening on localhost and the client was connecting to localhost, with no mininet involved, although with mininet I saw the same behavior. 

My guess now is that something about my local system is weird and causes this behavior. 

By disabling GSO I can run picoquic as expected, so the issue is resolved for me. I will let you know if I find some more information about what causes this odd behavior.

**Comment by huitema** [comment]
@muxamilian I understand that disabling UDP GSO in the code sample solves your issue, but could you please test the code in PR #1346 ? It includes a mechanism to detect the UDP GSO error, correct it by repeating the affected packets, and then automatically disable UDP GSO for the following calls. I would very much like to see if it fixes your issue.

**Comment by muxamilian** [comment]
I cloned the repository freshly, checked out the branch `sample-gso`, compiled picoquic, used the certificates I used before, reran the server and downloaded the 1M file with the client. 

It seems like I'm observing the same behavior as before. 

[20fa4d79b98af496.zip](https://github.com/private-octopus/picoquic/files/8455896/20fa4d79b98af496.zip)

**Comment by huitema** [comment]
Interesting. That means that the call to `sendmsg (64B)` returns "OK, no error, 64KB sent", and then the first 1536 bytes of that are received by the client. That's really weird, because the "msg" parameters specify the UDP GSO option, as well as "don't fragment". I changed the logging to confirm that, if you don't mind one more round of debugging. But there does not seem to be many alternatives, except adding a command line option in the sample so users can set the "GSO off" option. Or maybe turning it off all the time, but that's at least a factor 10 in perfs!

**Comment by huitema** [comment]
The PR #1346 now implements the simplest solution: add the keyword "no_gso" at the end of the command line to disable UDP_GSO. This is required when the platform believes that it support UDP GSO, but in fact it doesn't. Real time assessment would be better, but it is not clear how to do that.

**Comment by muxamilian** [comment]
> @muxamilian I think there is something in your configuration that trips the code. The code relies on _UDP_ segmentation offload. From the logs it seems that:

You were right with that. I was experimenting with mptcp before and used a modified [multipath tcp kernel](https://github.com/multipath-tcp/mptcp).

I didn't expect that this would have an influence on picoquic since there is no TCP involved. 

Apparently this kernel caused the issue with GSO. Reverting to the standard kernel resolved the problem. 

Thank you for your help.
