### ISSUE TITLE
Forget Stream

### ISSUE THREAD

**Issue by victorstewart** [private-octopus/picoquic#1354]
when tearing down an entire connection, we have the ability to use `picoquic_delete_cnx` and instantly forget the connection without waiting for synchronization with the opposing party. this allows for optimal simple one-step cleanup of memory and objects surrounding the connection and its streams.

but there is no way to do this for a stream when closing it. thus whether we use the stop sending or FIN pathway, there will be some future callback for the stream on the connection (because the connection will persist). this requires the implementer to leave the memory/object representing the stream in limbo, and finish cleaning it up later.

at present i've implemented this by creating a dummy pointer and assigning it as the stream_ctx with `picoquic_set_app_stream_ctx`, then checking in the callback if the stream_ctx is this pointer and bouncing out if so. but it would be more efficient to have this inside of picoquic so the callbacks are never called, any data received dropped, etc.

**Comment by victorstewart** [comment]
well your prompt has two heads: what shades of reliability and involvement should the application have after calling this function? 

and i think the point of adding it at all is a hard none and none to those questions. otherwise the existing interface allows a user to piecemeal together some degree of each.

the point is to say "throw away everything immediately", which isn't currently possible.

so i think once this is called all previously queued data pending send should dropped, all incoming data should be dropped and the callback never called for the stream again.

and that all we do is ACK until we reach FIN or Reset to make sure the opposing party completes the stream as well, in the interest of cleanliness given the assumption is the connection will continue and we want to minimize traffic on the now dead stream.

the irony is that this pairs intrinsically with perfect reliability of transported data. since only the application can provide true reliability of its data and state, once that exists, the transport is just a sequential delivery mechanism that the application can stop and throw away at any time.

that's why i came full circle to hard instant deletes at the transport level.

**Comment by huitema** [comment]
OK, updating the PR to suppress each of the 6 stream-related callbacks:

Callback | What | Status
--------- | ------ | -----
stream_data  | Data received  | Suppressed as side effect of "stop sending"
stream_fin | Fin received  | Suppressed as side effect of "stop sending"
stream_reset |Reset Stream received | Adding flag to suppress callback
stop_sending | Stop sending received | Adding flag to suppress callback
stream_gap | not implemented | Nothing to do
prepare_to_send | Ask application to send data in frame | Suppressed as side effect of "reset stream"

**Comment by victorstewart** [comment]
i think these callback behaviors sound great and make a lot of sense! 

will these be the new behaviors picoquic wide in response to stop sending and reset? if so also great.

**Comment by huitema** [comment]
Many applications want to be informed that a stream has been reset, so they can for example clean up the state of a pending transaction. The side effects mentioned above apply. If an application resets a stream, it is never asked to provide data for that stream. If it asks the peer to stop sending, it is never bothered with incoming data.
