### ISSUE TITLE
HTTP/3 client conditionally sends :authority, causing malformed requests

### ISSUE THREAD

**Issue by LPardue** [private-octopus/picoquic#1356]
In https://github.com/private-octopus/picoquic/blob/master/picohttp/h3zero.c#L779, the :authority pseudo-header is only added if host != null. That leads to a request message that is malformed according to https://quicwg.org/base-drafts/draft-ietf-quic-http.html#section-4.1.1.1-8

The solution is to always send something.

edit: this leads to interop failures with quiche-server after I added more robust checks in https://github.com/cloudflare/quiche/commit/838b00e63efbdd31b2cc4c2e6163f5630ee7a13c

**Comment by huitema** [comment]
Or maybe send a single "."?

**Comment by LPardue** [comment]
HTTP relies on URIs, so there has to be an authority and wuth H3, it must be acceptably matched against the cert provided by the server. SNI is also a MUST in H3 unless you provide something else.

Sure, our simple apps bebd the rules a bit but I'm curious in what case can a request be made to something where the host is null. Like, if you were writing out that out as a URI, is it even logical?

**Comment by huitema** [comment]
Assume the URL is `https://127.0.0.1/some_file.txt`. What should the authority be? Just the IP address?

**Comment by huitema** [comment]
By the way, I just had that question in a DM:

_Could you please tell me how do you set the :authority header on the client?
on the interop runner between quiche server and pico client its provided but when I did it on my server its not._

_Interop_
```
got request [(":method", "GET"), (":scheme", "https"), (":path", "/hgfmcnxtjv"), (":authority", "server4")] on stream id 4
```
_My server_
```
got request [(":method", "GET"), (":scheme", "https"), (":path", "/2MB.txt"), ("user-agent", "H3Zero/1.0")] on stream id 0
```
That's typical of a common test usage, in which researchers are not too interested in SNI or actual security, they are just trying to set connections and study the traffic. They will typically use a test certificate for the server -- for test.example.com, shipped with the code, and added to a test root list for tests. I suppose that I could by default use the SNI in that test certificate, until someone complains...

**Comment by feters** [comment]
Hello, It was me who asked the question. I set up the SNI and requested to use it instead of IP and it works perfectly well.
it is true that I was only focusing on the performance and energy efficiency of the server. My big apologies for this simple thing causing trouble but thanks a lot to both of you for being patient and trying to help me.

> Assume the URL is `https://127.0.0.1/some_file.txt`. What should the authority be? Just the IP address?
on quiche server indeed sending IP address with port.

**Comment by huitema** [comment]
@feters @LPardue the PR #1360 enforces presence of authority in H3 requests.

If "picoquicdemo" starts without specifying a host or SNI, the program warns the user about protocol failures. If the server negotiates hq-interop, the connection will work, but of it negotiates H3 the connection will fail immediately. The program will not invent an SNI, the user will just have to restart it with proper arguments.

 You may want to review.

**Comment by LPardue** [comment]
Sounds like a good compromise 👍

**Comment by feters** [comment]
agree, that will solve it.
