### ISSUE TITLE
Connection Close Without Chatting

### ISSUE THREAD

**Issue by victorstewart** [private-octopus/picoquic#1363]
it can be advantageous sometimes to close a connection without informing the opposing party. for example in an application server when malformed messages are discovered. this could be due to a client bug, or a malicious party proding the server. either way spending the resources to gracefully close the connection not only costs something, but can greatly increase the bad traffic volume: a buggy client might get into a connect -> close -> reconnect loop, or an attacker is now provided clarity as to boundaries and provided signals with which to increase the rate of their attacks.

this can be accomplished currently by using `picoquic_delete_cnx` but the problem is this function can not be called from within `picoquic_stream_data_cb_fn`, so the application operation code is then forced to be aware whether it's running within the callback or elsewhere plus (if running within the callback) discard all streams (to make sure no more data is read in) and persist the  cnx object for deletion after the callback cycle completes.

so it would be great to have a single consistent path here, so that one function can always be called and all this state awareness and persisting and cleanup can be avoided. something like `picoquic_close` with a silent flag.

**Comment by huitema** [comment]
Solved in PR #1364
