### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by chizi-chizi** [private-octopus/picoquic#1377]
-- The C compiler identification is GNU 7.5.0
-- The CXX compiler identification is GNU 7.5.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Initial CMAKE_C_FLAGS=
-- Found PTLS: /root/work/data/quic_learn/picotls/build
-- picotls/include: /root/work/data/quic_learn/picotls/include
-- picotls libraries: /root/work/data/quic_learn/picotls/build;/root/work/data/quic_learn/picotls/build
-- PTLS compiled without support for Fusion
-- Found OpenSSL: /usr/lib/x86_64-linux-gnu/libcrypto.so (found version "1.1.1")
-- root:
-- OpenSSL_VERSION: 1.1.1
-- OpenSSL_INCLUDE_DIR: /usr/include
-- OpenSSL_LIBRARIES: /usr/lib/x86_64-linux-gnu/libssl.so;/usr/lib/x86_64-linux-gnu/libcrypto.so
-- CMAKE_C_FLAGS: -std=c99 -Wall -O3 -fno-exceptions -fno-signed-zeros -frename-registers -fno-trapping-math   -DPTLS_WITHOUT_FUSION
-- CMAKE_CXX_FLAGS:  -DPTLS_WITHOUT_FUSION
-- Configuring done
WARNING: Target "picoquic-core" requests linking to directory "/root/work/data/quic_learn/picotls/build".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "picoquic-core" requests linking to directory "/root/work/data/quic_learn/picotls/build".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "picohttp-core" requests linking to directory "/root/work/data/quic_learn/picotls/build".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "picohttp-core" requests linking to directory "/root/work/data/quic_learn/picotls/build".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "picoquicdemo" requests linking to directory "/root/work/data/quic_learn/picotls/build".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "picoquicdemo" requests linking to directory "/root/work/data/quic_learn/picotls/build".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "picolog_t" requests linking to directory "/root/work/data/quic_learn/picotls/build".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "picolog_t" requests linking to directory "/root/work/data/quic_learn/picotls/build".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "picoquic_ct" requests linking to directory "/root/work/data/quic_learn/picotls/build".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "picoquic_ct" requests linking to directory "/root/work/data/quic_learn/picotls/build".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "picohttp_ct" requests linking to directory "/root/work/data/quic_learn/picotls/build".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "picohttp_ct" requests linking to directory "/root/work/data/quic_learn/picotls/build".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "picoquic_sample" requests linking to directory "/root/work/data/quic_learn/picotls/build".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "picoquic_sample" requests linking to directory "/root/work/data/quic_learn/picotls/build".  Targets may link only to libraries.  CMake is dropping the item.
-- Generating done
-- Build files have been written to: /root/work/data/quic_learn/picoquic/build
[  0%] Building C object CMakeFiles/picohttp-core.dir/picohttp/democlient.c.o
[  1%] Building C object CMakeFiles/picoquic-log.dir/loglib/csv.c.o
[  2%] Building C object CMakeFiles/picohttp-core.dir/picohttp/h3zero.c.o
[  3%] Building C object CMakeFiles/picoquic-log.dir/loglib/cidset.c.o
[  4%] Building C object CMakeFiles/picoquic-log.dir/loglib/autoqlog.c.o
[  5%] Building C object CMakeFiles/picoquic-core.dir/picoquic/bbr.c.o
[  6%] Building C object CMakeFiles/picoquic-log.dir/loglib/logconvert.c.o
[  7%] Building C object CMakeFiles/picohttp-core.dir/picohttp/demoserver.c.o
[  8%] Building C object CMakeFiles/picohttp-core.dir/picohttp/quicperf.c.o
[  9%] Building C object CMakeFiles/picohttp-core.dir/picohttp/siduck.c.o
[  9%] Building C object CMakeFiles/picoquic-log.dir/loglib/logreader.c.o
[ 10%] Building C object CMakeFiles/picoquic-log.dir/loglib/qlog.c.o
[ 11%] Building C object CMakeFiles/picoquic-log.dir/loglib/svg.c.o
[ 11%] Building C object CMakeFiles/picoquic-core.dir/picoquic/bytestream.c.o
[ 12%] Building C object CMakeFiles/picoquic-core.dir/picoquic/cc_common.c.o
[ 13%] Building C object CMakeFiles/picoquic-core.dir/picoquic/config.c.o
[ 14%] Building C object CMakeFiles/picoquic-core.dir/picoquic/cubic.c.o
[ 15%] Building C object CMakeFiles/picoquic-core.dir/picoquic/fastcc.c.o
[ 16%] Building C object CMakeFiles/picoquic-core.dir/picoquic/frames.c.o
[ 17%] Building C object CMakeFiles/picoquic-core.dir/picoquic/intformat.c.o
[ 17%] Building C object CMakeFiles/picoquic-core.dir/picoquic/logger.c.o
[ 18%] Building C object CMakeFiles/picoquic-core.dir/picoquic/logwriter.c.o
[ 19%] Linking C static library libpicohttp-core.a
[ 19%] Built target picohttp-core
[ 20%] Building C object CMakeFiles/picoquic-core.dir/picoquic/newreno.c.o
[ 21%] Building C object CMakeFiles/picoquic-core.dir/picoquic/packet.c.o
[ 22%] Building C object CMakeFiles/picoquic-core.dir/picoquic/performance_log.c.o
[ 23%] Building C object CMakeFiles/picoquic-core.dir/picoquic/picohash.c.o
[ 24%] Building C object CMakeFiles/picoquic-core.dir/picoquic/picoquic_lb.c.o
[ 25%] Linking C static library libpicoquic-log.a
[ 25%] Built target picoquic-log
[ 25%] Building C object CMakeFiles/picoquic-core.dir/picoquic/picosocks.c.o
[ 26%] Building C object CMakeFiles/picoquic-core.dir/picoquic/picosplay.c.o
In file included from /usr/include/pthread.h:24:0,
                 from /root/work/data/quic_learn/picoquic/picoquic/picoquic.h:37,
                 from /root/work/data/quic_learn/picoquic/picoquic/picosocks.h:116,
                 from /root/work/data/quic_learn/picoquic/picoquic/picosocks.c:22:
/usr/include/time.h:113:5: error: unknown type name ‘locale_t’; did you mean ‘socklen_t’?
     locale_t __loc) __THROW;
     ^~~~~~~~
     socklen_t
/root/work/data/quic_learn/picoquic/picoquic/picosocks.c: In function ‘picoquic_socks_cmsg_parse’:
/root/work/data/quic_learn/picoquic/picoquic/picosocks.c:421:81: error: dereferencing pointer to incomplete type ‘struct in_pktinfo’
                     ((struct sockaddr_in*)addr_dest)->sin_addr.s_addr = pPktInfo->ipi_addr.s_addr;
                                                                                 ^~
/root/work/data/quic_learn/picoquic/picoquic/picosocks.c: In function ‘picoquic_socks_cmsg_format’:
/root/work/data/quic_learn/picoquic/picoquic/picosocks.c:602:65: error: invalid application of ‘sizeof’ to incomplete type ‘struct in_pktinfo’
                 &control_length, IPPROTO_IP, IP_PKTINFO, sizeof(struct in_pktinfo));
                                                                 ^~~~~~
/root/work/data/quic_learn/picoquic/picoquic/picosocks.c:604:24: error: dereferencing pointer to incomplete type ‘struct in_pktinfo’
                 pktinfo->ipi_addr.s_addr = ((struct sockaddr_in*)addr_from)->sin_addr.s_addr;
                        ^~
CMakeFiles/picoquic-core.dir/build.make:285: recipe for target 'CMakeFiles/picoquic-core.dir/picoquic/picosocks.c.o' failed

**Comment by chizi-chizi** [comment]
@huitema  thanks your answer,  i have already fix the issue:
            PICO_TLS_DIR=$PICO_QUIC_DIR/picotls
            PICO_TLS_BUILD_DIR=$PICO_TLS_DIR/build
            PICO_TLS_INSTALL_DIR=$PICO_TLS_DIR/INSTALL_DIR
            cmake .. -DCMAKE_INSTALL_PREFIX=../INSTALL_DIR \
                     -DCMAKE_BUILD_TYPE=Debug \
                     -DPTLS_CORE_LIBRARY=$PICO_TLS_BUILD_DIR \
                     -DPTLS_OPENSSL_LIBRARY=$PICO_TLS_BUILD_DIR/libpicotls-openssl.a \
                     -DPTLS_CORE_LIBRARY=$PICO_TLS_BUILD_DIR/libpicotls-core.a \
                     -DPTLS_FUSION_LIBRARY=$PICO_TLS_BUILD_DIR/libpicotls-fusion.a
in this way, these libraries can discover. 

the full shell script  is as below:
#!/bin/bash


CORE_NUM=$(grep -c ^processor /proc/cpuinfo)

CURDIR=`pwd`


PICO_QUIC_DIR=$CURDIR/
PICO_QUIC_BUILD_DIR=$PICO_QUIC_DIR/build
PICO_QUIC_INSTALL=$PICO_QUIC_DIR/INSTALL_DIR

PICO_TLS_DIR=$PICO_QUIC_DIR/picotls
PICO_TLS_BUILD_DIR=$PICO_TLS_DIR/build
PICO_TLS_INSTALL_DIR=$PICO_TLS_DIR/INSTALL_DIR

PTLS_OPENSSL_LIBRARY=$PICO_TLS_BUILD_DIR/libpicotls-core.a
PTLS_OPENSSL_LIBRARY="$PTLS_OPENSSL_LIBRARY $PICO_TLS_BUILD_DIR/libpicotls-minicrypto.a"
PTLS_OPENSSL_LIBRARY="$PTLS_OPENSSL_LIBRARY $PICO_TLS_BUILD_DIR/libpicotls-fusion.a"
PTLS_OPENSSL_LIBRARY="$PTLS_OPENSSL_LIBRARY $PICO_TLS_BUILD_DIR/libpicotls-openssl.a"

fix_ols_cmake_error(){
    #reference to https://unix.stackexchange.com/questions/512681/how-do-i-set-a-cmake-policy#:~:text=Use%20the%20cmake_policy%20command%20to,Wno%2Ddev%20to%20suppress%20it.
    #在第一行前添加字符串cmake_policy(SET CMP0046 OLD),fix error about:
    #CMake Warning (dev) at cmake/dtrace-utils.cmake:37 (ADD_DEPENDENCIES):
    #Policy CMP0046 is not set: Error on non-existent dependency in
    #add_dependencies.  Run "cmake --help-policy CMP0046" for policy details.
    #Use the cmake_policy command to set the policy and suppress this warning.
    head -n 1 picotls/cmake/dtrace-utils.cmake | grep "cmake_policy(SET CMP0046 OLD)" > /dev/null
    if [ $? -ne 0 ]
    then
        echo "sed -i '1icmake_policy(SET CMP0046 OLD)' $PICO_TLS_DIR/cmake/dtrace-utils.cmake"
        sed -i '1icmake_policy(SET CMP0046 OLD)' $PICO_TLS_DIR/cmake/dtrace-utils.cmake
    fi

}

install_ols_dependency(){
# apt-get install faketime libscope-guard-perl libtest-tcp-perl
# fix error about "Can't locate Net/EmptyPort.pm in @INC (you may need to install the Net::EmptyPort module)" when exec make check
    dpkg -l | grep faketime > /dev/null
    if [ $? -ne 0 ]
    then
        echo "apt-get install faketime -y"
        apt-get install faketime -y
    fi

    dpkg -l | grep libscope-guard-perl > /dev/null
    if [ $? -ne 0 ]
    then
        echo "apt install libscope-guard-perl > /dev/null"
        apt-get install libscope-guard-perl -y
    fi

    dpkg -l | grep libtest-tcp-perl > /dev/null
    if [ $? -ne 0 ]
    then
        echo "apt-get install libtest-tcp-perl -y"
        apt-get install libtest-tcp-perl -y
    fi
}

fix_cmake_error(){
    fix_ols_cmake_error
}

install_dependency(){
    install_ols_dependency
}

show_help(){
  echo "$0 [ tls | quic | all | pre]"
  echo "tls             build tls"
  echo "quic            build quic"
  echo "all             build tls and quic"
  echo "pre             install depency and fix cmake error"
}

if [ $# -ne 1 ]; then
       show_help
       exit -1
fi


#picoquic depends picotls so first build picotls

make_tls(){
    pushd  $PICO_QUIC_DIR
    if [ ! -d $PICO_TLS_DIR ]
    then
        git clone git@github.com:chizi-chizi/picotls.git
    fi
    pushd $PICO_TLS_DIR
        #reference to https://github.com/h2o/picotls
        git submodule init
        git submodule update

        if [ ! -d $PICO_TLS_BUILD_DIR ]
        then
            mkdir $PICO_TLS_BUILD_DIR
        else
            rm -rf $PICO_TLS_BUILD_DIR
            mkdir $PICO_TLS_BUILD_DIR
        fi

        pushd $PICO_TLS_BUILD_DIR
            cmake .. -DCMAKE_INSTALL_PREFIX=../INSTALL_DIR \
                     -DCMAKE_BUILD_TYPE=Debug
            make  -j $CORE_NUM
            make check
            #make install # current, not support install
        popd
    popd
    popd
}

make_quic(){
    pushd $PICO_QUIC_DIR
        if [ ! -d $PICO_QUIC_BUILD_DIR ]
        then
            mkdir $PICO_QUIC_BUILD_DIR
        else
            rm -rf $PICO_QUIC_BUILD_DIR
            mkdir $PICO_QUIC_BUILD_DIR
        fi

        pushd $PICO_QUIC_BUILD_DIR
            cmake .. -DCMAKE_INSTALL_PREFIX=../INSTALL_DIR \
                     -DCMAKE_BUILD_TYPE=Debug \
                     -DPTLS_CORE_LIBRARY=$PICO_TLS_BUILD_DIR \
                     -DPTLS_OPENSSL_LIBRARY=$PICO_TLS_BUILD_DIR/libpicotls-openssl.a \
                     -DPTLS_CORE_LIBRARY=$PICO_TLS_BUILD_DIR/libpicotls-core.a \
                     -DPTLS_FUSION_LIBRARY=$PICO_TLS_BUILD_DIR/libpicotls-fusion.a
                     #-DPTLS_OPENSSL_LIBRARY=$PTLS_OPENSSL_LIBRARY

                     #-DPTLS_DIR=$PICO_TLS_BUILD_DIR
            make  -j $CORE_NUM
            make install
            popd
    popd
}

make_pre(){
    fix_cmake_error
    install_dependency
}

make_all(){
    make_pre
    make_tls
    make_quic
}
make_test(){
    echo $PTLS_OPENSSL_LIBRARY
}
case $1 in
all)
    make_all
    ;;
tls)
    make_tls
    ;;
quic)
    make_quic
    ;;
pre)
    make_pre
    ;;
test)
    make_test
    ;;
*)
    show_help
    ;;
esac

**Comment by huitema** [comment]
OK, if your problem is solved, maybe we can close the issue. But I am still a bit worried, because other users may not want to write a long script. The default process is to clone picotls, build it, then clone picoquic and build it. It works for many users of picoquic. I would like to understand why that default process did not work for you. What need to change to make the build simpler?

**Comment by chizi-chizi** [comment]
@huitema  maybe because the complier env and cmake version,
```
# uname -a
Linux learn 4.15.0-143-generic #147-Ubuntu SMP Wed Apr 14 16:10:11 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

# cmake --version
cmake version 3.10.2
```

 for example,when i build picotls, i will get a cmake warning  as below:
```
CMake Warning (dev) at cmake/dtrace-utils.cmake:37 (ADD_DEPENDENCIES):
  Policy CMP0046 is not set: Error on non-existent dependency in
  add_dependencies.  Run "cmake --help-policy CMP0046" for policy details.
  Use the cmake_policy command to set the policy and suppress this warning.

  The dependency target
  "/root/work/data/quic_learn/picoquic/picotls/build/picotls-probes.o" of
  target "generate-picotls-probes" does not exist.
Call Stack (most recent call first):
  CMakeLists.txt:58 (DEFINE_DTRACE_DEPENDENCIES)
This warning is for project developers.  Use -Wno-dev to suppress it.
```
and then 
```
#cmake --help-policy CMP0046
CMP0046
-------

Error on non-existent dependency in add_dependencies.

CMake 2.8.12 and lower silently ignored non-existent dependencies
listed in the ``add_dependencies()`` command.

The OLD behavior for this policy is to silently ignore non-existent
dependencies. The NEW behavior for this policy is to report an error
if non-existent dependencies are listed in the ``add_dependencies()``
command.

This policy was introduced in CMake version 3.0.
CMake version 3.10.2 warns when the policy is not set and uses
OLD behavior.  Use the cmake_policy command to set it to OLD or
NEW explicitly.

.. note::
  The ``OLD`` behavior of a policy is
  ``deprecated by definition``
  and may be removed in a future version of CMake.
```
which say 
```
CMake 2.8.12 and lower silently ignored non-existent dependencies
listed in the ``add_dependencies()`` command.
```
but in my machine, the cmake version is 3.10.2,

When I compile picoquic, it prompts that some libraries cannot be found, I found the final reason, when I compiled picotls, I created a build directory in picotls, and then executed cmake.., most cmakes use this, but picotls can't be used this way, because cmake in picquic /FindPTLS.cmake
```
 11 set(PTLS_HINTS ${PTLS_PREFIX}/lib ${CMAKE_BINARY_DIR}/../picotls ../picotls)
 12 find_library(PTLS_CORE_LIBRARY picotls-core HINTS ${PTLS_HINTS})
```
the value of PTLS_HINTS is  picotls , not picotls/build, final i rewrite the script, i hope it can help other users:
```
#!/bin/bash

CORE_NUM=$(grep -c ^processor /proc/cpuinfo)
CURDIR=`pwd`
PICO_QUIC_DIR=$CURDIR
PICO_QUIC_BUILD_DIR=$PICO_QUIC_DIR/build
PICO_QUIC_INSTALL=$PICO_QUIC_DIR/INSTALL_DIR
PICO_TLS_DIR=$PICO_QUIC_DIR/picotls

fix_ols_cmake_warnning(){
    #reference to https://unix.stackexchange.com/questions/512681/how-do-i-set-a-cmake-policy#:~:text=Use%20the%20cmake_policy%20command%20to,Wno%2Ddev%20to%20suppress%20it.
    #在第一行前添加字符串cmake_policy(SET CMP0046 OLD),fix error about:
    #CMake Warning (dev) at cmake/dtrace-utils.cmake:37 (ADD_DEPENDENCIES):
    #Policy CMP0046 is not set: Error on non-existent dependency in
    #add_dependencies.  Run "cmake --help-policy CMP0046" for policy details.
    #Use the cmake_policy command to set the policy and suppress this warning.
    head -n 1 picotls/cmake/dtrace-utils.cmake | grep "cmake_policy(SET CMP0046 OLD)" > /dev/null
    if [ $? -ne 0 ]
    then
        echo "sed -i '1icmake_policy(SET CMP0046 OLD)' $PICO_TLS_DIR/cmake/dtrace-utils.cmake"
        sed -i '1icmake_policy(SET CMP0046 OLD)' $PICO_TLS_DIR/cmake/dtrace-utils.cmake
    fi
}

install_ols_dependency(){
# apt-get install faketime libscope-guard-perl libtest-tcp-perl
# fix error about "Can't locate Net/EmptyPort.pm in @INC (you may need to install the Net::EmptyPort module)" when exec make check
    dpkg -l | grep faketime > /dev/null
    if [ $? -ne 0 ]
    then
        echo "apt-get install faketime -y"
        apt-get install faketime -y
    fi

    dpkg -l | grep libscope-guard-perl > /dev/null
    if [ $? -ne 0 ]
    then
        echo "apt install libscope-guard-perl > /dev/null"
        apt-get install libscope-guard-perl -y
    fi

    dpkg -l | grep libtest-tcp-perl > /dev/null
    if [ $? -ne 0 ]
    then
        echo "apt-get install libtest-tcp-perl -y"
        apt-get install libtest-tcp-perl -y
    fi
}

fix_cmake_prompt(){
    fix_ols_cmake_warnning
}

install_dependency(){
    install_ols_dependency
}

show_help(){
  echo "$0 [ tls | quic | all | pre]"
  echo "tls             build tls"
  echo "quic            build quic"
  echo "all             build tls and quic"
  echo "pre             install depency and fix cmake error"
}

if [ $# -ne 1 ]; then
       show_help
       exit -1
fi

#picoquic depends picotls so first build picotls
make_tls(){
    pushd  $PICO_QUIC_DIR
        if [ ! -d $PICO_TLS_DIR ]
        then
            git clone git@github.com:h2o/picotls.git
        fi

        pushd $PICO_TLS_DIR
            #reference to https://github.com/h2o/picotls
            git submodule init
            git submodule update

            cmake . -DCMAKE_INSTALL_PREFIX=../INSTALL_DIR \
                     -DCMAKE_BUILD_TYPE=Debug
            make  -j $CORE_NUM
            make check

        popd
    popd
}

make_quic(){
    pushd $PICO_QUIC_DIR
        if [ ! -d $PICO_QUIC_BUILD_DIR ]
        then
            mkdir $PICO_QUIC_BUILD_DIR
        else
            rm -rf $PICO_QUIC_BUILD_DIR
            mkdir $PICO_QUIC_BUILD_DIR
        fi

        pushd $PICO_QUIC_BUILD_DIR
            cmake .. -DCMAKE_INSTALL_PREFIX=../INSTALL_DIR \
                    -DCMAKE_BUILD_TYPE=Debug

                     #-DPTLS_DIR=$PICO_TLS_BUILD_DIR
            make  -j $CORE_NUM
            make install
        popd
    popd
}

make_pre(){
    fix_cmake_prompt
    install_dependency
}

make_all(){
    make_pre
    make_tls
    make_quic
}

make_test(){
    echo $PTLS_OPENSSL_LIBRARY
    echo $PICO_TLS_DIR
}

case $1 in
all)
    make_all
    ;;
tls)
    make_tls
    ;;
quic)
    make_quic
    ;;
pre)
    make_pre
    ;;
test)
    make_test
    ;;
*)
    show_help
    ;;
esac
```
