### ISSUE TITLE
Don't send connection Close when send not supported TLS

### ISSUE THREAD

**Issue by alagoutte** [private-octopus/picoquic#138]
With last ngtcp2 (and openssl master),  TLS 1.3 use draft-26 and when i send a Initial i don't get return.

We need to send a Connection close with error (513 / 0x0201)

**Comment by huitema** [comment]
I will check what happens. If you have time, I will need to get a repro. Maybe I should check with a simple non supported version. I need a test vector for that.

**Comment by huitema** [comment]
Just managed to get a repro in a unit test.

**Comment by huitema** [comment]
Fixed with PR #141
