### ISSUE TITLE
how will the load balancer deploy and work ?

### ISSUE THREAD

**Issue by huowa222** [private-octopus/picoquic#1388]
i saw a merge log of the load balancer integration, however, i don't see it is used in any code. 
1. is the load balancer work in the same working process as the quic server? if yes, how will the packets forwarded to the correct server , i only see a list functions of the CID generations.

**Comment by huitema** [comment]
The current specification of "load balancer compatibility" assumes an external load balancer acting as  NAT/Router that captures incoming packet and directs them to the appropriate server. The load balancer would be on theincoming path, but not on the outgoing path. The specification is still evolving. See https://datatracker.ietf.org/doc/draft-ietf-quic-load-balancers/ for the specification of Connection Identifiers, and https://datatracker.ietf.org/doc/draft-ietf-quic-retry-offload/ for managing connection retries for a pool of servers.

There has been some work to manage specific scenarios, such as running multiple instances of picoquic sharing port 443 on a single server, e.g., one server per CPU core. I suppose that we could add code in the repo to support that explicitly. We could also envisage other scenarios, such as for example "anycast routing". Do you have a specific scenario in mind?
