### ISSUE TITLE
BUG: Multiple wrongly returned error codes

### ISSUE THREAD

**Issue by bathooman** [private-octopus/picoquic#1395]
### Description
- Type: Non-conformance Bug
- Priority: Minor

## Non-conformance Bug
Commit: 7f2fbdfb9f1f7431b31c04fb5d9b4d30b560540b

**Expected behavior 1**   
The QUIC 1 [RFC](https://www.rfc-editor.org/rfc/rfc9000.html) in section 12.4 states that:

> An endpoint MUST treat the receipt of a frame of unknown type as a connection error of type FRAME_ENCODING_ERROR.

**Actual behavior 1** 

When a client and a server are exchanging packets, receipt of an unknown frame will cause the generation of a CC with the PROTOCOL_VIOLATION error code.
I have attached the captured interaction between a QUIC client and a server containing the mentioned problem. The master secret log file is also attached so that one can decrypt the exchanged traffic.

[unknown-frame-type.zip](https://github.com/private-octopus/picoquic/files/9337389/unknown-frame-type.zip)

---------------------------------------------------------------
**Expected behavior 2**   
The QUIC 1 [RFC](https://www.rfc-editor.org/rfc/rfc9000.html) in section 19.15 states that:

> An 8-bit unsigned integer containing the length of the connection ID.  Values less than 1 and greater than 20 are invalid and MUST be treated as a connection error of type FRAME_ENCODING_ERROR.

**Actual behavior 2** 
When a client and a server are exchanging packets, receipt of an NCI with the connection ID length greater than 20 will cause the generation of a CC with the PROTOCOL_VIOLATION error code.

![image](https://user-images.githubusercontent.com/3464382/184642004-24cfad8f-dfec-4057-8075-b6e24f83c0b5.png)

The captured interaction, along with the master secret log file, is attached in the following:

[invalid-new-connection-id-length.zip](https://github.com/private-octopus/picoquic/files/9337400/invalid-new-connection-id-length.zip)

---------------------------------------------------------------
**Expected behavior 3**   
The QUIC 1 [RFC](https://www.rfc-editor.org/rfc/rfc9000.html) in section 19.15 states that:

> The value in the Retire Prior To field MUST be less than or equal to the value in the Sequence Number field. Receiving a value in the Retire Prior To field that is greater than that in the Sequence Number field MUST be treated as a connection error of type FRAME_ENCODING_ERROR.

**Actual behavior 3** 
When a client and a server are exchanging packets, receipt of an NCI by the server where the value for the retire prior to field is greater than the value for the sequence number will cause the generation of a CC with the PROTOCOL_VIOLATION error code.

![image](https://user-images.githubusercontent.com/3464382/184643591-e75ff5ae-9372-4afd-bc7d-ccc93409480d.png)

The captured interaction, along with the master secret log file, is attached in the following:

[invalid-retiring-sequence-number.zip](https://github.com/private-octopus/picoquic/files/9337436/invalid-retiring-sequence-number.zip)

**Comment by huitema** [comment]
@bathoomann -- thanks for the report. Yes, there was a bit of looseness in the choice of response error code.

On the "frame type error" issue, there is some ambiguity in the specification between "frames that are not allowed in a specific protocol state", which are protocol violations, and "frames that are unknown", which are "frame encoding errors". The code in picoquic checks that only authorized types are present in initial, 0rtt and handshake packets, and will return a protocol violation if it sees a frame that it does not expect at this point -- unknown or not. The code will return the "frame type error" if the unknown frame arrives in 1RTT packet.

For the NEW_CONNECTION_ID errors, picoquic had kept the pre-standard behavior: return a "frame encoding error" if there was an error parsing the frame, such as an unexpected field, and "protocol violation" or a more specific code if the content of the frame did not make sense. The new Connection ID definition does not quite follow that philosophy. I need to fix the code.

**Comment by huitema** [comment]
Fixed in PR #1398
