### ISSUE TITLE
BUG: Receipt of NEW_TOKEN by a server is not handled correctly

### ISSUE THREAD

**Issue by bathooman** [private-octopus/picoquic#1396]
### Description
- Type: Non-conformance Bug
- Priority: Medium

---------------------------------------------------------------
## Non-conformance Bug
Commit: 7f2fbdfb9f1f7431b31c04fb5d9b4d30b560540b

**Expected behavior**   
The QUIC 1 [RFC](https://www.rfc-editor.org/rfc/rfc9000.html) in section 19.7 states that:

> Clients MUST NOT send NEW_TOKEN frames. A server MUST treat receipt of a NEW_TOKEN frame as a connection error of type PROTOCOL_VIOLATION.

**Actual behavior** 
When a client and a server are exchanging packets, receipt of a NEW_TOKEN frame will not trigger any type of error by the server. In the following, the server is running on port 20220, and the client is running on port 60581. As one can see, when the server receives an NT, it does not generate any error.

![image](https://user-images.githubusercontent.com/3464382/184635947-5b3deb88-a261-418b-bd07-5c7d925d82dc.png)

I have attached the captured interaction between a QUIC client and a server containing the mentioned problem. The master secret log file is also attached so that one can decrypt the exchanged traffic.

[client-generated-new-token.zip](https://github.com/private-octopus/picoquic/files/9337180/client-generated-new-token.zip)

**Comment by huitema** [comment]
Verified. The parsing code merely skips over these frames if received by a server, should trigger an error.

**Comment by huitema** [comment]
Fixed in Pr #1398
