### ISSUE TITLE
New V2 constants

### ISSUE THREAD

**Issue by IvanNardi** [private-octopus/picoquic#1419]
I would like to implement the final (hopefully...) random numbers of QUICv2. See: https://github.com/quicwg/quic-v2/pull/85/files
@huitema , do you prefer I keep the old values too (i.e. values in draft-v7) or can I remove them?

**Comment by huitema** [comment]
No, by all means, go for it. Make sure that you rev the picoquic version number in your PR!

**Comment by IvanNardi** [comment]
Ok

> Make sure that you rev the picoquic version number in your PR!

What do you mean with that? Update `PICOQUIC_VERSION` define?

**Comment by huitema** [comment]
Yes please.

**Comment by IvanNardi** [comment]
Done in 2d05d0ff25bdb61d587530eb686a6abf5ce73770
