### ISSUE TITLE
cmake Parse error in command line argument: -DPICOQUIC_FETCH_PTLS

### ISSUE THREAD

**Issue by joergdeutschmann-i7** [private-octopus/picoquic#1423]
In `README.md` it says `cmake -DPICOQUIC_FETCH_PTLS .` which returns
```
Parse error in command line argument: -DPICOQUIC_FETCH_PTLS
Should be: VAR:type=value
CMake Error: No cmake script provided.
CMake Error: Problem processing arguments. Aborting.
```
(tested on Ubuntu 20.04.5 LTS with `cmake version 3.16.3`)

Should probably be `cmake -DPICOQUIC_FETCH_PTLS=1 .`

**Comment by marcblanchet** [comment]
same here. I did cmake -DPICOQUIC_FETCH_PTLS=Y and worked

**Comment by huitema** [comment]
I just fixed the README.
