### ISSUE TITLE
picoquicdemo on separate hosts

### ISSUE THREAD

**Issue by alexj0l** [private-octopus/picoquic#1424]
Hi everyone,

is it possible to run picoquicdemo as "server" on one host and then run it from another host as client to test the performance on link between them? Sadly I didn't found anything useful for my case.

Thanks in advance.

**Comment by alexj0l** [comment]
Small update: I figured it out but now I'm getting an error on client side.
I want to test the maximal throughput achieved by picoquic by running
`./picoquicdemo -D <server_name> 4443 /20000000` on client and
`./picoquicdemo -p 4443` on server side.
The server is running without any problems, but the client gets the message
`
Starting Picoquic (v1.1.0.0) connection to server = <server_name>, port = 4443
Files not saved to disk (-D, no_disk)
Testing scenario: </200000000>
Careful: NULL SNI is incompatible with HTTP 3. Expect errors!
Max stream id bidir remote before start = 0 (0)
Starting client connection. Version = 1, I-CID: 822cc5d9fe5b8484
Max stream id bidir remote after start = -4 (0)
Waiting for packets.
Client port (AF=2): 57910.
Negotiated ALPN: h3
Almost ready!

Connection established. Version = 1, I-CID: 822cc5d9fe5b8484, verified: 1
Cannot send GET command for stream(0): /200000000
Received a request to close the connection.
Client exit with code = -1
`

**Comment by huitema** [comment]
The message "NULL SNI is incompatible with HTTP 3. Expect errors!" is because you are not providing a server name. In TLS 1.3, the server name is used to verify the server certificate and prevent man-in-the-middle attacks. If you do not have a server name, things will break, just like the message says. The solution is to set an arbitrary host name using the "-n" option, as in:

```
./picoquicdemo -n test -D <server_name> 4443 /20000000
```

**Comment by alexj0l** [comment]
@huitema Thanks a lot! Is there a way to revert de load direction? Instead of download to make upload (other than swapping client and server)?

**Comment by huitema** [comment]
The demo server supports a POST function. It is somewhat tested, but not documented very well. It probably needs some debugging.

**Comment by alexj0l** [comment]
One more question: By specifying `-G reno` is the client using Reno or NewReno?

**Comment by huitema** [comment]
NewReno.

**Comment by alexj0l** [comment]
Thanks! May I ask which version of BBR is supported by picodemoquic? The first one or V2?

**Comment by huitema** [comment]
First one, but with a series of changes soewhat siila to 2, e.g., reaction to large losses or to ECN marks.

**Comment by huitema** [comment]
Closing the issue, after documenting the solution in [the wiki](https://github.com/private-octopus/picoquic/wiki/Testing-without-DNS-names-or-Certificates)
