### ISSUE TITLE
picoquic may not match picotls version

### ISSUE THREAD

**Issue by dreamwind1985** [private-octopus/picoquic#1453]
I build picoquic on linux system and get this mistake:
picoquic/tls_api.c:1834:16: error: ‘ptls_context_t’ {aka ‘struct st_ptls_context_t’} has no member named ‘esni’
...

The git version of picotls which I use is commit id 61228171836561b5f6feee5bf0ad81414d47e748。
I think picoquic may use an old version of picotls， is it?

**Comment by huitema** [comment]
The README says "The current code is tested against the Picotls version of Sat Dec 10 01:56:28 2022 +0900, after commit 7d294ab4f2e0ed749b4bcfaf533225a4e0c096f7." The ESNI code was removed in picotls long before that. You are probably using an old version of picotls.
