### ISSUE TITLE
Change definition of QHKDF-Expand

### ISSUE THREAD

**Issue by huitema** [private-octopus/picoquic#147]
From interop test, @nibanks wrote:
And just to double check you updated the label expand function too?

It used to use
~~~
QHKDF-Expand(Secret, Label, Length) =             
                HKDF-Expand(Secret, QuicHkdfLabel, Length)

struct {
   uint16 length = Length;
   opaque label<6..255> = "QUIC " + Label;
   uint8 hashLength = 0;
} QuicHkdfLabel;
~~~
Now it's:
~~~
QHKDF-Expand(Secret, Label, Length) =    
                   HKDF-Expand(Secret, QhkdfExpandInfo, Length)

struct {
  uint16 length = Length;
  opaque label<6..255> = "QUIC " + Label;
} QhkdfExpandInfo;
~~~
This will affect all key computations.

**Comment by nibanks** [comment]
Let me know when your server is fixed and then I'll test it out.

**Comment by huitema** [comment]
It is very painful, because it requires a new API in the TLS stack. Or duplicating part of the TLS stack in the Quic code, which is equally bad.

**Comment by huitema** [comment]
The code calls "ptls_aead_new()" at various places. But that applies the TLS formating of labels, which includes hash_context<0..255>, i.e. a trailing zero byte when no hash context is used. The options are either to update ptls_aead_new() with a "no hash context" argument in picotls.c, or to copy paste ptls_aead_new() into quic_aead_new() in the quic code. Of course, you will need the corresponding changes or copies in the various functions that are called through ptls_aead_new(), all the way to ptls_hkdf_expand_label().

**Comment by huitema** [comment]
Of course, if we want to keep draft-09 compatibility, we will need to do that with a test of the version flags, calling it the old way for the old versions and the new way for the new versions. But I am not sure I want to do that. It is simpler to just create a draft-09 branch, and let people download that if they want to test against draft-09.

**Comment by nibanks** [comment]
Once you support draft-11, you won't be able to simultaneously support older QUIC versions because of the header changes. So I'd say don't worry about back compat.

**Comment by huitema** [comment]
But then, that begs the question about whether to support draft 10 at all. The encryption is not compatible with draft 9, and the header is not compatible with draft 11. I would rather jump to draft 11.

**Comment by nibanks** [comment]
Draft 11 has the same `QhkdfExpandInfo`. Whether you do it in stages, draft-10 and then draft-11, or just jump straight to 11, doesn't really matter. You still need a change here.

**Comment by huitema** [comment]
So, first things first, I have created a branch "support-draft-09". If some other implementation wants to test their version of draft-09, they will just have to download that.

**Comment by huitema** [comment]
I have a PR ready for the code changes, and it must be good since it matches the test vector on the wiki! Check PR #148.

**Comment by huitema** [comment]
Fixed.
