### ISSUE TITLE
Test Migration using Mininet

### ISSUE THREAD

**Issue by LZJ0913** [private-octopus/picoquic#1498]
I use mininet to build a network topology:"h1 has two NICs h1-eth0 and h1-eth1 connected to r1 and r2 respectively, r1 and r2 connected to r3, r3 connected to h2". Before "ifconfig h1-eth1 down", two paths between h1 and h2 "h1-eth0-r1-r3-h2" and "h1-eth1-r2-r3-h2" are connected.
I run "./picoquicdemo -n test -o ../received 192.168.2.10 4433 <big file>" in h1, and run "./picoquicdemo -w ../server_files -p 4433" in h2. After the CLI returned "Connection established", I run "ifconfig h1-eth1 down", but instead of Migrtaion, the connection is broken.

The following figure is the log records of h1. 
![client](https://github.com/private-octopus/picoquic/assets/78056809/ab3489d9-14b1-48a8-8f54-abc5078d9443)

The following figure is the log records of h2.
![server](https://github.com/private-octopus/picoquic/assets/78056809/c19b5699-0955-405a-817a-2f2e2673b273)

I guess it's possible that the client didn't detect new path because I overlooked some steps. I would be grateful if you could provide information or suggestions.

**Comment by huitema** [comment]
That scenario is tested and should work if you enable multipath. It is not tested, and probably does not work yet, if you have not enabled multipath.

The first step would be to add a test case for exactly your scenario.
