### ISSUE TITLE
Having issues setting up Multipath with picoquicdemo

### ISSUE THREAD

**Issue by sureshpsu** [private-octopus/picoquic#1513]
Hi,
   I am trying to setup a Realtime wireless systems with WiFi and WiGi as two paths. I am using ./picoquicdemo to stream data over both wifi and wigi but unfortunately it is not working (it just uses one path). Currently, I am using following commands:

on client: ./picoquicdemo -a perf -M 3 -A 192.168.10.245/5, 192.168.1.4/4 192.168.10.231 4433 "*1:0:-:397:5000000"
on Server: ./picoquicdemo -a perf -M 3 -A 192.168.10.231/3, 192.168.1.2/2

With the above setup, i am not able to stream QUIC data over both WiFi and WiGi in my setup. Please, advise me if i am doing some thing wrong?

Thanking you,
Warm regards,
Suresh

**Comment by huitema** [comment]
Maybe ask @clarkzjw, who is using that option successfully?

I think you have two issues:

1) The parameters should be quoted, as in:
~~~
./picoquicdemo -a perf -M 3 -A "192.168.10.245/5, 192.168.1.4/4 192.168.10.231" 4433 "*1:0:-:397:5000000"
 ~~~
 2) The parameters are only applied on the client.

**Comment by clarkzjw** [comment]
try quoting IPs and interface indexes on the client side
```
./picoquicdemo -a perf -M 3 -A "192.168.10.245/5,192.168.1.4/4" 192.168.10.231 4433 "*1:0:-:397:5000000"
```
and yes, the `-A` option only applies to the client.

**Comment by sureshpsu** [comment]
Hi Jinwei Zhao,
                      I got it working, thanks for all the inputs. The issue was with the routing table, picoquic was not able to reach the server from the secondary link.....I fixed the routing issues and it started working.

I used tcpdump to debug and caught the issue.......

PS: Indeed, picoquic did send quic packets over the secondary link but it just could not route it to the server.

Thanking you,
Warm regards,
Suresh
