### ISSUE TITLE
Throughput issues when implemented on mininet

### ISSUE THREAD

**Issue by meejeei** [private-octopus/picoquic#1536]
Hello, I conducted an experiment to compare throughput by configuring a dumbbell topology on a mininet and sending TCP (CUBIC) using iperf3 on top and picoquic on the bottom.

However, I set the bandwidth of the link between the switches to 100M, but found that the combined throughput of TCP and throughput of picoquic exceeded 100M.

If you know the solution, I wonder if you can explain it.

Iperf3-c 10.0.0.2 was sent to the tcp client
picoquic client has a ./picoquicdemo-n test-G cubic-D 10.0.0.4 4433 /500000000
For the picoquic server, type ./picoquicdemo -p4433 -G cubic -c /home/... -k /home/.

**Comment by huitema** [comment]
Looks like this is an issue with your setup, not an issue with TCP or picoquic. I have no idea how mininet "sets the bandwidth to 100M" (megabits or megabytes?), but obviously the way it was done does not work.

**Comment by meejeei** [comment]
I set the tbf rate to 100Mbit using the netem function of Linux. I'll have to find out if there's.

Thank you very much for your quick reply.
