### ISSUE TITLE
How should we use PicoQuic to develop applications

### ISSUE THREAD

**Issue by abc1590011** [private-octopus/picoquic#1556]
How can I use the APIs in PicoQuic to develop an application？

**Comment by huitema** [comment]
Your best bet is to start by looking at the sample code in sample.c, sample_client.c, sample_server.c, picoquic_sample.h.

**Comment by huitema** [comment]
Also, the documentation in doc/architecture.md

**Comment by abc1590011** [comment]
> Your best bet is to start by looking at the sample code in sample.c, sample_client.c, sample_server.c, picoquic_sample.h.
