### ISSUE TITLE
[Documentation] Building (and Rebuilding) single targets

### ISSUE THREAD

**Issue by notBroman** [private-octopus/picoquic#1604]
To build a single target defined in `CMakeLists.txt` the command `cmake --build . --target <target_name>` can be used this makes (re)building targets easier. This will rebuild the target and it's dependencies (if anything has changed). Since this works for all executables defined in `CMakeLists.txt` I'm unsure how to add this to the documentation. Nonetheless this would be useful to mention somewhere, seeing as independent building is mentioned in `sample/README.md`.

For example to (re)build only the sample in `sample/` the command `cmake --build . --target picoquic_sample` can be used. The command was run from the top most directory (the one`CMakeLists.txt` is in).
<img width="300" alt="example.png" src="https://github.com/private-octopus/picoquic/assets/75252557/851df100-981d-4ec6-9dad-a5a61d535a4c">

**Comment by huitema** [comment]
If I understand correctly, you would like to document the build process. That sounds like a good idea. How about preparing a PR to add something like `.../doc/building_picoquic.md`? I would be happy to review a PR.

**Comment by notBroman** [comment]
Would this replace the 'Building Picoquic' section in the `README.md` or just expand on it?

**Comment by huitema** [comment]
Let's do a two step. First merely add a reference in the README.md, then remove what we believe is redundant or unneeded.

**Comment by RichLogan** [comment]
@notBroman Apologies if I've make the wrong assumption here, but I was just reading through this and when you say:

> For example to (re)build only the sample in `sample/` the command `cmake --build . --target picoquic_sample` can be used. The command was run from the top most directory (the one `CMakeLists.txt` is in).

It sounds like you're doing / advocating an in source build, which are generally something we should avoid when using CMake to avoid polluting the source directory with build files. 

Better to use a dedicated build directory and run build commands pointing to or in said build directory. e.g generating using `cmake -S <picoquic_root> -B <your_build_directory>` (or something like `cd <picoquic_root>;mkdir <your_build_directory>;cd <your_build_directory>;cmake ..`), and then `cmake --build <your_build_directory> --target picoquic_sample`.

(Can substitute `.` depending on what directory you're currently in, but your build dir shouldn't be the repo dir).
