### ISSUE TITLE
Simulating limited link buffer

### ISSUE THREAD

**Issue by notBroman** [private-octopus/picoquic#1652]
Hello, I am currently trying to figure out if there is a way to test for congestion in picoquic. I saw that the loss of the link is implemented using 'leaky bucket' in `picoquictest_sim_link_submit`, is that where a max capacity associated with the bucket? As far as I can see in `st_picoquictest_sim_link_t` there is only a time associated with it, to ensure the rate.

Is something similar to limiting the number of packets done in any other place?

**Comment by huitema** [comment]
The link buffer size is specified as "queue delay max", which is expressed in microseconds. I don't remember why I did that 5 years ago, I guess mostly because the standard size is expressed as function of the BDP, such as "2 BDP", which is achieved by setting the queue delay to 2*latency.

**Comment by huitema** [comment]
The leaky bucket code is for something else: simulating AQM that put a soft limit to the local bandwidth. That's typically an issue for delay-based congestion controllers, and that was a known issue with BBR.

**Comment by notBroman** [comment]
Thank you for the reply, it seems I was indeed looking in the wrong spot.
