### ISSUE TITLE
Security vulnerability due to unbounded storage of TLS stream

### ISSUE THREAD

**Issue by AsakuraMizu** [private-octopus/picoquic#1745]
## Description
picoquic treats TLS streams the same as normal data streams, and there is no capacity limit for them. As a result, their size may grow infinitely since there is no flow control for crypto data in QUIC.

An remote attacker may send an unlimited number of `CRYPTO` frames after handshaking, resulting in unbounded memory usage and leading to a denial-of-service attack.

## Tested versions
Latest git commit (deaf162)

## Suggestion
Limit the capacity of TLS streams and close the connection with a `CRYPTO_BUFFER_EXCEEDED` error code when the limit is exceeded as described in [RFC 9000 - 7.5. Cryptographic Message Buffering](https://www.rfc-editor.org/rfc/rfc9000.html#section-7.5).

**Comment by huitema** [comment]
Thanks for the report.

Can you take a look at PR #1746? It fixes the code, and adds a test in the test suite to reproduce the "excessive offset" and verifies that such excessive offsets result in a connection close with error code CRYPTO_BUFFER_EXCEEDED.

**Comment by huitema** [comment]
I wrote a blog entry describing the bug and the fix. @AsakuraMizu, do you want me to link that to a home page or similar?

**Comment by AsakuraMizu** [comment]
> I wrote a blog entry describing the bug and the fix. @AsakuraMizu, do you want me to link that to a home page or similar?

Thank you for the kind offer! I just want to clarify that the original discovery of the vulnerability was made by my friend, and I simply replicated it on picoquic. No need to link to anything for now, but I really appreciate the mention.
