### ISSUE TITLE
Compare `UDP_COALESCED_INFO` against `cmsg_type` not `cmsg_level`

### ISSUE THREAD

**Issue by mxinden** [private-octopus/picoquic#1772]
As far as I can tell, `UDP_COALESCED_INFO` is a `cmsg_type`, not `cmsg_level`. The corresponding `cmsg_level` should be `IPPROTO_UDP`.

https://github.com/private-octopus/picoquic/blob/6f1c5f4a7721b25604460b0d36cb5375088a716c/picoquic/picosocks.c#L400

See msquic implementation for reference:

https://github.com/microsoft/msquic/blob/c761886b3c3dfb09106584393b9c7580baca4c53/src/platform/datapath_winuser.c#L3215-L3221

Hope I am not missing something.

**Comment by huitema** [comment]
@mxinden Thanks for finding that! The interesting part is that tests of the existing code were working, although maybe by chance. I have a fix in PR #1773, if you want to take a look.
