### ISSUE TITLE
Exploring Noise-QUIC as an alternative to TLS

### ISSUE THREAD

**Issue by rsepassi** [private-octopus/picoquic#1779]
Some findings from an initial investigation:

If we delete the following files from picoquic:
```
tls_api.c
picoquic_ptls_openssl.c
picoquic_ptls_minicrypto.c
picoquic_ptls_fusion.c
picoquic_mbedtls.c
```

And add the following typedef to `logger.c` and `logwriter.c`, and remove the line `#include <picotls.h>`:
```
typedef struct st_ptls_iovec_t {
    uint8_t *base;
    size_t len;
} ptls_iovec_t;
```

Then the dependency on picotls is removed, and we're left with the following 46 undefined symbols:

```
picoquic_aead_confidentiality_limit
picoquic_aead_decrypt_generic
picoquic_aead_decrypt_mp
picoquic_aead_encrypt_generic
picoquic_aead_encrypt_mp
picoquic_aead_free
picoquic_aead_get_checksum_length
picoquic_aead_integrity_limit
picoquic_aes128_ecb_create
picoquic_aes128_ecb_encrypt
picoquic_aes128_ecb_free
picoquic_apply_rotated_keys
picoquic_cipher_free
picoquic_compute_new_rotated_keys
picoquic_create_cnxid_reset_secret
picoquic_crypto_context_free
picoquic_crypto_random
picoquic_crypto_uniform_random
picoquic_delete_retry_protection_contexts
picoquic_dispose_verify_certificate_callback
picoquic_encode_retry_protection
picoquic_find_retry_protection_context
picoquic_get_initial_aead_context
picoquic_get_tls_time
picoquic_initialize_tls_stream
picoquic_is_tls_complete
picoquic_master_tlscontext
picoquic_master_tlscontext_free
picoquic_pn_encrypt
picoquic_pn_iv_size
picoquic_prepare_retry_token
picoquic_public_random
picoquic_public_random_64
picoquic_public_random_seed
picoquic_public_uniform_random
picoquic_set_cipher_suite
picoquic_setup_initial_traffic_keys
picoquic_tls_client_authentication_activated
picoquic_tls_set_client_authentication
picoquic_tls_set_verify_certificate_callback
picoquic_tls_stream_process
picoquic_tlscontext_create
picoquic_tlscontext_free
picoquic_tlscontext_trim_after_handshake
picoquic_verify_retry_protection
picoquic_verify_retry_token
```

All of which are declared in `tls_api.h`, except for `picoquic_set_cipher_suite`, which is declared in `picoquic.h`.

So a pretty clean separation! Love to see it.

A dozen or so of these seem to be related to context lifetimes, so basically independent of any crypto-specific stuff.

A Noise IK handshake - where both sides already have keys for each other - is a single round-trip, and the data/ciphertext messages carry a 16-byte MAC and an 8-byte counter.

Will take more of a look later. Any initial thoughts? If you can share any high-level info on how these functions are orchestrated, or places where there might be an impedance mismatch, that'd be much appreciated.

**Comment by rsepassi** [comment]
The Noise protocol if interested in taking a look: http://www.noiseprotocol.org/noise.html
And its usage in Wireguard, as an example: https://www.wireguard.com/protocol/

**Comment by rsepassi** [comment]
Looked over things a bit more. aes128 is only used in the LB configuration, so can drop that for now. Looks like the core of things are these 28 functions:
```
// picoquic_aead_confidentiality_limit
// picoquic_aead_decrypt_generic
// picoquic_aead_decrypt_mp
// picoquic_aead_encrypt_generic
// picoquic_aead_encrypt_mp
// picoquic_aead_free
// picoquic_aead_get_checksum_length
// picoquic_aead_integrity_limit
// picoquic_apply_rotated_keys
// picoquic_cipher_free
// picoquic_compute_new_rotated_keys
// picoquic_create_cnxid_reset_secret
// picoquic_crypto_context_free
// picoquic_delete_retry_protection_contexts
// picoquic_encode_retry_protection
// picoquic_find_retry_protection_context
// picoquic_get_initial_aead_context
// picoquic_get_tls_time
// picoquic_initialize_tls_stream
// picoquic_is_tls_complete
// picoquic_pn_encrypt
// picoquic_pn_iv_size
// picoquic_prepare_retry_token
// picoquic_setup_initial_traffic_keys
// picoquic_tls_stream_process
// picoquic_tlscontext_trim_after_handshake
// picoquic_verify_retry_protection
// picoquic_verify_retry_token
```

**Comment by huitema** [comment]
Of course, we don't want to actually delete picotls, etc. There is no desire to remove support for PKI, TLS 1.3, etc. My understanding is that we will get a compiling option to build a "picoquic with noise" variant.

But before we do that, we should have a discussion of what we mean by "QUIC with noise". My expectation is that QUIC with "embed Noise", as an alternative to "embedding TLS1.3". The basic architecture should remain: a handshake phase using Initial and Handshake packets, providing a master secret, which is then used to derive the packet protection key (AEAD encryption of packets) and the header protection key. Most of the packet encryption in the current code would still be used, perhaps getting the AEAD code from a different library.

But first, let's have a spec.

**Comment by rsepassi** [comment]
Yep, we agree: provide an option to build picoquic with Noise, where that means "embed Noise" instead of "embed TLS1.3". "Delete" etc were implementation explorations.

IANAC(ryptographer), so would be stretching to write a spec, though I could draft something.

Mathias Hall-Andersen, David Wong, Nick Sullivan, and Alishah Chator wrote up [nQUIC: Noise-Based QUIC Packet Protection](https://eprint.iacr.org/2019/028) which uses Noise (IK) in place of TLS 1.3.

They mention some desire to bring something to the QUIC WG but I don't know if they did or if it went anywhere.

**Comment by huitema** [comment]
Let's take the nQUIC paper as your spec. According to that paper, the Noise key exchange is carried in Initial packets, and produces a master secret. So we get a parallel:

QUIC | nQUIC
------|-------
initial packet (Client Hello) -&gt; | initial packet (Noise) ->&gt;
&lt;- initial packet(Server Hello)  | &lt;- initial packet (Noise)
&lt;- handshake packet (Server flight) | (maybe more initial packets)
handshake packet(Client Final) -&gt |
-- keys available --                             |  -- keys available --   

After the keys are available, QUIc and nQUIC should be using exactly the same code.

**Comment by huitema** [comment]
There may be a to split "tls_api.c" in three parts:

* loading crypto stacks
* doing the key exchange (parallel codes for TLS 1.3 and Noise)
* computing the various AEAD keys that are needed from the secrets

**Comment by rsepassi** [comment]
Yes, the parallel looks right. There are no more initial packets in nQUIC; there is exactly 1 client->server packet, and 1 server->client response. At that point, the client has completed the handshake. The server completes the handshake upon receiving the first authenticated packet from the client with the new shared secret (Finished, or any other packet).

I'm still digesting `tls_api.c` but the split you suggest looks reasonable. I see a file comment about having a "crypto-provider" API, so this might yield progress on that front.

The semantics of `picoquic_tls_stream_process` and the epochs are not yet clear to me. My initial understanding is that it is responsible for:
1. Reading from, updating `consumed_offset`, deleting from, and writing to each of the epoch streams.
2. Transitioning a client upon a successful handshake via `picoquic_client_almost_ready_transition`
3. Transitioning a server upon a successful handshake via `picoquic_false_start_transition` or directly to `picoquic_state_server_almost_ready`.
4. Erroring via `picoquic_connection_error` if there is a handshake error

Things I don't yet understand:
* Is the stream read from always the same as the stream written to? Or is there a state machine relationship between the epochs?
* Are the epochs Initial and Handshake only for longer TLS handshakes? i.e. Should all of the Noise messages be happening on the 1RTT stream?
* How to ensure the server waits for a client Finished packet before reporting the handshake complete. I opened another issue re `picoquic_false_start_transition` and `picoquic_state_server_almost_ready`; feel free to close it if you'd rather just discuss here.

I'm setting aside 0RTT and retry tokens for now until I have a more solid understanding.

**Comment by huitema** [comment]
picoquic_tls_stream_process  is very much linked to the architecture of picotls. The epochs are defined by TLS 1.3, in which to each epoch corresponds a stage in the handshake progress and a set of AEAD keys. TLS messages are sent in "crypto" frames, and must be produced or consumed in the specified epoch.

In the noise case, it seems that we will only have two epochs: Initial, and 1RTT. If I understand correctly, Noise does not support 0RTT, so no 0RTT epoch, and Noise does not convey the rich set of server parameters, certificates and final message of TLS, so no "handshake" epoch.

I think you need to define a specific version number for Noise, so the packets can be processed properly. In that version, the content of "crypto" frames in handshake packets will be passed to Noise for processing. So we get:

* Noise formats a client request message.
* That request is sent by Picoquic as a series of frames in as many Initial packets.
* The server side receives the Initial packets and passes the content to Noise.
* At some point Noise decides that the message is complete, processes it and formats a response message. At that point, Noise may do a callback to picoquic to provide the master secret, and the server MAY start sending 1 RTT packet. (Cautiously, because possible MITM?)
* That response is sent by Picoquic as a series of frames in as many Initial packets.
* At some point Noise decides that the message is complete, processes it and formats a final message. Noise also does a callback to picoquic to provide the master secret, from which picoquic will derive the AEAD key.
* The picoquic client sends application frames in 1 RTT packets. It sends the client's "final" message as a crypto frame in an 1RTT packet.
* The server receives the 1RTT packets and passes the "final" message to Noise. In classic QUIC, the server would send a "handshake done" frame to the client, to mark "all clear".

**Comment by huitema** [comment]
By the way, you have to be careful with "there is exactly 1 client->server packet, and 1 server->client response". Packets do get lost, so we have to repeat them. Also, a QUIC datagram has a payload of about 1200 bytes. That's big compared to current ECDH/ECDSA keys, but post quantum keys will be larger than that.

**Comment by rsepassi** [comment]
Thanks for entertaining this. I switched over to using ngtcp2 because it already had a factored out crypto layer, so it'll be a more straightforward testbed to swap the handshake, or more invasively dumb-out the crypto and wrap it in Wireguard or similar. I think if/when picoquic gets a similar crypto API, it'd be fairly straightforward to add a Noise-based crypto-provider if it was interesting to you.
