### ISSUE TITLE
0RTT packet not repeated after reset

### ISSUE THREAD

**Issue by huitema** [private-octopus/picoquic#189]
And they should be. Observed that in such cases the demo client stalls.

**Comment by bkchr** [comment]
Which size does the 0RTT package has?

**Comment by huitema** [comment]
It is a regular packet. The content size is in one of the attributes of the packet. There could be several such packets if allowed by the initial flow control window.

The bug happens because the retransmit queue is emptied upon processing of the stateless retry packet. But just leaving the 0rtt packets in the queue is not enough -- there is some kind of second order effect that needs fixing too. 

My plan is to write an unit test to repro the issue, and then make sure it stays fixed.

-- Christian Huitema

**Comment by bkchr** [comment]
Okay. I saw some different bug I think, a 40byte package was repeated infinitely and I had to restart the application.

**Comment by huitema** [comment]
If you have repro steps, please file a bug

**Comment by bkchr** [comment]
The problem is, that I can not reproduce it at the moment :(

**Comment by huitema** [comment]
Fixed, see PR #195
