### ISSUE TITLE
Travis build has stopped working.

### ISSUE THREAD

**Issue by huitema** [private-octopus/picoquic#191]
I tried subscribing to the service, but nothing happens. @bkchr : can you take a look?

**Comment by bkchr** [comment]
I tried it, but I don't have any rights. I think that @alagoutte is right, you maybe need to check with your `private-octopus` account. 
If you maybe give me rights to access the config sections of the repo, I could look at it.

**Comment by private-octopus** [comment]
I checked the configuration. It doe say that Travis is enabled. But when I go to the Travis site proper, it does not list any enabled project for private-octopus, and asks for $39 per month subscription. I find that a bit much, but I suppose I should just pay for it & deduce it as a business expense. After all, these guys certainly do need to finance their service.

**Comment by private-octopus** [comment]
Hum. There is some kind of confusion between "travis-ci.com", which wants $69 per month, and "travis-ci.org", which is free for open source projects. The transition or split between the two may have caused a glitch.

**Comment by huitema** [comment]
I think I fixed it by setting the proper parameters in the "travis-ci.org" web site. It appears to be working now.
