### ISSUE TITLE
Redesign wake time computation

### ISSUE THREAD

**Issue by huitema** [private-octopus/picoquic#201]
The scheduling is based on the computation of an "earliest wake time" for each connection. The wake time is updated when a packet is received, if the user submits or consumes data, or if the previous wake time is elapsed and a new packet preparation is attempted.

The wake time is computed based on a series of events that could cause packets to be sent: possible retransmission, need for acknowledgement, urgent packets queued, data ready, or flow control update. This should work, but there is a problem with the implementation. If the computation of wake time does not exactly match the sending logic, then we can get in an infinite loop in which the sending logic sends nothing, but the wake time says something should be sent. The server becomes then completely unresponsive.

We need to find a simple solution to eliminate this risk of hot loops.

**Comment by bkchr** [comment]
I think that I also observed this behavior several times. 

But I don't have any idea on how to tie the wake time computation with the sending logic, without making the code unreadable :( Any ideas on your side so far?

**Comment by huitema** [comment]
I am thinking having as much common code as possible. Also, We could impose some rule such as always enforce a minimum wait time increase after a transmission attempt.

But the stress test did help rooting out several bugs, so there is hope.

**Comment by huitema** [comment]
The last remnant of the old way are removed in PR #426
