### ISSUE TITLE
Cannot build on linux

### ISSUE THREAD

**Issue by mimoo** [private-octopus/picoquic#202]
Hello,

I'm trying to build this on Linux and I have compile errors:

First `u_short` doesn't exist for me, had to rename these to `unsigned short` manually. Then:

```
picoquic/picosocks.c: In function ‘picoquic_recvmsg’:       
picoquic/picosocks.c:255:81: error: dereferencing pointer to incomplete type                                                                         
                     ((struct sockaddr_in*)addr_dest)->sin_addr.s_addr = pPktInfo->ipi_addr.s_addr;                                                                               
```

**Comment by bkchr** [comment]
Which compiler and distribution did you use?

**Comment by mimoo** [comment]
I'm using Ubuntu and I tried with both clang version 3.6.0-2ubuntu1 and gcc version 4.9.2

**Comment by bkchr** [comment]
Which Ubuntu version?

**Comment by mimoo** [comment]
Oups sorry, Ubuntu 15.04

**Comment by bkchr** [comment]
If you provide a pull request, I would merge that. :)

**Comment by huitema** [comment]
I am looking at the original comment and I am a bit puzzled. Both sin_addr (left) and ipi_addr (right) are defined as "struct sockaddr_in". The error message points to an incomplete type, and that would be "struct sockaddr_in", which seems strange. I don't see why there is an u_short involved there. Any explanation?

**Comment by mimoo** [comment]
(btw, using 18.04 now and it compiles fine)

**Comment by bkchr** [comment]
Yeah, I expected that, because I also use Linux and it worked before ;) But we still should merge my pull request.
