### ISSUE TITLE
Refactoring frame skip and decode function interfaces

### ISSUE THREAD

**Issue by igorlord** [private-octopus/picoquic#212]
As stated in #199, the current interface to frame skip and decode functions makes the code too verbose.  We have options.

The proposed interface #199 (see below) was deemed too complex.
```
err <- skip_fn(uint8_t** pbytes, uint8_t* max_bytes)
err <- decode_fn(picoquic_cnx_t* cnx, uint8_t** pbytes, uint8_t* max_bytes)
```

Here is another proposal that is also concise.  Here, we return new bytes.  Errors are indicated by return of NULL (no separate error code).  Besides being concise, it ensures that processing will NOT continue after a failure.
```
uint8_t* <- skip_fn(uint8_t* bytes, uint8_t* max_bytes)
uint8_t* <- decode_fn(picoquic_cnx_t* cnx, uint8_t* bytes, uint8_t* max_bytes)
```

I'd appreciate feedback before I go ahead and create a PR to change a bunch of code.

**Comment by huitema** [comment]
I am just boarding a plane right now, will come back to you after landing tonight

**Comment by igorlord** [comment]
Bon voyage!

**Comment by huitema** [comment]
I like the proposal -- if ((x == decode(x, xmax, &err_detail,...))==NULL) { process error}.
I think it is a reasonable compromise between speed and reliability.

**Comment by igorlord** [comment]
Thanks.

One thing, I looked at all decode() and skip() functions, and I could not find the need for err_detail. Everywhere decode() sees an error, it just calls protocol error and returns the same error code. Skip just returns -1. There seems to be no informational content in err. That's why my proposal did not have err or err_detail.

(I am driving to NY this weekend, but next week I should have some time for this.)

**Comment by igorlord** [comment]
Closing via #222
