### ISSUE TITLE
Cleaning up stream flags -- state reduction

### ISSUE THREAD

**Issue by igorlord** [private-octopus/picoquic#214]
I am confused about the amount of transport state flags for streams.

It seems that *_signalled flags can all be removed, since there is already a "received" flags.  The code logic should always be:
```
if ((flags & foo_received) == 0) {
    flags |= foo_received;
    ....
    call callback();
}
```
So if the received flag is set, the callback has been called.  No need to ponder the meaning of cases where one flag is set but the other is not.

I am also a bit confused about the meaning of "fin_noftified".  Is it "application closed the sending part of stream"?  If so, should it be "fin_requested" for consistency with other flags?

**Comment by huitema** [comment]
Fixed with PR #410
