### ISSUE TITLE
Maintaining latest_progress_time

### ISSUE THREAD

**Issue by igorlord** [private-octopus/picoquic#218]
I do not understand the logic behind maintaining "latest_progress_time".

It is updated when a frame is successfully decoded, but only if the frame requires an ACK.
Why is there such a relationship between ACKs and the notion of "making progress"?

**Comment by huitema** [comment]
The idea is to check for real progress, such as for example consuming data or receiving data. The inactivity timer would fire even if the peer was in a loop sending acks but otherwise doing nothing.

**Comment by huitema** [comment]
@igorlord Do we need to keep this issue open?
