### ISSUE TITLE
Encryption issues - Header length 13?

### ISSUE THREAD

**Issue by aviaita4** [private-octopus/picoquic#304]
EVP_EncryptUpdate / EVP_EncryptInit in PicoTLS blows up
- I see that header_length was 13 whenever it blew up. In QUIC SPEC, 13 is not a possible header length. Is this a valid header length? / unexpected behavior? (I am using the same connection_id_callback as in picoquicdemo.c - same connection ID formatting)

Also, I have another question: Does picoquic invoke a close/application_close (reason 0) without communication parties actually invoking a picoquic_close?

**Comment by huitema** [comment]
13 is a fine length for a short header - 1 byte of type, 8 byte connection ID, 4 bytes of encrypted packet number.

**Comment by huitema** [comment]
Picoquic will close the connection in case of protocol error, after repeated transmission errors, or after a long period of inactivity -- 2 minutes currently. You can use the keep alive function to bypass the inactivity timer. The demo client uses a shorter timer at the application level.

**Comment by aviaita4** [comment]
> 13 is a fine length for a short header - 1 byte of type, 8 byte connection ID, 4 bytes of encrypted packet number.

Thank you for confirmation.
- Regarding my original question, 
  I observed (1 out of multiple encounters) that a packet of length 60 (13 bytes header + 47 bytes body)  is only encrypted for 47 bytes of body - upon which EVP_EncryptUpdate / EVP_EncryptInit in PicoTLS blows up.  Probably because the length should be multiple of block size? (I am new to this)
- In such case padding is done. Does picoquic handle this?

**Comment by huitema** [comment]
Picotls negotiates an AEAD mode of encryption, in which the length of the encrypted ciphertext is the length of the clear text + the length of of the AEAD checksum, typically 16 bytes. The 47 bytes body is composed of 31 bytes of encrypted clear text data and 16 bytes of checksum. When decrypted, you should get 31 bytes of clear text. No padding is required.

You say that "EVP_EncryptUpdate / EVP_EncryptInit in PicoTLS blows up". I don't think it is the encryption/decryption algorithm -- this uses OpenSSL underneath, and OpenSSL is rather well debugged. It looks like a memory corruption issue, either in your application or maybe in Picoquic. Have you tried running under debugger and analyzing the stack when it "blows-up"?
