### ISSUE TITLE
Demonstrate encrypted connection ID

### ISSUE THREAD

**Issue by huitema** [private-octopus/picoquic#305]
The default CID construct used in Picoquic demo code is designed to facilitate the work of a load balancer. The CID is 64 bits. Out of the 64 bits, N bits are fixed and designate a particular node in a server farm, and 64-N bits are picked at random.

This is purely demo code, and it could be replaced. It might be interesting to demonstrate use of encryption in constructing these CID. This may require using longer CID to benefit from modern ciphers.

**Comment by huitema** [comment]
@igorlord, @dbavatar : you added a default structure for connection-id that exposes the node number in clear text. I would like to offer an encrypted variant of that, but that would require selecting an encryption scheme + some way to synchronize keys between load balancer and servers. Any idea?

**Comment by igorlord** [comment]
For production, there will be a plug-in (callback) that has some specialized knowledge of where to take the keys from and how to generate the special encoding used by the load balancer.

For picoquicdemo, I think a simple AES encryption with a key given by the command line should do.  What do you think?

**Comment by huitema** [comment]
Actually, there are known good ways to create modern ciphers with arbitrary lengths. The key is the FFX construct first defined by Paul Rogaway. This is effectively a Feistel cipher in which the confusion box is implemented using a strong cipher, e.g. AES. Studies show that 6 passes suffice to provide good resistance. Check https://en.wikipedia.org/wiki/Format-preserving_encryption for quick description and references.

I think this is useful, because the 16 bytes CID creates a sizable overhead on all packets. 6 passes means "six times slower than AES", but that's probably OK for the low volume of CID operations -- trading off some CPU for better transmission efficiency.

**Comment by huitema** [comment]
I went ahead and submitted an implementation of FFX in PR #517. This would allow encryption of arbitrary length CID. I could add a demo of that in picoquicdemo, but it only make sense if done in collaboration with load balancer. The design would be:
```
CID: 8*L bytes
Decrypted CID:
 * N bits either set at random or copied from remote CID.
 * V bits static, identify for example server in a farm
 * 1 bit key phase.
Total N + V + 1 = 8*L

Encrypted CID: 8*L bytes
 * 8*L-1 encrypted bits
 * 1 bit key phase.
```
The CID generation is done at the server, using mask, static value and encryption key set by configuration. The CID generation includes verifying that the CID is unique at the server, by testing against the local hash table. If the generation is from a random number, collisions are resolved by picking a different random number.

I don't know whether I should even try to handle collisions when the CID is generated by using bits from the remote CID. By the way, I am not sure that this option of using bits from the remote CID is practical; the Chrome clients and most small clients are likely to use NULL CID. @igorlord, @dbavatar Do you really need that option?

**Comment by huitema** [comment]
The other issue with the design is, how to handle the encryption key. It would have to be known by all servers in the farm. The "reset key" has the same requirement, so it is tempting to just use the reset key as encryption key. Or, if we are cautiously paranoid, have both derived from a master key using HKDF expansion.

**Comment by huitema** [comment]
Another argument for coupling reset key and CID key. Suppose that the server manages two reset keys, old and new. Packet arrives for an unknown CID. Which reset key do we use for the reset, the old or the new? If the reset key and CID keys are in phase, then we can use the phase bit in the incoming DCID to select the appropriate Reset Key!

**Comment by huitema** [comment]
So the logical case is for an API that provides both a CID and the associated Reset Secret, and does that in coordination with the load balancer.

**Comment by huitema** [comment]
In a mail to the QUIC list, Kazuho makes a good point on the relation between the CID key and STEK: _Because CID encryption key is a master key, I think it's beneficial to
rotate it rather frequently. The precedent that the servers have is
the TLS session ticket encryption key (STEK). My understanding is that
people generally try to generate a new STEK every day or so [1].
Considering the fact that the maximum permitted lifetime of a TLS
session ticket is 7 days, generating a new STEK once a day is fine,
because by retaining 8 keys it would be possible decrypt TLS session
ticket that was issued 7 days earlier._
That would mean reserving 3 bits in the CID to indicate the "stek epoch".

**Comment by huitema** [comment]
Implemented the CID generation per https://github.com/quicwg/load-balancers, which resolves this issue.
