### ISSUE TITLE
Provide API for Spin bit.

### ISSUE THREAD

**Issue by huitema** [private-octopus/picoquic#347]
There are discussions of making the spin bit dependent on some negotiation, e.g. by VN. We should have an API to allow third parties to submit their spin code, such as:

* Spin + Random,
* Spin + VEC
* Spin + loss detection
* Mock spin for privacy, e.g. every 100 ms at client.
* Random spin by server.

**Comment by ferrieux** [comment]
The code for spin+VEC being already there, you've got a pretty good idea of where to put the hooks;)
For spin+loss, please see https://github.com/private-octopus/picoquic/compare/master...ferrieux:master , which implements loss as "QR" (sQuare sequence+Retransmit)

**Comment by huitema** [comment]
Done in PR 355.
