### ISSUE TITLE
Improve debugging of transport parameter test

### ISSUE THREAD

**Issue by huitema** [private-octopus/picoquic#365]
A common error is caused by updating the table of versions without updating the macros used in the test vector. Consider having a specific test for that, with an explicit error message.

**Comment by ferrieux** [comment]
Maybe simpler and more generic: when something fails, just tell which test and vector is concerned, and which part fails (either different lengths, or the offset where divergence occurs, or even better an hex dump). This way, no need to go into gdb, which implies struggling wiith Cmake output (make.flag) to remove the "-O2" and get single stepping to work ;)

**Comment by huitema** [comment]
Added error messages as suggested by @ferrieux in PR #379
