### ISSUE TITLE
IPV6_PKTINFO not present on MacOS X

### ISSUE THREAD

**Issue by larseggert** [private-octopus/picoquic#48]
So compilation there fails now

**Comment by huitema** [comment]
We need that if using send msg, which we need to ensure replies are sent from the correct source address. Alternative would be to just use send from on Apple. Is there another alternative ?

-- Christian Huitema

**Comment by huitema** [comment]
Can you check whether the fix suggested here would work?

https://forum.nginx.org/read.php?29,273674,273674

-- Christian Huitema

**Comment by huitema** [comment]
@larseggert : I just updated the socket code to use the magic Apple flag that I found on the web for IPV6 PKTINFO. Can you try compile and tell me if it works?

**Comment by larseggert** [comment]
I can verify that it compiles, but not that it works
