### ISSUE TITLE
Missing initial when sending handshake with ConnectionClose + TRANSPORT_PARAMETER_ERROR

### ISSUE THREAD

**Issue by gjnance** [private-octopus/picoquic#485]
picoquic generates a handshake packet with a connection close frame (TRANSPORT_PARAMETER_ERROR) in response to an initial with invalid transport params, but it never sends a response to the initial with the rest of the crypto data required to decrypt the hs packet.

c654efd8a31b4792: Receiving packet type: 2 (initial), S0, Version ff000011,
c654efd8a31b4792:     <c654efd8a31b4792>, <0df5ad5554465505>, Seq: 0, pl: 1175
c654efd8a31b4792:     Token length: 0
c654efd8a31b4792:     Decrypted 1158 bytes
c654efd8a31b4792:     Crypto HS frame, offset 0, length 268: 010001080303ac5e...
c654efd8a31b4792:     padding, 886 bytes
[...snip...]
c654efd8a31b4792: 0.008440 : Connection established, state = 9, from length: 16
c654efd8a31b4792 : Client address: 127.0.0.1, port 27264
c654efd8a31b4792: Received SNI:
c654efd8a31b4792: Received ALPN: hq-15
c654efd8a31b4792: Received transport parameter TLS extension (51 bytes):
c654efd8a31b4792: Proposed version: ff000011
c654efd8a31b4792:     Extension list (45 bytes):
c654efd8a31b4792:         Extension type: 0, length 4 (0x0000 / 0x0004), 0000ffff
c654efd8a31b4792:         Extension type: 1, length 4 (0x0001 / 0x0004), 00100000
c654efd8a31b4792:         Extension type: 2, length 2 (0x0002 / 0x0002), 4000
c654efd8a31b4792:         Extension type: 3, length 2 (0x0003 / 0x0002), 000f
c654efd8a31b4792:         Extension type: 5, length 2 (0x0005 / 0x0002), 05a0
c654efd8a31b4792:         Extension type: 8, length 2 (0x0008 / 0x0002), 4000
c654efd8a31b4792:         Extension type: 7, length 1 (0x0007 / 0x0001), 14
c654efd8a31b4792: 0.008581 : Server CB, Stream: 0, 0 bytes, fin=5 (connection close)
c654efd8a31b4792: Sending packet type: 4 (handshake), S0, Version ff000011,
c654efd8a31b4792:     <0df5ad5554465505>, <4eee0241dd20d19e>, Seq: 0, pl: 25
c654efd8a31b4792:     Prepared 5 bytes
c654efd8a31b4792:     connection_close, Error 0x0008, Reason length 0

**Comment by huitema** [comment]
Closing since this appears fixed now.
