### ISSUE TITLE
Changes in draft-18

### ISSUE THREAD

**Issue by huitema** [private-octopus/picoquic#506]
In transport:
    * Stream-related errors now use STREAM_STATE_ERROR (#2305)
    * Endpoints discard initial keys as soon as handshake keys are available (#1951, #2045)
    * Expanded conditions for ignoring ICMP packet too big messages (#2108, #2161)
    * Remove rate control from PATH_CHALLENGE/PATH_RESPONSE (#2129, #2241)
    * Endpoints are permitted to discard malformed initial packets (#2141)
    * Clarified ECN implementation and usage requirements (#2156, #2201)
    * Disable ECN count verification for packets that arrive out of order (#2198, #2215)
    * Use Probe Timeout (PTO) instead of RTO (#2206, #2238)
    * Loosen constraints on retransmission of ACK ranges (#2199, #2245)
    * Limit Retry and Version Negotiation to once per datagram (#2259, #2303)
    * Set a maximum value for max_ack_delay transport parameter (#2282, #2301)
    * Allow server preferred address for both IPv4 and IPv6 (#2122, #2296)
    * Corrected requirements for migration to a preferred address (#2146, #2349)
In TLS:
    * Endpoints discard initial keys as soon as handshake keys are available (#1951, #2045)
    * Use of ALPN or equivalent is mandatory (#2263, #2284)
In recovery:
    * After Probe Timeout discard in-flight packets or send another (#2212, #1965)
    * Endpoints discard initial keys as soon as handshake keys are available (#1951, #2045)
    * 0-RTT state is discarded when 0-RTT is rejected (#2300)
    * Loss detection timer is cancelled when ack-eliciting frames are in flight (#2117, #2093)
    * Packets are declared lost if they are in flight (#2104)
    * After becoming idle, either pace packets or reset the congestion controller (#2138, 2187)
    * Process ECN counts before marking packets lost (#2142)
    * Mark packets lost before resetting crypto_count and pto_count (#2208, #2209)
    * Congestion and loss recovery state are discarded when keys are discarded (#2327)

**Comment by alagoutte** [comment]
You can look also the "TODO draft-18" item list for @wireshark https://github.com/quicwg/base-drafts/wiki/Tools

**Comment by huitema** [comment]
Looking at this change list, it seems that the only changes affecting the bits on the wire are:
1) STREAM_STATE_ERROR  - already implemented
2) Limit Retry and Version Negotiation to once per datagram -- already implemented
3) Set a maximum value for max_ack_delay transport parameter -- done in PR #514
4) Allow server preferred address for both IPv4 and IPv6 -- done in PR #514.

ALPN is a server configuration issue, and the "or equivalent" clause is ambiguous. The Picoquic client always provide an ALPN.

We already have code to not process the Initial packets when in Handshake or Ready state, so there is no point in actually discarding the Initial keys. We discussed this in Tokyo, and a better solution is supposed to arrive with draft-19.

The recovery recommendation are interesting, but I am notsure that they apply to our implementation.

**Comment by huitema** [comment]
Done in PR #514
