### ISSUE TITLE
Performance: picoquic_is_cnx_backlog_empty() is hot

### ISSUE THREAD

**Issue by hoang-tranviet** [private-octopus/picoquic#521]
Hello,

When benchmarking the latest picoquic on high bw - low latency link, I observed the throughput drop significantly (70-140Mbps) compared to a version in last August (~240Mbps).

perf report reveals the hot functions on the receiver:

```
41.49%--quic_client
|          
--27.58%--picoquic_is_cnx_backlog_empty
          |          
          |--22.47%--picoquic_skip_frame
          |          |          
          |          |--19.16%--picoquic_skip_ack_frame_maybe_ecn
```

When transferring large files, it seems the retransmission queue grows unstoppably. Then there's a lot of calls to picoquic_skip_ack_frame_maybe_ecn() (thousands per packet).

Meanwhile, the server is much lighter.

Hoang

**Comment by huitema** [comment]
Just for checks: for your message, it appears that the measurement is done over a direct link between two computers, one running `picoquicdemo` in server mode, and the other in client mode. Is that correct?

**Comment by huitema** [comment]
I think I understand what is happening. When doing a large transfer, the client sends a lot of acknowledgements and little else. The acknowledgements-only packets from the client do not trigger any ack from the server, and so the list of unacknowledged packets grows considerably on the client. Having that large queue on the client is not good. It occupies a lot of memory, and it causes scaling issue if some function has to walk the entire queue.

This is compounded by a coding mistake in the client. There are lines at the beginning of the client loop that try to limit the time the client will be waiting: a long time in the normal case, but a short time if the client is almost done. That's why the client calls `picoquic_is_cnx_backlog_empty()`. I can fix that part easily, but I want to also fix the "queue of acks" issue.

**Comment by hoang-tranviet** [comment]
> Just for checks: for your message, it appears that the measurement is done over a direct link between two computers, one running `picoquicdemo` in server mode, and the other in client mode. Is that correct?
Yes, the link is 1Gbps - 0.2ms

> The acknowledgements-only packets from the client do not trigger any ack from the server, and so the list of unacknowledged packets grows considerably on the client. Having that large queue on the client is not good.
I see, this is the generic problem of any QUIC implementation I think.

By the way, is there any built-in facility in picoquic for throughput measurement?
That would ease the benchmark process.

**Comment by huitema** [comment]
The management of flow control was fix after August. Before that, the client would have to send frequent MAX_DATA packets, which would trigger acknowledgements from the server. It does not need to do that so often now, but the side effect is that acknowledgements are less frequents. So there are three required fixes:

1) On the server, actually acknowledge some of the received acks. 

2) In the client, force an ack from the server if the queue builds up.

3) In the demo client, only call `picoquic_is_cnx_backlog_empty()` when it is really needed.

Looking at the "generating acknowledgements" section in the recovery draft (https://quicwg.org/base-drafts/draft-ietf-quic-recovery.html#rfc.section.4), I don't see a discussion of the ACK of ACK issue. The current sender behavior that never acknowledges ACK only packets appears conformant, even if that leads to long periods without any ACK. @hoang-tranviet, do you want to raise the issue in the QUIC WG?

**Comment by bkchr** [comment]
I think that I observed something similar.

Regarding `picoquic_is_cnx_backlog_empty`, isn't that called somewhere in picoquic automatically?

**Comment by huitema** [comment]
The function `picoquic_is_cnx_backlog_empty` is only used in test code or in UI code. It is not used by the protocol machine itself. In the demo client, it is used so the client can exit cleanly when everything is done, without waiting for a long timer. But right now it is called for every packet, and there is really no need to do that.

**Comment by huitema** [comment]
@hoang-tranviet _"By the way, is there any built-in facility in picoquic for throughput measurement?"_ Well, obviously you can divide data sent by time elapsed. Apart from that, there also an option in the code to generate a performance trace:
```
time, sequence, highest ack, high ack time, last time ack, cwin, SRTT, RTT min, Send MTU, pacing packet time(us), nb retrans, nb spurious, cwin blkd, flow blkd, stream blkd, 
11001, 1, -1, 11001, 11001, 15360, 250000, 0, 1252, 1, 0, 0, 0, 0, 0, 
11001, 2, -1, 11001, 11001, 15360, 250000, 0, 1252, 1, 0, 0, 0, 0, 0, 
32752, 2, 0, 32752, 11001, 17421, 21236, 21080, 1252, 1527, 0, 0, 0, 0, 0, 
32752, 2, 0, 32752, 11001, 17421, 21236, 21080, 1252, 1527, 0, 0, 0, 0, 0, 
32752, 3, 0, 32752, 11001, 17421, 21236, 21080, 1252, 1527, 0, 0, 0, 0, 0, 
33851, 3, 0, 32752, 11001, 17421, 21236, 21080, 1252, 1527, 0, 0, 0, 0, 0, 
...
```
I use it in tests to debug flow control and congestion control, but it is not exposed in the demo client or server. Ideally, this should follow some standard log format, but we are not there yet...

**Comment by huitema** [comment]
@hoang-tranviet I believe that the performance issue that you mentioned is solved in PR #522. Can you verify that? Thanks!

**Comment by hoang-tranviet** [comment]
> Can you verify that? Thanks!

@huitema Thanks for the info and patch set, please see my response in the PR.

> Looking at the "generating acknowledgements" section in the recovery draft (https://quicwg.org/base-drafts/draft-ietf-quic-recovery.html#rfc.section.4), I don't see a discussion of the ACK of ACK issue. The current sender behavior that never acknowledges ACK only packets appears conformant, even if that leads to long periods without any ACK. @hoang-tranviet, do you want to raise the issue in the QUIC WG?

I just checked the [transport draft](https://quicwg.org/base-drafts/draft-ietf-quic-transport.html#sending-ack-frames) and it does have a text about it:

> To limit receiver state or the size of ACK frames, a receiver MAY limit the number of ACK Ranges it sends. A receiver can do this even without receiving acknowledgment of its ACK frames, with the knowledge this could cause the sender to unnecessarily retransmit some data. Standard QUIC [QUIC-RECOVERY] algorithms declare packets lost after sufficiently newer packets are acknowledged. Therefore, the receiver SHOULD repeatedly acknowledge newly received packets in preference to packets received in the past.

I am not sure that this solution vs. yours which one is better, or we need both. QUIC is new to me.

**Comment by huitema** [comment]
@hoang-tranviet I believe that the performance issue that you mentioned is solved in PR #522. Can you verify that? Thanks!

**Comment by hoang-tranviet** [comment]
Yes, the throughput is now around 254 Mbps in my test, a bit higher than the August version.
Thanks.

**Comment by huitema** [comment]
Noted the comment in #522, "The throughput is now around 254 Mbps in my test, a bit higher than the August version." Closing the issue.
