### ISSUE TITLE
picoquicdemo server didn't receive anything

### ISSUE THREAD

**Issue by vunhatminh241191** [private-octopus/picoquic#602]
Hi,

I have a following issue after cloning picoquic and running picoquicdemo. My picoquicdemo client is showing some message like this 

`No root crt list specified, certificate will not be verified.
Opening stream 0 to GET /index.html
e3dcee1acaeb0636: Sending packet type: 2 (initial), S0, Version 50435131,
e3dcee1acaeb0636:     <e3dcee1acaeb0636>, <210fc338dcb6b896>, Seq: 0, pl: 474
e3dcee1acaeb0636:     Token length: 0
e3dcee1acaeb0636:     Prepared 454 bytes
e3dcee1acaeb0636:     Crypto HS frame, offset 0, length 450: 010001be03032bf5...

e3dcee1acaeb0636: Sending packet type: 5 (0rtt protected), S0, Version 50435131,
e3dcee1acaeb0636:     <e3dcee1acaeb0636>, <210fc338dcb6b896>, Seq: 0, pl: 729
e3dcee1acaeb0636:     Prepared 709 bytes
e3dcee1acaeb0636:     Stream 2, offset 0, length 7, fin = 0: 00040401000700
e3dcee1acaeb0636:     Stream 0, offset 0, length 30, fin = 1: 011c0000d1d7510b...
e3dcee1acaeb0636:     Stream 10, offset 0, length 1, fin = 0: 03
e3dcee1acaeb0636:     Stream 6, offset 0, length 1, fin = 0: 02
e3dcee1acaeb0636:     padding, 658 bytes

e3dcee1acaeb0636: Sending 1252 bytes to 127.0.0.1:4443 at T=0.000000 (58ac62885ca96)
Select returns 1205, from length 16
Local address updated
e3dcee1acaeb0636: Receiving 1205 bytes from 127.0.0.1:4443 at T=0.001845 (58ac62885d1cb)
e3dcee1acaeb0636: Receiving packet type: 2 (initial), S0, Version 50435131,
e3dcee1acaeb0636:     <210fc338dcb6b896>, <4a3bb2ee4df26bd7>, Seq: 0, pl: 190
e3dcee1acaeb0636:     Token length: 0
e3dcee1acaeb0636:     Decrypted 170 bytes
e3dcee1acaeb0636:     ACK (nb=0), 0
e3dcee1acaeb0636:     Crypto HS frame, offset 0, length 161: 0200009d03033e00...

e3dcee1acaeb0636: Receiving packet type: 4 (handshake), S0, Version 50435131,
e3dcee1acaeb0636:     <210fc338dcb6b896>, <4a3bb2ee4df26bd7>, Seq: 0, pl: 173
e3dcee1acaeb0636:     Decrypted 153 bytes
e3dcee1acaeb0636:     Crypto HS frame, offset 0, length 149: 0800006d006b0000...

e3dcee1acaeb0636: Receiving packet type: 6 (1rtt protected), S0,
e3dcee1acaeb0636:     <210fc338dcb6b896>, Seq: 0 (0), Phi: 0,
e3dcee1acaeb0636:     Decrypted 764 bytes
e3dcee1acaeb0636:     Crypto HS frame, offset 0, length 126: 0400007a000186a0...
e3dcee1acaeb0636:     NEW CONNECTION ID[1]: 0x25b543212b2fa110, 4ecca481049d050ec455342dff2c6707
e3dcee1acaeb0636:     NEW CONNECTION ID[2]: 0x92ef425fee1428f9, edce3847023eb2f117042133bdd2ca92
e3dcee1acaeb0636:     NEW CONNECTION ID[3]: 0x39f3a8c1f7fce6fb, 95c37cdbda85bacb7952853b62464586
e3dcee1acaeb0636:     NEW CONNECTION ID[4]: 0x0bf147c4f16bda7e, afafd7246e8e0c9d110227f3cde8ac68
e3dcee1acaeb0636:     NEW CONNECTION ID[5]: 0xe2caca861f19809b, e3ffbf77bee469c8d76837b44ef99a82
e3dcee1acaeb0636:     NEW CONNECTION ID[6]: 0x18fe445592d1ad7e, e19cec3de1aa09acaaca70ff7f9eb523
e3dcee1acaeb0636:     NEW CONNECTION ID[7]: 0x9deb7d5fbb8a7b4f, e29278dda4128c5452b85dae042e492f
e3dcee1acaeb0636:     NEW CONNECTION ID[8]: 0xc87081b10bef35d3, ed0ffc7e29de980860bdac7ee9d89dba
e3dcee1acaeb0636:     Stream 3, offset 0, length 7, fin = 0: 00040401000700
e3dcee1acaeb0636:     Stream 0, offset 0, length 396, fin = 1: 0140040000d9f400...
e3dcee1acaeb0636:     Stream 11, offset 0, length 1, fin = 0: 03
e3dcee1acaeb0636:     Stream 7, offset 0, length 1, fin = 0: 02

Stream 0 ended after 386 bytes`

It is still processing all files that it needs, such as /text.html, file-123K, and so on. However, my picoquicserver didn't receive anything, does anyone know what is going on and how to fix it?

Thanks

**Comment by huitema** [comment]
Did you enable the log on the server side? They are not on by default. You could for example do:
```
.\picoquicdemo -l log.txt -p 4433
```
Which will launch the server with default options, listen on port `4433` and log data on `log.txt`

The log is written asynchronously, so there may be a small delay before the data appears on the server side. If you just want to look at 1 connection, something like:
```
.\picoquicdemo -l log.txt -p 4433 -1
```
will automatically close the log and end the server after one connection.

**Comment by vunhatminh241191** [comment]
I am enable that log like you suggest, and here is the log file
[log.txt](https://github.com/private-octopus/picoquic/files/3273215/log.txt)

I saw an error about Length 0, like this 
![Screen Shot 2019-06-10 at 11 08 57 AM](https://user-images.githubusercontent.com/3871672/59216323-3dbe7200-8b70-11e9-8da5-295368c42563.png)

**Comment by huitema** [comment]
@vunhatminh241191 I am looking at your log. The server receives the request for a doc on stream 0 at T=0.004789, replies immediately in 1RTT packet #2, which is acknowledged by the client at T=0.005613. Then the server receives a request to close the connection from the client at  T=0.005668. This would be consistent with a client asking for exactly one document, as in:
```
./picoquicdemo -l client_log.txt -a h3-20 -v ff000014 ::1 4433 /
```
Is that what you are doing?

**Comment by vunhatminh241191** [comment]
Hi I am using 
`./picoquicdemo -l - -L -v ff000014 localhost 4433`

however, I tried to use your command but this is nothing happened.
Here is the log of server and client
[client_log.txt](https://github.com/private-octopus/picoquic/files/3274119/client_log.txt)
[log.txt](https://github.com/private-octopus/picoquic/files/3274120/log.txt)

**Comment by huitema** [comment]
The client log looks fine. Upon successful completion, the client should have created some ".html" files in the local directory. Do you see them?

**Comment by vunhatminh241191** [comment]
I saw some html such as index.html and test.html

**Comment by huitema** [comment]
@vunhatminh241191 if you see the files in your working directory, it means that the server sent them and the client received them. I don't know then why you said that "the server received nothing." The server will not by default display anything when it processes a command, that's expected. The only traces will be on the log file.

On the client side, I suggest that you use the command:
```
./picoquicdemo -l client_log.txt -L -v ff000014 localhost 4433
```
That way, the client messages that show the progression of the session will not be mixed up with the log messages. Looking at this messages will quickly show whether the client works well or not.

**Comment by huitema** [comment]
@vunhatminh241191 Reading back this tread, it seems that client and servers were working as expected, but that this "expected" way was surprising for you. I assume that if it surprised you, it will surprise many other people as well. Should we write a wiki page about that? What would you like to find there?

**Comment by vunhatminh241191** [comment]
I think what I expected is the client will bring something to me for example
Get /index.html 
<html> ... </html>
and the server log file will show the connection between my client and server. I think you are right, my expectation is different with what picoquicdemo actually did.

**Comment by huitema** [comment]
Closing the issue.
