### ISSUE TITLE
Source code formatting

### ISSUE THREAD

**Issue by bkchr** [private-octopus/picoquic#61]
Hi, currently the code is not consistent formatted. Would you be open for a pull request that formats all the code in an uniform way? Maybe with `clang-format`.

**Comment by huitema** [comment]
I have no issue with that. Now is in fact a good time, as there are no urgent bugs in the queue. Please make sure that you run all the tests after doing the formatting, just to be on the safe side.

**Comment by huitema** [comment]
This is solved by PR #66
