### ISSUE TITLE
Satellite: encode latency and bandwidth in ticket or token, remember at client side

### ISSUE THREAD

**Issue by huitema** [private-octopus/picoquic#651]
The HTTP spec says:

_When a 0-RTT QUIC connection is being used, the initial value of each server setting is the value used in the previous session. Clients SHOULD store the settings the server provided in the connection where resumption information was provided, but MAY opt not to store settings in certain cases (e.g., if the session ticket is received before the SETTINGS frame). A client MUST comply with stored settings - or default values, if no values are stored - when attempting 0-RTT. Once a server has provided new settings, clients MUST comply with those values._

On the client side, this implies remembering an application setting frame and storing it together with the session token. On the server side, this implies either always reusing the same parameters, or alternately encoding the value of the parameters in the session ticket. Or, possibly, using some other alternative, such as setting identifiers.

In any case, this requires providing an API for optionally setting initial application parameters in tickets and retrieving them on the server side, and possibly a similar API on the client side for storing information with tickets and retrieving it.

**Comment by huitema** [comment]
Confirmed that resumption tickets are for SNI+ALPN.

**Comment by jlaine** [comment]
What kind of API are you imagining on the client side? Being able to pass in a single arbitrary binary blob of settings, and getting it handed back on session resumption?

**Comment by huitema** [comment]
@jlaine revisiting this issue. The initial motivation was the satellite work, in which there is a lot to be gained if the resumed connection can start with the right congestion control parameters. This would require knowledge of:

* observed bandwidth in previous connection
* observed RTT in previous connection
* date of last connection, because the older the measurement the less trust in them
* IP address of last connection, because measurements are only valid for some given network path

The client could place these data in a transport parameter, but that opens a can of worms. What if the client is hostile? What if it is trying to DOS a remote network? It seems safer to have the server place that data in an encrypted blob, which could be either the "session resume ticket" or the "retry token". Of these two, the retry token seems like a better fit, because its content is entirely managed by the Quic stack, rather than exported through TLS. Also, the format of the token is entirely defined by the implementation, and the implementation can send it whenever it wants.

So the design would be:

1) Add some fields in the encrypted token
2) Delay sending the NEW TOKEN frame until RTT and bandwidth have been measured
3) Send the NEW TOKEN then, even if the server is not using Retry for protection
4) On incoming connection, pass the estimated RTT and Bandwidth to the CC algorithms

**Comment by huitema** [comment]
Fixed.

**Comment by huitema** [comment]
Should analyze whether this is better done as an extension of tickets or tokens, or as a separate element. Tickets and tokens are usually prepared during the initial handshake, and there is only limited information available then. It might be better to just use the Quic extension mechanism, defining:

1) Transport parameter for `path information`
2) Frame for `new path information`

To prevent abuse, the parameter should probably be encrypted, or at least signed. It could contain:

* measured RTT min
* max bandwidth observed
* path MTU validated

There also need to be a time to live, and also the source and destination address. These should probably be exposed to both parties, to the server for validation, and to the client for selecting the right token when many are available.

**Comment by huitema** [comment]
This issue is addressed in Pr #1204
