### ISSUE TITLE
Rust bindings

### ISSUE THREAD

**Issue by bkchr** [private-octopus/picoquic#68]
Hi,
I just wanted to inform you, that I created rust bindings for your library. My repository can be found here: https://github.com/bkchr/picoquic-rs

I hope that is okay for you :)

**Comment by huitema** [comment]
Of course that's OK. In fact it is great.

I will document the rust bindings in the README.

The only issue is that since Picoquic is still a work in progress, the API is pretty much guaranteed to change over time. You will have to update the bindings as it does. But I guess you know that already!

**Comment by bkchr** [comment]
Yeah, I'm aware that the api will break :)
