### ISSUE TITLE
Evented I/O (EPoll, Kqueue, IOCP)

### ISSUE THREAD

**Issue by vijayee** [private-octopus/picoquic#705]
I'm trying to make bindings for ponylang to this library and I've noticed that the native network stack for pony is using I/O Event libs that don't block the thread when waiting for connections  in udp/tcp. Does this library block the thread when waiting for connections? Is it using an event library under the hood? If not I'd like to make enhancement so that it will mesh better with the pony ecosystem.

**Comment by huitema** [comment]
The library does not block, and is in fact designed to integrate with an eventing system. It consists of a set of API that could be activated upon events -- packet arrivals and timers. The demo client and server are implemented by using socket events to call the API, but this is "on top" of the API, and could be easily replaced in your pony integration.

The picoquic library is single threaded. The implementation uses a context object (type `picoquic_quic_t) and expect that the environment will interact with that object. There are four main points of interaction:

* The "packet receive" API which is called when a packet has been received on one of the UDP sockets, or by whatever other mean is available.

* The "packet prepare" API which should be called regularly and the next packet to be sent if one is ready

* The connection level API that let applications start and close connections, or push data to a connection.

* The callback API by which the stack informs the application about connection events and data arrival. The call back API is normally activated by a call to the "prepare" API.

These API execute as C functions. The "single threaded" restriction means that only one of these functions should be executing at a given time.

The "receive" an "prepare" API take a "current_time" parameter, which is how the stack learns about the time. In the test environment, we use that to run tests in "virtual time". The stack maintains a "next wake up time", which is updated after each call to one of the API functions.

For the pony ecosystem integration, the first step would be to call the API function upon events integrated with your system.

You may want to look at the "quicwind" project in the Windows solution. It is an example of running the picoquic library in a background thread, while the application itself executes in the foreground.

**Comment by vijayee** [comment]
Thanks, I'll take a look at your quicwind solution.

**Comment by bkchr** [comment]
I have an implementation with picoquic and epoll for Rust. So, yes it is possible :)

**Comment by vijayee** [comment]
@bkchr could you link to your code?

**Comment by bkchr** [comment]
https://github.com/bkchr/picoquic-rs

**Comment by vijayee** [comment]
@bkchr thanks. What are you using this binding to create?

**Comment by bkchr** [comment]
The bindings between Rust and C? For that I use `rust-bindgen`.

**Comment by huitema** [comment]
@vijayee are you waiting for more information, or can we close this issue?

**Comment by vijayee** [comment]
You may close this issue
