### ISSUE TITLE
cannot connect using two servers

### ISSUE THREAD

**Issue by Winters123** [private-octopus/picoquic#739]
Hi,
I installed `picoquic` on two servers with IP 192.168.0.1 and 192.168.0.2.
I lunched `picoquicdemo` as a server with `./picoquicdemo -p 5566 192.168.0.1` and another as a client with `./picoquicdemo 192.168.0.1 5566`. But seems the two cannot be connected together and both exit with error msg like this:
```
Starting PicoQUIC connection to server IP = 192.168.0.1, port = 5566
Testing scenario: <0:index.html;4:test.html;8:/1234567;12:main.jpg;16:war-and-peace.txt;20:en/latest/;24:/file-123K>
No server name specified, certificate will not be verified.
Received a request to close the connection.
Client exit with code = 1044
```
Am I doing something wrong?

**Comment by huitema** [comment]
The server launch command is wrong. Try using just `./picoquicdemo -p 5566`

**Comment by Winters123** [comment]
the cmd you suggested works for me. Thanks for it!
But as a user, I suggest it would be better to let users specify the NIC address as we may have multiple NICs (so different addresses) on the same server. Not sure if it makes any sense.

Cheers,

**Comment by huitema** [comment]
@Winters123 sure. I don't have time to do that right now, but if you have a PR...

**Comment by Winters123** [comment]
Yep, willing to help :)

**Comment by huitema** [comment]
Considering this as non-repro.
