### ISSUE TITLE
Basic multipath

### ISSUE THREAD

**Issue by huitema** [private-octopus/picoquic#74]
Once we have PN encryption and basic migration, the main task left for multipath is packet scheduling along multiple paths, possibly tied to "coordinated congestion control".

**Comment by huitema** [comment]
There are a few tasks linked to "multipath", and differences with the current version:

1) Scheduling path different from path[0] for data transmission.
2) Write a multipath congestion controller that sends an appropriate fraction of traffic on each path.
3) Set up multipath simulator.
4) Write socket code that handles addresses as they appear on the system.
5) Specify a way to negotiate multipath function between peers.
6) Include time stamp option for computing RTT.

The options, and the changes to the basic Quic V1 spec, will need to be stated in a draft.

**Comment by huitema** [comment]
The multipath simulator is also useful to resolve option #320, make before break migration, because that too requires multiple simultaneous paths.

**Comment by huitema** [comment]
The implementations of congestion control rely on an estimate of packet loss rates. The current estimator assumes a single packet sequence and thus in practice a single path. This will have to be fixed for multipath.

**Comment by ytxing** [comment]
Hey, is multipath usable now?

**Comment by huitema** [comment]
@ytxing The spec is ready. I need to get 3 or 4 quiet days to implement that properly. Do you want to help me with implementation or test?

**Comment by ytxing** [comment]
@huitema I am happy to test some multipath functions, especially some 'coupled congestion control' and 'scheduling' functions. Since I am not familiar with qicopuic implementation, I will not try to mess things up with my codes. :)

**Comment by huitema** [comment]
Fair enough. I am going to put this multipath work up in the priority list, but it will take a bit of time.

**Comment by ytxing** [comment]
Great,  looking forward to it.

**Comment by huitema** [comment]
Very first basic multipath version has been implemented in PR #1108 . The unit tests are passing, but this is clearly very rough. Further work is needed for compliance with the draft.
