### ISSUE TITLE
Control of RTC vs ACKs

### ISSUE THREAD

**Issue by huitema** [private-octopus/picoquic#740]
Copying here a discussion that started as  comments on PR #738 -- since the PR is closed.

@steschu77 asked whether the "ACK time stamp" implemented in PR #768 was an official QUIC extension (No, not yet), and whether it was meant for real time communication (No, it was meant to better control transmission on high bandwidth*delay connections).

The issue of how to do RTC in Quic is interesting. There are two approaches:

1) Use the "Datagram" extension and carry the real time frames in datagrams, much like they are carried in RTP -- in fact, this leads to "encapsulate RTP in Quic"
2) Use special versions of Streams, adding delimitation of frames within a stream and some tolerance for "gaps" in the stream when packet losses cannot be corrected quickly enough to meet RTC constraints.

Picoquic should allow experimentation with both approaches. We already supports datagrams, so the first part is easy. The stream approach is not supported yet -- we did define a "gap" callback code, but there is no actual code behind it. There is probably more work to do than just allow gaps in streams -- large video "I" frames are often protected with per frame FEC, because losing them means losing large chunks of video. We will need to study how to accommodate that too.

There is a related control issue. End-to-end RTC control requires monitoring end to end delivery delays,reacting to congestion, etc. It is unclear whether that should be merged into the generic ACK format and exposed to the application through an API, or implemented as part of application level protocols.

**Comment by steschu77** [comment]
I did some research of how to do video in QUIC some time back. I found that there are two general approaches which Christian pointed out as 1) and 2) already. It turns out that these two approaches are the answers to the question of who is in charge to compensate packet loss.

Approach 1) is the answer if receiver driven loss compensation is desired. Using per stream sequence numbers and frame markings, ad actually also the referencing schema, a receiver would be able to detect loss, decide when or if further received video data can be decoded and feed the decoder accordingly.

Approach 2) relies on the sender to use the "gap" signaling to tell a receiver to ignore certain data that has been lost. No per stream sequence numbers nor the referencing schema would be necessary in this approach.

As for congestion control, a mechanism is desirable that allows fast bandwidth drop detection. The current idea is to have per-packet receive time-stamps transmitted to the sender similar to [rtp-cc-feedback](https://tools.ietf.org/html/draft-ietf-rmcat-rtp-cc-feedback-05).

See the following attached PDF for more details:
[QUICVideo.pdf](https://github.com/private-octopus/picoquic/files/3948110/QUICVideo.pdf)

**Comment by huitema** [comment]
@steschu77 I am reading your paper on video over Quic. I actually implemented something like that as part of video conferencing experiments at Microsoft, about 10 years ago. The main difference is that we were using N+P FEC, where N was the number of packets necessary to carry a video frame, and P was the redundancy level required to meet the quality of service. We were trying for high definition, I-Frames could be 30 to 60KB long, and as you know losing one would prevent receiving the subsequent interpolated frames. We ended up with schemes like 20+4 or 40+6, using the same kind of redundancy code also used in Skype.

There may well be another way than regular stream or datagrams. Nothing prevents us from creating a new set of frames specifically for "video streams", and try to get the exact best fit. This might actually be easier than trying to shoehorn video communication in a stream concept defined mostly for HTTP pages.

As for congestion control, I am reading Colin's RFC. He does design an RTP/RTCP specific congestion layer, but part of the reason is that he has to -- there was no such thing in the original RTP/RTCP. Thierry Turletti and I experimented with similar feedback for H.261 over UDP; see RFC 2032, and also our ACM paper (https://www.semanticscholar.org/paper/Videoconferencing-on-the-Internet-Turletti-Huitema/a4092d119cb3de6fb654fe490859a38c9c817c08) that developed the concept of "an output rate control scheme that adapts the image coding process based on network conditions." That was in 1992-1993, so of course we can do much better now!

In any case, the whole point of congestion control algorithms is to react quickly to change in network conditions. If we run video over Quic, we can use the mainstream congestion control algorithm, BBR in particular, and provide an API to indicate changing network conditions to the application. Of course, we already have an API in Picoquic to plug in alternative CC algorithms, so we can try experimenting with new algorithms as well.

**Comment by steschu77** [comment]
Experimentation around real-time video transmission using QUIC is the reason why I am using picoquic. :) It provides the right level of adaptability required for experiments.

The whole topic of how to do real-time video is very manifold as you can see in the linked PDF. With picoquic I want to answer the questions of how to deal with loss and limited bandwidth. I want to look into adaptive re-transmission (re-transmissions of lost data that give up after a timeout), FEC, and congestion control algorithms.

I am currently building a testbed for the experimentation and therefore don't do changes in picoquic itself. Instead, I try to monitor all related work like the one-way delay measurement.

**Comment by huitema** [comment]
OK. If changes are required, such as new API, I am willing to help. Turns out that the "partial reliability" work is specifically excluded from the Quic WG charter, so we won't get a standard for that any time soon. But you can certainly work with existing concepts, e.g. reset stream in case of missing data, or use datagrams. In the case of datagrams, we may want some performance work to couple datagrams and video production.

**Comment by huitema** [comment]
@steschu77 The topic has been addressed with addition of path quality APIs, real time scheduling per path, and generally the IETF effort on [media over QUIC](https://datatracker.ietf.org/wg/moq/about/). We also have an experimental "unreliable stream" API in Picoquic:
```
typedef int (*picoquic_stream_direct_receive_fn)(picoquic_cnx_t* cnx,
    uint64_t stream_id, int fin, const uint8_t* bytes, uint64_t offset, size_t length,
    void* direct_receive_ctx);

int picoquic_mark_direct_receive_stream(picoquic_cnx_t* cnx,
    uint64_t stream_id, picoquic_stream_direct_receive_fn direct_receive_fn, void* direct_receive_ctx);
```
Do we need to keep this issue open?

**Comment by steschu77** [comment]
I am fine with closing this issue.
