### ISSUE TITLE
Not decoding STOP_SENDING correctly

### ISSUE THREAD

**Issue by kenmcmil** [private-octopus/picoquic#783]
Picoquic is not decoding STOP_SENDING frame correctly. Here is the relevant code in frames.c in function `picoquic_decode_stop_sending_frame`, line 747:

```
if ((bytes = picoquic_frames_varint_decode(bytes+1, bytes_max, &stream_id))  == NULL ||
        (bytes = picoquic_frames_uint16_decode(bytes,   bytes_max, &error_code)) == NULL)
```

This decodes the error as a uint16, but according to draft 23 it should be a variable int. The same problem occurs in `picoquic_prepare_stop_sending_frame`.

**Comment by huitema** [comment]
Thanks, Ken. Will fix that asap.

**Comment by huitema** [comment]
@kenmcmil This is getting fixed in PR 784.
