### ISSUE TITLE
picoquic_get_next_cnx infinite loop

### ISSUE THREAD

**Issue by bkchr** [private-octopus/picoquic#83]
Hi, I'm not aware if you know that. I was using `picoquic_get_next_cnx` to iterate over all connections. I was getting one connection per time and polled it if it wants to send new data. Now, I had multiple connections and they all wanted to be updated at the same time. This lead to a bug, that I infidelity looped over all connections, because they were reordered internally :(
Maybe you could add a warning or provide some sort of "stable" iterator.

I solved it now in rust in the following way. I create a stable list in beforehand and then I iterate over this list. My changes can be found here: https://github.com/bkchr/picoquic-rs/commit/7b4c69db4a55efc43d08841cf11836e5198caf20
Maybe they help to better understand what I want to say :)

**Comment by huitema** [comment]
Yes, I know some of the API need work. Give me a bit of time to write a test that reproes your bug. The list is managed by priority, which makes sense if you work one at a time, but clearly there are other patterns.

**Comment by huitema** [comment]
OK, after thinking about it, I think I can fix it that way:

* The connections are currently queued in the Quic context in the order of their next wake time.

* The queue is currently updated each time the wake time of a connection changes, which leads to loops or other issues in picoquic_get_next_cnx

* The proposed fix is to not update the queue in real time when the wake time changes, but only sort the queue when the application calls picoquic_get_first_cnx.

Will that pattern work in the Rust mapping?

**Comment by bkchr** [comment]
Yeah that could work. Currently I'm doing something similar and building the list beforehand. I run over all connections, collect them and then I iterate over my own list that does not change.

**Comment by huitema** [comment]
Solved by PR #101
