### ISSUE TITLE
picoquic_initialize_tls_stream should fail if no ALPN is provided

### ISSUE THREAD

**Issue by steschu77** [private-octopus/picoquic#868]
I am building a minimal picoquic client/server application. I noticed that to get the client connected to the server it needs to provide an ALPN. In my case only the server complains about the missing ALPN, which is difficult to find. It would be better if the client already returns an error during context initialization if no ALPN has been provided.

**Comment by huitema** [comment]
Yes, that's a good idea. We could fail the "create connection" call if the ALPN is absent.

**Comment by huitema** [comment]
@steschu77 please check PR #869, to see if it addresses your issue.
