### ISSUE TITLE
BBR's cwin increases indefinitely with a rwin-limited peer in SATCOM configuration

### ISSUE THREAD

**Issue by francoismichel** [private-octopus/picoquic#873]
Hello,

Using a high delay network configuration the congestion window provided by the satellite-flavoured BBR implementation seems to increase indefinitely when the peer has a small receive window. The algorithm never seems to leave the `picoquic_bbr_alg_startup_long_rtt` state.

Let's imagine that we are in a satellite use-case, that the BDP is 3MB and that the peer's receive window cannot exceed 1MB. In that case, BBR will enter in the `startup_long_rtt` phase (because of the large RTT) and will only get out of it when the RTT increases enough to make ´picoquic_hystart_test´ return 1. This is unlikely to happen due to the small peer's receive window: the bytes in flight will never reach the BDP (3MB) and threfore the RTT is not expected to deviate much. The congestion window will however continue to increase for every acked packet as we are in the `startup_long_rtt_phase`. 

The problem is that if the peer at some point annouces a larger receive window, the sender will send send at a very high rate, a lot higher than the actual bandwidth. I experienced this problem in our own fork of picoquic but the problem seems to remain here too. I think that experiencing configurations with a rwin peer having a buffer that is smaller than the BDP is a lot more likely to happen in the satellite use-case given the high BDPs that can be experienced.

I see two ways of fixing the problem :
- capping the congestion window to the peer's receive window. This looks complicated as the peer's receive window is distrubuted among all the opened streams so we have iterate through the streams to compute it
- implementing some form of congestion validation such as proposed in [RFC7661](https://tools.ietf.org/html/rfc7661) . This could in fact be proposed in `cc_common.c` as the other congestion control algorithms are also exposed to the problem. The problem is however already mitigated for the other algorithms as they still react to loss events.

What do you think of this ? Do not hesitate to tell me if I was unclear in the problem statement. I can also try to provide a PR if you do not have the time to look at it right now, but I prefer to have your opinion on the solution to adopt before proposing any concrete modification to picoquic. :-) 

(I also see no way in picoquic to limit the receive window of a peer, I guess this would be nice to have in order to experiment with such use-cases but this is another thing)

Regards

**Comment by huitema** [comment]
@francoismichel clearly this is a bug. The fix is obvious: do not increase the CWIN if the sender is not CWIN-limited. But as you said, we will not trust the fix if we cannot test it, and we can only test it if picoquic supports a form of limited window.

The current flow control behavior is designed to maximize throughput. The windows open exponentially, doubling in size each time half the window is consumed. In addition, the HTTP-3 client is designed to open the flow control windows by the length of the file if it requests a large file. I think of having a control flag to inhibit that behavior, and stick to an almost fixed window: if the window is half consumed, increase it by a fixed amount instead of the exponential behavior.

I don't know whether it is sufficient to treat this fixed window that as a test setup, or whether we need to expose it as a run time option. For now, I would prefer to just have a "fixed window" flag that can be set by the test tools. That would be enough to run the unit tests and verify the behavior.

**Comment by francoismichel** [comment]
@huitema Indeed, using something like `picoquic_cc_was_cwin_blocked` to avoid increasing the cwin blindly should do the trick, but should we also get out of this `picoquic_bbr_alg_startup_long_rtt` state at some point (e.g. once that `picoquic_cc_was_cwin_blocked()` returns `false`) ? I am not sure whether it is very important as the bandwidth is anyway driven by the receive window in such cases but I wonder what happens if the receive window suddenly grows.

>  I think of having a control flag to inhibit that behavior, and stick to an almost fixed window: if the window is half consumed, increase it by a fixed amount instead of the exponential behavior.

This is what I am doing for my flow control mechanism for the FEC extension. This is in fact how I noticed the bug we are talking about right now. :-)

> For now, I would prefer to just have a "fixed window" flag that can be set by the test tools. That would be enough to run the unit tests and verify the behavior.

Using a `fixed_window` flag is a great first step that will allow providing a fix rapidly. Allowing to configure a maximum window size would be an interesting next step to experiment with limited receive-buffers and high BDP networks.

**Comment by huitema** [comment]
Let's first define the test condition. I would define it as:

* Set the receiver's flow window to be a fraction of BDP, about 1/2 BDP
* Transmit at least 8*BDP worth of data
* Verify that the CWIN never exceeds 1/2 BDP by more than a few packets

For example:
* RTT = 600 ms
* Data rate = 1 Mbps
* BDP = 75KB
* Flow control window = 40 KB
* File size = 1 MB
* Expected duration: about 15 seconds
* CWIN max = TBD (less than 150KB)

That should be a good test that the CWIN is not overly increasing.

**Comment by francoismichel** [comment]
Looks good to me. :+1:

**Comment by huitema** [comment]
@francoismichel you may want to check PR #875. The fix was not quite as simple as I thought, but it does solve the issue.
