### ISSUE TITLE
BBR BBR_PROBE_RTT_INTERVAL is very long.

### ISSUE THREAD

**Issue by huitema** [private-octopus/picoquic#885]
It takes 10 second to detect that the RTT may have increased. That's quite long, making it mostly a safety valve for unpredictable routing events. Consider using some probabilistic logic to get out of the blockage sooner.

**Comment by huitema** [comment]
At the same time, this wait interval is not long enough on high delay links. On a "normal" link with an RTT of 100ms or less, the 10 seconds interval encompasses 100 RTT or more, which are as many chances of detecting a low RTT. On satellite links, 10 seconds is just about 16 RTT, which means that the chances of spurious transition to probe RTT state are much higher.

**Comment by adcen0107** [comment]
Where does the BBR implementation of picoquic come from ? the kernel or other open source quic project BBR implementation

**Comment by huitema** [comment]
@adcen0107 I developed it. First based on the publicly available IETF draft, then added extra processes on my own to fix issues found in deployment or simulations.

**Comment by huitema** [comment]
Probe RTT is an issue for applications like video streaming or real-time communication. It can cause the transmission to stall very 10 seconds, which is annoying. It would be very nice to find an alternate way to check the RTT Min without causing such stalls. It would also be nice to detect issues with RTT Min before waiting 10 seconds.

The main issue is the "latecomer advantage" also found with LEDBAT. If nodes sharing the same bottleneck do not get consistent estimates of probe RTT, the resource is not shared fairly.

In the "latecomer" case, the late comers start with a higher estimate of RTT Min. The consistent estimates only happen if usage is reduced for some time, so the global load becomes lower than the bottleneck bandwidth. The queue drains, and all nodes will observe the reduced RTT.

The other issue is RTT increase. BBR sets the CWIN to bandwidth*minRTT*2, so in theory as long as the actual RTT is not more than twice the actual RTT there is no problem -- but problems could still happen. High RTT can thus be due to overload and queues, or change of network conditions such as further away from base station. 

It would be nice if small frequent tests could detect the difference. The probe BW pattern is to increase BW by 25% for one RTT, then decrease for the next RTT in order to compensate, so as to detect throughput increases. The opposite pattern would be to decrease by 25% for one RTT, then increase by 25% to compensate. If the RTT decreases, this indicates the high delay was due to overload. If it does not decrease, it might indicate an RTT increase -- but we might need repeated tests to actually believe that.

**Comment by huitema** [comment]
The first step may be to add a "late comer" test. Such as:

* start a first connection.
* then start a second connection some time after on the same link.
* then verify that the two connections converge to similar data rates and RTT min estimates.

This will establish whether we have in fact a latecomer issue, and provide a test bed for assessing it.

**Comment by huitema** [comment]
Probably fixed in BBR v3.
