### ISSUE TITLE
picohttp-core depends on picoquic-core

### ISSUE THREAD

**Issue by larseggert** [private-octopus/picoquic#889]
picohttp-core depends on picoquic-core, since it uses `picoquic_add_to_stream`, `picoquic_varint_decode` and `picoquic_varint_skip`.

Is this intentional? Why break out picohttp-core into its own lib then?

**Comment by larseggert** [comment]
`picoquic_add_to_stream ` is only called from `h3zero_send_initial_settings`, which seems completely unused, but the other two are actual dependencies.

**Comment by huitema** [comment]
Picohttp-core depends on picoquic-core in more than one way. It also depends on the external API provided by picoquic-core for setting connections, pushing data or managing callback.

The library was broken out because some applications do need picoquic-core but do not need HTTP. And example would be DNS over QUIC. Another example would be applications that provide their own HTTP stack.

**Comment by huitema** [comment]
@larseggert of course, I don't know what you are trying to achieve. Reading between the lines, I wonder whether you are looking for a simple HTTP library that could be used on top of the Quant transport, or any other transport for that matter. That was not the initial goal for the picohttp library, but I can see that it might be interesting. But I would need to understand it a bit more.

The library "picohttp-core" has three big components: the H3 encoding (H3Zero), the demo client and the demo server. The client and the server have more dependencies on the Quic stack -- they have to start connections, answer to callbacks, etc. Are you interested in that, or just the H3 encoding?

**Comment by larseggert** [comment]
Sorry, I should have been clearer. I’m basically o my I retested in the h3zero functionality for my fake h3 test client.

**Comment by huitema** [comment]
So what you probably want is a clean h3zero lib, maybe in a separate project than Picoquic. A first step might be to create a separate lib in the picoquic project, and also to move the stack dependencies to the demo client and demo server. If you want to start a PR, you are welcome.

**Comment by huitema** [comment]
Actually, there may not be any need to separate the h3zero lib, as long as you do not link with the demo client or the demo server. From what you say, it may be sufficient to:

1) Move the calls to "send the settings" from H3Zero to the demo client and server,
2) Duplicate `picoquic_varint_decode` and `picoquic_varint_skip` as `h3zeo_varint_decode` and `h3zero_varint_skip` in h3zero.c.

Sounds easy enough.

**Comment by huitema** [comment]
@larseggert Can you review PR #891 ? Maybe compile the PR branch and see whether you can now just load the picohttp-core library?

**Comment by larseggert** [comment]
Thanks, I will test the PR later.

You could simply put the functions into a C file shared by the two libs instead of duplicating them, too.

**Comment by huitema** [comment]
Fixed.
