### ISSUE TITLE
Support new  aead fusion engine from picotls

### ISSUE THREAD

**Issue by huitema** [private-octopus/picoquic#954]
huitema  9:51 PM
@kazuho The fusion work looks very cool. If I understand properly, this code implements AEAD independently of openssl, and just uses the openssl implementation of AES ECB, allowing use a single context for AEAD and header protection. But I wonder what this does to the API. In particular:
9:52
Does that mean that for using fusion I need to replace calls to ptls_aead_new(), etc., with a fusion equivalent?

kazuho  9:53 PM
fusion does not use openssl at all. It has ptls_fusion_aes128gcm, ptls_fusion_aes128ctr that you can use.

huitema  9:54 PM
That's cool. What about chacha_poly?
9:54
Next question, what should I do for ARM builds?

kazuho  9:54 PM
Just aes-gcm for x86-64.
9:56
Basically, you can use the traditional AEAD API. In addition, a new API is provided: ptls_aead_encrypt_s which is a combined operation of AEAD+CTR.
9:56
When the underlying crypto engine does not support combined operation, picotls would issue AEAD and CTR operation separately.

huitema  9:57 PM
By CTR, do you mean the call to produce the encryption block for header protection?

1 reply
Today at 9:57 PMView thread

kazuho  9:57 PM
So the only changes required for using fusion is, use ptls_aead_encrypt_s, use &ptls_fusion_<ciphername> on x86-64.
9:58
https://github.com/h2o/quicly/blob/4c17e90129b1ac08ffd7142410e44e6633cbccf0/lib/defaults.c#L424-L433
9:58
This is the code that quicly will use.

huitema  9:58 PM
If I recall correctly, the header protection key does not roll on a key update. Does that mean that after a key update I have to roll back to the old API?

kazuho  9:59 PM
No, you supply one AEAD context and one CTR context to ptls_aead_encrypt_s
9:59
It's up to you to choose the correct pair.

huitema  10:00 PM
Nice.

**Comment by BitFis** [comment]
Whats the status of this? I am interested of decoupling picoQuic from openssl. Where should I start?
Thanks a lot.

**Comment by huitema** [comment]
@BitFis I would love the help. I am working on the socket code, because that's where 60% of the CPU is spent today, and was planning to move to the fusion work after that's done. 

The code changes for fusion should be limited to tls_api.c, except if we want to fuse "header protection" and "packet protection", which are orchestrated in "sender.c" and "packet.c". There may be a need to update some of the tests, or maybe add a specific test for the fusion case.

**Comment by BitFis** [comment]
@huitema sounds good, I will look into this. My current goal is to enable picoQuic to be run on embedded devices.

**Comment by huitema** [comment]
@BitFis -- I opened issue #1057 to track the possibility of replacing OpenSSL. Comments are welcome.

**Comment by huitema** [comment]
Fusion is now supported per PR #1064, which technically solves this issue. The next step would be to use the combined mode for header protection and packet protection, which will be done eventually as part of the performance work.
