### ISSUE TITLE
Finding files responsible for retransmission

### ISSUE THREAD

**Issue by mayankmclaren** [private-octopus/picoquic#961]
Hi,
I'm trying to find the files responsible for the retransmission of frames in a stream.
Can you please help me with it and tell me what are those files?

**Comment by huitema** [comment]
The packet loss detection is in sender.c. Start with `picoquic_retransmit_needed` at line 1244. It calls the function `picoquic_retransmit_needed_by_packet` at line 1093.

**Comment by huitema** [comment]
@mayankmclaren Do you need to keep this issue open?

**Comment by mayankmclaren** [comment]
Thank you for your reply, I'll close this issue.
I'm following your replies to @matalbap on issue #962 and #741. We are trying to accomplish unreliability with picoqiuc.
