### ISSUE TITLE
Unreliable extension on picoquic.

### ISSUE THREAD

**Issue by matlabap** [private-octopus/picoquic#962]
Which part of picoquic supports retransmission?
Is there any extension for supporting unreliability in picoquic?

**Comment by huitema** [comment]
1) in sender.c, check `picoquic_retransmit_needed` line 1244, which calls `picoquic_retransmit_needed_by_packet` line 1093 and also calls `picoquic_copy_before_retransmit` line 1177.

2) there is support for out of order delivery, through the "direct receive" API. Check the description in `picoquic.h`, lines 615-655.

The direct receive API allows application to receive fragments of data streams as soon as they arrive, even if not received in order. It provides much of the benefits of the "unreliability" services, but missing data will still be retransmitted. 

If you don't mind, can we have the unreliability discussion in issue #741? To get rid of retransmission, we need a negotiation between client and server, and probably an extension frame to indicate which parts of the stream do not need retransmission. There is no clear consensus yet. If you want to develop an extension for that, i will be happy to review a PR!

**Comment by huitema** [comment]
About retransmission, I forgot to mention that when ACK of packets containing stream frames are received, the code executes `picoquic_process_ack_of_stream_frame` (`frames.c`, line 2359). This maintains a list of stream segments that are already received, and thus will not be retransmitted.

**Comment by huitema** [comment]
@matlabap Please see the extended discussion in issue #741. Do you want to keep your specific issue open?

**Comment by matlabap** [comment]
Thank you! I will follow the discussion on issue #741.
