### ISSUE TITLE
Intergration of PICOQUIC with Chromium.

### ISSUE THREAD

**Issue by mayankmclaren** [private-octopus/picoquic#968]
Hi,
I wanted to know that if picoquic can be used with Chromium? 
Do you support HTTP handshake? 
And also can I transfer my own dummy data like pictures and videos using picoquic? If yes then please tell me how.

**Comment by huitema** [comment]
Picoquic does support the HTTP-3 handshake. I have not tested the Chrome client against a picoquic server, but the [interop matrix for draft 28](https://docs.google.com/spreadsheets/d/1D0tW89vOoaScs3IY9RGC0UesWGAwE6xyLk0l4JtvTVg/edit#gid=1248220598) shows successful access from Google Quic to the Picoquic server. You will have to convince Chrome (or Chromium) to use the IETF draft 28 version of QUIC. I am not an expert on that.

**Comment by mayankmclaren** [comment]
Thanks for answering, what about sending dummy data?

**Comment by huitema** [comment]
The server (picoquicdemo) can be programmed with a folder name. It will serve files found in that folder.

**Comment by mayankmclaren** [comment]
Thank you
