### ISSUE TITLE
Error for picotls/ffx.h file 

### ISSUE THREAD

**Issue by AbhishiktaP** [private-octopus/picoquic#983]
I tried making picoquic and I am getting a an error for picotls/ffx.h file. How should i overcome it?

[Screenshot from 2020-07-10 19-00-40](https://user-images.githubusercontent.com/41802409/87159963-c5c8fb00-c2df-11ea-976e-f8ac8c207fe6.png)

**Comment by huitema** [comment]
'ffx.h' is in the folder ['(picotls)/include/picotls'](https://github.com/h2o/picotls/blob/master/include/picotls/ffx.h) . That's the same location as 'picotls/openssl.h', which you also need. Do you have a recent install of picotls? It should be there.

**Comment by huitema** [comment]
@AbhishiktaP the latest version of picoquic removes the dependency on `ffx.h`. If your problem is not solved yet, please upgrade to that latest version.

**Comment by huitema** [comment]
Considering this closed.
