### ISSUE TITLE
picoquic_sample Could not load tokens from <sample_token_store.bin>.

### ISSUE THREAD

**Issue by erfanw** [private-octopus/picoquic#996]
Hi,

I am trying to execute the codes from picoquic_sample following the instructions in the Readme file in /picoquic/sample. After I ran the client with the server already running, however, I encountered this problem:

`Could not load tokens from <sample_token_store.bin>.`

What's wrong here?

**Comment by huitema** [comment]
Nothing is wrong, except perhaps the text of the message. The file containing tickets or tokens are created on first use, to enable 0rtt on later connections to the same server. Any suggestion of better text?

**Comment by huitema** [comment]
@erfanw New text proposed in PR #997. Would it be less surprising?

**Comment by erfanw** [comment]
Thank you very much for the pull request. However, I met this problem in picoquic_sample, rather than in picoquicdemo. Actually there was no problem with picoquicdemo.

**Comment by huitema** [comment]
Thanks for the feedback. There is clearly something bad happening, but it is not related to the tokens file.

The sample was written to provide an example of usage of developing an application on top of the QUIC transport implemented in Picoquic. I realize that people are using it as an example of running an application. From that point of view, the sample is a bit incomplete. The client only prints a few messages, and you don't see the progress. The server is completely silent, which is fine in operations but does not help in your case.

Server and clients are in fact programmed to create logs. These are placed by default in these folders:
#define PICOQUIC_SAMPLE_CLIENT_BINLOG_DIR "sample_client_log";
#define PICOQUIC_SAMPLE_SERVER_BINLOG_DIR "sample_server_log";
Client and server create binary logs, that can be transformed in text versions using `picolog_t`. This is a bit of a hidden feature, which is not great for a sample. I suppose I could document it some more...

**Comment by huitema** [comment]
@erfanw I have reproduced your issue. The message `index.html: reset, received 0 bytes` indicates that the server did not find the file "/server_files/index.html". Are you sure that you created these folders directly under the root of your system, by opposition to within your home directory?

I have revised the way the sample does logging, producing now readable "qlog" files instead of the more difficult binary files, and I have updated the "README" text.

**Comment by huitema** [comment]
Also made the message more explicit, printing the reason cause in the report, as in:
```
No token file present. Will create one as <sample_token_store.bin>.
Starting connection to localhost, port 4567
Initial connection ID: d9229d4eb6d2a0f3
Opened stream 0 for file index.html
Connection to the server completed, almost ready.
Connection to the server confirmed.
All done, closing the connection.
Connection closed.
index.html: reset, received 0 bytes, error 0x103 -- no such file
```

**Comment by huitema** [comment]
@erfanw I think these changes should resolve the issue. Do you agree?

**Comment by erfanw** [comment]
Hi,

Yes I think this makes the whole process more user-friendly. Thank you very much. You are so helpful. I will try later if the problem with the file can be solved.

Best Regards,
Erfan

________________________________
